// Gerado por nexo-one/scripts/gen_narration.py (NEXO): matriz cabeça x cauda por evento, sorteada a cada linha.
export const NARRATION: Record<string, { heads: string[]; tails: string[] }> = {
 "SEMANTIC_BACKFILLED": {
  "heads": [
   "Dei nome e leitura simples a %q",
   "Traduzi para português %q",
   "Arrumei a ficha de %q",
   "Reescrevi a pergunta de %q",
   "Dei um nome humano a %q",
   "Deixei %q legível",
   "Sem esperar ninguém, deixei %q legível",
   "Como combinado, reescrevi a pergunta de %q",
   "Com calma, dei nome e leitura simples a %q",
   "No meu turno, arrumei a ficha de %q",
   "No meu turno, dei um nome humano a %q",
   "No meu turno, deixei %q legível",
   "Antes de seguir, dei um nome humano a %q",
   "No meu turno, traduzi para português %q",
   "Sem pular etapa, arrumei a ficha de %q",
   "Enquanto o resto rodava, traduzi para português %q",
   "Antes de seguir, reescrevi a pergunta de %q",
   "Enquanto o resto rodava, arrumei a ficha de %q",
   "Como combinado, deixei %q legível",
   "Antes de seguir, arrumei a ficha de %q",
   "Mais uma vez, deixei %q legível",
   "Antes de seguir, traduzi para português %q",
   "Como sempre, traduzi para português %q",
   "Como sempre, deixei %q legível",
   "Seguindo a fila, dei nome e leitura simples a %q",
   "Por conta própria, arrumei a ficha de %q",
   "Por conta própria, reescrevi a pergunta de %q",
   "Agora há pouco, reescrevi a pergunta de %q",
   "Agora há pouco, deixei %q legível",
   "Com calma, deixei %q legível",
   "No ritmo de sempre, dei um nome humano a %q",
   "Sem alarde, arrumei a ficha de %q",
   "Sem ninguém pedir, deixei %q legível",
   "Agora há pouco, traduzi para português %q",
   "Como sempre, dei nome e leitura simples a %q",
   "Para não perder o fio, reescrevi a pergunta de %q",
   "Sem alarde, dei um nome humano a %q",
   "Nesta rodada, dei nome e leitura simples a %q",
   "Ainda agora, dei um nome humano a %q",
   "Nesta rodada, reescrevi a pergunta de %q",
   "Sem esperar ninguém, arrumei a ficha de %q",
   "Mais uma vez, dei um nome humano a %q",
   "Mais uma vez, reescrevi a pergunta de %q",
   "Como combinado, arrumei a ficha de %q",
   "Sem alarde, traduzi para português %q"
  ],
  "tails": [
   ".",
   " para qualquer pessoa entender.",
   ", agora dá para ler sem sigla.",
   "; ninguém precisa decifrar código.",
   ", do jeito que o site mostra.",
   " antes que virasse sopa de IDs.",
   "; clareza também é dado.",
   ", sem jargão desnecessário.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "TEST_ENRICHED": {
  "heads": [
   "Completei a ficha de %q",
   "Preenchi o que faltava em %q",
   "Fechei as lacunas de %q",
   "Revisei o contrato de %q",
   "Deixei %q pronto para rodar",
   "Juntei método e critério em %q",
   "Ainda agora, deixei %q pronto para rodar",
   "Mais uma vez, revisei o contrato de %q",
   "Para não perder o fio, revisei o contrato de %q",
   "Enquanto o resto rodava, juntei método e critério em %q",
   "Por conta própria, juntei método e critério em %q",
   "Seguindo a fila, juntei método e critério em %q",
   "Com calma, juntei método e critério em %q",
   "Sem ninguém pedir, completei a ficha de %q",
   "Antes de seguir, preenchi o que faltava em %q",
   "Por conta própria, revisei o contrato de %q",
   "No meu turno, revisei o contrato de %q",
   "Agora há pouco, completei a ficha de %q",
   "Com calma, revisei o contrato de %q",
   "Sem ninguém pedir, deixei %q pronto para rodar",
   "Sem ninguém pedir, revisei o contrato de %q",
   "No ritmo de sempre, preenchi o que faltava em %q",
   "Agora há pouco, revisei o contrato de %q",
   "Enquanto o resto rodava, completei a ficha de %q",
   "Mais uma vez, fechei as lacunas de %q",
   "Para não perder o fio, preenchi o que faltava em %q",
   "Na mesma rodada, revisei o contrato de %q",
   "Como combinado, juntei método e critério em %q",
   "Na mesma rodada, preenchi o que faltava em %q",
   "Sem pular etapa, deixei %q pronto para rodar",
   "Sem esperar ninguém, revisei o contrato de %q",
   "Como sempre, fechei as lacunas de %q",
   "Sem pular etapa, fechei as lacunas de %q",
   "Agora há pouco, deixei %q pronto para rodar",
   "Antes de seguir, fechei as lacunas de %q",
   "Como combinado, preenchi o que faltava em %q",
   "Agora há pouco, juntei método e critério em %q",
   "Com calma, fechei as lacunas de %q",
   "Para não perder o fio, deixei %q pronto para rodar",
   "Para não perder o fio, completei a ficha de %q",
   "Antes de seguir, completei a ficha de %q",
   "Para não perder o fio, juntei método e critério em %q",
   "Como sempre, deixei %q pronto para rodar",
   "Sem alarde, juntei método e critério em %q",
   "Ainda agora, fechei as lacunas de %q"
  ],
  "tails": [
   ".",
   "; agora ele pode ir para a bateria.",
   ", com dado e critério no lugar.",
   "; papelada resolvida na hora.",
   " sem esperar ninguém.",
   ", do jeito que o robô aceita.",
   "; faltava pouco.",
   " e segui para o próximo.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "LEARNING_SIGNAL_RECORDED": {
  "heads": [
   "Anotei uma lacuna",
   "Achei um buraco no caminho",
   "Pedi uma ferramenta que ainda não existe",
   "Marquei o que está segurando a fila",
   "Registrei o que falta",
   "Deixei um pedido para o Engenheiro",
   "Encontrei um teste sem receita",
   "Para não perder o fio, encontrei um teste sem receita",
   "Sem ninguém pedir, pedi uma ferramenta que ainda não existe",
   "Como combinado, pedi uma ferramenta que ainda não existe",
   "Nesta rodada, marquei o que está segurando a fila",
   "Ainda agora, achei um buraco no caminho",
   "Ainda agora, marquei o que está segurando a fila",
   "Agora há pouco, pedi uma ferramenta que ainda não existe",
   "Enquanto o resto rodava, deixei um pedido para o Engenheiro",
   "No ritmo de sempre, anotei uma lacuna",
   "Como sempre, encontrei um teste sem receita",
   "Agora há pouco, registrei o que falta",
   "Como sempre, achei um buraco no caminho",
   "Seguindo a fila, deixei um pedido para o Engenheiro",
   "Enquanto o resto rodava, encontrei um teste sem receita",
   "Como combinado, achei um buraco no caminho",
   "Sem pular etapa, anotei uma lacuna",
   "Para não perder o fio, deixei um pedido para o Engenheiro",
   "Para não perder o fio, anotei uma lacuna",
   "No meu turno, registrei o que falta",
   "Como combinado, deixei um pedido para o Engenheiro",
   "Agora há pouco, deixei um pedido para o Engenheiro",
   "Sem esperar ninguém, pedi uma ferramenta que ainda não existe",
   "Na mesma rodada, deixei um pedido para o Engenheiro",
   "No meu turno, anotei uma lacuna",
   "Sem ninguém pedir, marquei o que está segurando a fila",
   "Sem alarde, registrei o que falta",
   "Sem alarde, encontrei um teste sem receita",
   "Enquanto o resto rodava, registrei o que falta",
   "Antes de seguir, achei um buraco no caminho",
   "Como sempre, registrei o que falta",
   "No ritmo de sempre, deixei um pedido para o Engenheiro",
   "Mais uma vez, deixei um pedido para o Engenheiro",
   "Seguindo a fila, marquei o que está segurando a fila",
   "Por conta própria, anotei uma lacuna",
   "Com calma, pedi uma ferramenta que ainda não existe",
   "No meu turno, pedi uma ferramenta que ainda não existe",
   "No ritmo de sempre, encontrei um teste sem receita",
   "Sem pular etapa, registrei o que falta"
  ],
  "tails": [
   ".",
   " para o dono resolver.",
   ": receita ou dado que falta.",
   "; quem pode destravar já sabe.",
   " e segui com o que dava para fazer.",
   ", sem parar a fila por isso.",
   "; vira trabalho na próxima rodada.",
   " com o motivo escrito.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "TEST_DISPATCHED": {
  "heads": [
   "Mandei para a bateria %q",
   "Coloquei %q para rodar",
   "%q saiu da fila",
   "Liguei a máquina em %q",
   "Soltei %q no runner",
   "Despachei %q",
   "%q entrou em execução",
   "Entre uma bateria e outra, liguei a máquina em %q",
   "Sem alarde, soltei %q no runner",
   "Ainda agora, soltei %q no runner",
   "Sem esperar ninguém, coloquei %q para rodar",
   "Com calma, mandei para a bateria %q",
   "Nesta rodada, coloquei %q para rodar",
   "Seguindo a fila, coloquei %q para rodar",
   "Agora há pouco, %q entrou em execução",
   "Como combinado, liguei a máquina em %q",
   "Entre uma bateria e outra, %q saiu da fila",
   "Ainda agora, mandei para a bateria %q",
   "Para não perder o fio, coloquei %q para rodar",
   "Nesta rodada, mandei para a bateria %q",
   "Enquanto o resto rodava, liguei a máquina em %q",
   "No meu turno, %q entrou em execução",
   "Mais uma vez, %q entrou em execução",
   "Sem esperar ninguém, despachei %q",
   "Para não perder o fio, %q saiu da fila",
   "Antes de seguir, liguei a máquina em %q",
   "Ainda agora, %q saiu da fila",
   "Antes de seguir, soltei %q no runner",
   "Seguindo a fila, mandei para a bateria %q",
   "No meu turno, soltei %q no runner",
   "Nesta rodada, %q entrou em execução",
   "Mais uma vez, liguei a máquina em %q",
   "Por conta própria, %q entrou em execução",
   "Entre uma bateria e outra, coloquei %q para rodar",
   "Por conta própria, %q saiu da fila",
   "Seguindo a fila, despachei %q",
   "Mais uma vez, %q saiu da fila",
   "Sem pular etapa, %q saiu da fila",
   "No meu turno, %q saiu da fila",
   "Na mesma rodada, soltei %q no runner",
   "Sem ninguém pedir, liguei a máquina em %q",
   "Enquanto o resto rodava, %q saiu da fila",
   "Sem esperar ninguém, liguei a máquina em %q",
   "Nesta rodada, liguei a máquina em %q",
   "Como sempre, %q saiu da fila"
  ],
  "tails": [
   ".",
   "; agora é esperar a conta.",
   ", critério já congelado.",
   " com dado público e receita fixa.",
   "; volta em alguns minutos.",
   " sem ninguém apertar botão.",
   ", junto com o lote.",
   "; o robô cuida do resto.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "TEST_RESULT_RECORDED": {
  "heads": [
   "Terminei um teste: %q",
   "Chegou o resultado de %q",
   "%q voltou da bateria",
   "Fechei a conta de %q",
   "Saiu o veredito de %q",
   "A bateria devolveu %q",
   "Agora há pouco, a bateria devolveu %q",
   "Mais uma vez, a bateria devolveu %q",
   "Antes de seguir, %q voltou da bateria",
   "Sem alarde, %q voltou da bateria",
   "Entre uma bateria e outra, terminei um teste: %q",
   "No ritmo de sempre, saiu o veredito de %q",
   "Sem pular etapa, %q voltou da bateria",
   "Com calma, chegou o resultado de %q",
   "Antes de seguir, fechei a conta de %q",
   "Como sempre, a bateria devolveu %q",
   "Enquanto o resto rodava, %q voltou da bateria",
   "No ritmo de sempre, chegou o resultado de %q",
   "Mais uma vez, saiu o veredito de %q",
   "Seguindo a fila, a bateria devolveu %q",
   "Ainda agora, fechei a conta de %q",
   "No ritmo de sempre, fechei a conta de %q",
   "Sem esperar ninguém, terminei um teste: %q",
   "Para não perder o fio, fechei a conta de %q",
   "Seguindo a fila, chegou o resultado de %q",
   "Agora há pouco, terminei um teste: %q",
   "Antes de seguir, saiu o veredito de %q",
   "No meu turno, %q voltou da bateria",
   "Para não perder o fio, %q voltou da bateria",
   "Sem ninguém pedir, chegou o resultado de %q",
   "Enquanto o resto rodava, fechei a conta de %q",
   "Por conta própria, %q voltou da bateria",
   "Entre uma bateria e outra, %q voltou da bateria",
   "Sem ninguém pedir, %q voltou da bateria",
   "Nesta rodada, %q voltou da bateria",
   "No meu turno, a bateria devolveu %q",
   "Por conta própria, saiu o veredito de %q",
   "Por conta própria, terminei um teste: %q",
   "Enquanto o resto rodava, terminei um teste: %q",
   "Como sempre, chegou o resultado de %q",
   "Com calma, %q voltou da bateria",
   "Sem alarde, a bateria devolveu %q",
   "Ainda agora, %q voltou da bateria",
   "Sem pular etapa, terminei um teste: %q",
   "Na mesma rodada, fechei a conta de %q"
  ],
  "tails": [
   ".",
   "; o critério decide, não eu.",
   ", e ficou registrado.",
   " com os números na ficha.",
   "; próximo passo é atacar.",
   ", sem mexer na trave.",
   "; mais um tijolo no mapa.",
   " e o site já mostra.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "ROADMAP_TEST_FROZEN": {
  "heads": [
   "Congelei as regras antes de olhar os dados: %q",
   "Travei o critério de %q",
   "Escrevi o que derrubaria %q",
   "Pré-registrei %q",
   "Fixei sucesso e kill de %q",
   "Tranquei a trave de %q",
   "Por conta própria, congelei as regras antes de olhar os dados: %q",
   "Sem alarde, fixei sucesso e kill de %q",
   "Enquanto o resto rodava, pré-registrei %q",
   "Ainda agora, fixei sucesso e kill de %q",
   "Sem pular etapa, escrevi o que derrubaria %q",
   "Como sempre, escrevi o que derrubaria %q",
   "Nesta rodada, tranquei a trave de %q",
   "Ainda agora, escrevi o que derrubaria %q",
   "Ainda agora, congelei as regras antes de olhar os dados: %q",
   "Sem pular etapa, tranquei a trave de %q",
   "Antes de seguir, pré-registrei %q",
   "Como sempre, congelei as regras antes de olhar os dados: %q",
   "Antes de seguir, travei o critério de %q",
   "Entre uma bateria e outra, tranquei a trave de %q",
   "Para não perder o fio, fixei sucesso e kill de %q",
   "Seguindo a fila, fixei sucesso e kill de %q",
   "Enquanto o resto rodava, travei o critério de %q",
   "Antes de seguir, congelei as regras antes de olhar os dados: %q",
   "No meu turno, pré-registrei %q",
   "No ritmo de sempre, tranquei a trave de %q",
   "Como combinado, travei o critério de %q",
   "Mais uma vez, escrevi o que derrubaria %q",
   "Mais uma vez, tranquei a trave de %q",
   "Mais uma vez, pré-registrei %q",
   "Sem pular etapa, travei o critério de %q",
   "Agora há pouco, travei o critério de %q",
   "Entre uma bateria e outra, escrevi o que derrubaria %q",
   "Seguindo a fila, escrevi o que derrubaria %q",
   "Mais uma vez, fixei sucesso e kill de %q",
   "Nesta rodada, pré-registrei %q",
   "Nesta rodada, escrevi o que derrubaria %q",
   "Por conta própria, tranquei a trave de %q",
   "Sem ninguém pedir, congelei as regras antes de olhar os dados: %q",
   "Seguindo a fila, tranquei a trave de %q",
   "Sem alarde, travei o critério de %q",
   "Com calma, escrevi o que derrubaria %q",
   "Sem ninguém pedir, tranquei a trave de %q",
   "Seguindo a fila, travei o critério de %q",
   "Enquanto o resto rodava, congelei as regras antes de olhar os dados: %q"
  ],
  "tails": [
   ".",
   " antes de ver o resultado.",
   "; depois disso ninguém mexe.",
   ", para não me enganar depois.",
   " com a previsão anotada.",
   "; o dado decide sozinho.",
   ", do jeito que a ciência pede.",
   " e só então liberei a execução.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "RESULT_CONTESTED": {
  "heads": [
   "Não confiei no resultado e abri um ataque: %q",
   "Fui atrás do ponto fraco de %q",
   "Coloquei %q à prova",
   "Duvidei de %q",
   "Montei o contra-teste de %q",
   "Ataquei %q",
   "Resolvi testar %q de novo",
   "Seguindo a fila, resolvi testar %q de novo",
   "Para não perder o fio, não confiei no resultado e abri um ataque: %q",
   "Como sempre, montei o contra-teste de %q",
   "Ainda agora, duvidei de %q",
   "Como sempre, coloquei %q à prova",
   "Seguindo a fila, não confiei no resultado e abri um ataque: %q",
   "Entre uma bateria e outra, resolvi testar %q de novo",
   "No ritmo de sempre, fui atrás do ponto fraco de %q",
   "Por conta própria, duvidei de %q",
   "No ritmo de sempre, coloquei %q à prova",
   "Como sempre, duvidei de %q",
   "Na mesma rodada, montei o contra-teste de %q",
   "Como combinado, montei o contra-teste de %q",
   "Na mesma rodada, coloquei %q à prova",
   "Antes de seguir, resolvi testar %q de novo",
   "Para não perder o fio, montei o contra-teste de %q",
   "Enquanto o resto rodava, duvidei de %q",
   "Enquanto o resto rodava, ataquei %q",
   "Antes de seguir, duvidei de %q",
   "Sem esperar ninguém, ataquei %q",
   "Como combinado, não confiei no resultado e abri um ataque: %q",
   "Nesta rodada, coloquei %q à prova",
   "Com calma, duvidei de %q",
   "Nesta rodada, não confiei no resultado e abri um ataque: %q",
   "Nesta rodada, duvidei de %q",
   "Mais uma vez, coloquei %q à prova",
   "Entre uma bateria e outra, duvidei de %q",
   "Ainda agora, fui atrás do ponto fraco de %q",
   "Sem pular etapa, não confiei no resultado e abri um ataque: %q",
   "Sem esperar ninguém, coloquei %q à prova",
   "Enquanto o resto rodava, coloquei %q à prova",
   "No ritmo de sempre, não confiei no resultado e abri um ataque: %q",
   "Para não perder o fio, duvidei de %q",
   "Sem alarde, coloquei %q à prova",
   "Sem alarde, resolvi testar %q de novo",
   "Sem esperar ninguém, montei o contra-teste de %q",
   "Nesta rodada, montei o contra-teste de %q",
   "Sem alarde, montei o contra-teste de %q"
  ],
  "tails": [
   ".",
   " com outro dado.",
   "; se for real, aguenta.",
   ", por outro caminho.",
   " com critério congelado.",
   "; resultado bonito demais pede ataque.",
   " antes de acreditar.",
   ", trocando a coleção de supernovas.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "RESULT_REFEREE1_PASSED": {
  "heads": [
   "O resultado sobreviveu ao primeiro ataque: %q",
   "%q aguentou o primeiro golpe",
   "%q passou pelo contra-teste",
   "O ataque não derrubou %q",
   "%q segurou o tranco",
   "Tentei derrubar %q e não consegui",
   "Para não perder o fio, o ataque não derrubou %q",
   "Nesta rodada, o ataque não derrubou %q",
   "Agora há pouco, %q passou pelo contra-teste",
   "Sem esperar ninguém, o resultado sobreviveu ao primeiro ataque: %q",
   "Sem ninguém pedir, tentei derrubar %q e não consegui",
   "No ritmo de sempre, o ataque não derrubou %q",
   "Mais uma vez, o resultado sobreviveu ao primeiro ataque: %q",
   "Ainda agora, %q segurou o tranco",
   "Entre uma bateria e outra, %q aguentou o primeiro golpe",
   "Sem ninguém pedir, %q segurou o tranco",
   "Enquanto o resto rodava, %q passou pelo contra-teste",
   "Para não perder o fio, %q aguentou o primeiro golpe",
   "Agora há pouco, %q segurou o tranco",
   "No ritmo de sempre, %q aguentou o primeiro golpe",
   "Sem pular etapa, %q aguentou o primeiro golpe",
   "Sem alarde, %q aguentou o primeiro golpe",
   "Por conta própria, %q aguentou o primeiro golpe",
   "Sem ninguém pedir, %q aguentou o primeiro golpe",
   "Mais uma vez, %q aguentou o primeiro golpe",
   "Como sempre, %q aguentou o primeiro golpe",
   "Sem alarde, o resultado sobreviveu ao primeiro ataque: %q",
   "Entre uma bateria e outra, %q segurou o tranco",
   "No meu turno, o resultado sobreviveu ao primeiro ataque: %q",
   "Para não perder o fio, %q segurou o tranco",
   "Com calma, %q aguentou o primeiro golpe",
   "Para não perder o fio, tentei derrubar %q e não consegui",
   "Agora há pouco, o ataque não derrubou %q",
   "Enquanto o resto rodava, o ataque não derrubou %q",
   "Enquanto o resto rodava, tentei derrubar %q e não consegui",
   "Mais uma vez, %q segurou o tranco",
   "No meu turno, tentei derrubar %q e não consegui",
   "Como sempre, o ataque não derrubou %q",
   "Antes de seguir, tentei derrubar %q e não consegui",
   "Como combinado, tentei derrubar %q e não consegui",
   "Agora há pouco, o resultado sobreviveu ao primeiro ataque: %q",
   "Sem esperar ninguém, tentei derrubar %q e não consegui",
   "Seguindo a fila, %q aguentou o primeiro golpe",
   "Por conta própria, %q passou pelo contra-teste",
   "Com calma, o ataque não derrubou %q"
  ],
  "tails": [
   ".",
   "; ficou mais sólido.",
   ", e sigo desconfiando.",
   " com outro dado.",
   "; bom sinal.",
   ", por enquanto de pé.",
   " e segue para o próximo teste.",
   "; ponto para ele.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "RESULT_REFUTED": {
  "heads": [
   "Derrubei uma conclusão minha: %q",
   "%q caiu no ataque",
   "Errei em %q",
   "O contra-teste desmontou %q",
   "%q não resistiu",
   "Refutei %q",
   "Com calma, %q caiu no ataque",
   "Entre uma bateria e outra, derrubei uma conclusão minha: %q",
   "No ritmo de sempre, %q caiu no ataque",
   "Mais uma vez, o contra-teste desmontou %q",
   "Com calma, refutei %q",
   "Mais uma vez, errei em %q",
   "Sem ninguém pedir, o contra-teste desmontou %q",
   "No ritmo de sempre, refutei %q",
   "Como sempre, %q caiu no ataque",
   "Sem pular etapa, o contra-teste desmontou %q",
   "Com calma, errei em %q",
   "Seguindo a fila, errei em %q",
   "Por conta própria, refutei %q",
   "Na mesma rodada, derrubei uma conclusão minha: %q",
   "Sem pular etapa, errei em %q",
   "Antes de seguir, %q caiu no ataque",
   "Para não perder o fio, %q não resistiu",
   "Entre uma bateria e outra, refutei %q",
   "Entre uma bateria e outra, %q não resistiu",
   "Mais uma vez, derrubei uma conclusão minha: %q",
   "Na mesma rodada, errei em %q",
   "Com calma, o contra-teste desmontou %q",
   "Seguindo a fila, refutei %q",
   "Como sempre, derrubei uma conclusão minha: %q",
   "Mais uma vez, %q caiu no ataque",
   "Mais uma vez, refutei %q",
   "Entre uma bateria e outra, errei em %q",
   "Como combinado, o contra-teste desmontou %q",
   "No meu turno, refutei %q",
   "Ainda agora, errei em %q",
   "Na mesma rodada, %q caiu no ataque",
   "Sem pular etapa, %q não resistiu",
   "Agora há pouco, refutei %q",
   "Antes de seguir, %q não resistiu",
   "Ainda agora, o contra-teste desmontou %q",
   "No ritmo de sempre, errei em %q",
   "Sem esperar ninguém, errei em %q",
   "Sem ninguém pedir, refutei %q",
   "Enquanto o resto rodava, %q caiu no ataque"
  ],
  "tails": [
   ".",
   " e agora sei onde.",
   "; errar rápido é o objetivo.",
   ", e a rival já está na fila.",
   "; queda também é resultado.",
   " sem choro, com registro.",
   ", melhor agora do que num paper.",
   "; o mapa ficou mais honesto.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "RESULT_CONFIRMED": {
  "heads": [
   "Confirmado depois do ataque independente: %q",
   "%q resistiu e virou resultado firme",
   "Outro dado, mesma resposta: %q",
   "%q passou no teste que podia derrubar",
   "Fechou: %q",
   "Antes de seguir, outro dado, mesma resposta: %q",
   "Entre uma bateria e outra, outro dado, mesma resposta: %q",
   "Com calma, %q passou no teste que podia derrubar",
   "Para não perder o fio, %q passou no teste que podia derrubar",
   "Enquanto o resto rodava, %q resistiu e virou resultado firme",
   "Nesta rodada, %q passou no teste que podia derrubar",
   "Ainda agora, fechou: %q",
   "Para não perder o fio, %q resistiu e virou resultado firme",
   "Sem ninguém pedir, outro dado, mesma resposta: %q",
   "No meu turno, confirmado depois do ataque independente: %q",
   "Como sempre, fechou: %q",
   "Como combinado, %q passou no teste que podia derrubar",
   "Por conta própria, %q resistiu e virou resultado firme",
   "Sem pular etapa, fechou: %q",
   "Enquanto o resto rodava, outro dado, mesma resposta: %q",
   "Seguindo a fila, %q passou no teste que podia derrubar",
   "Na mesma rodada, confirmado depois do ataque independente: %q",
   "Nesta rodada, confirmado depois do ataque independente: %q",
   "Sem esperar ninguém, confirmado depois do ataque independente: %q",
   "Nesta rodada, %q resistiu e virou resultado firme",
   "No meu turno, outro dado, mesma resposta: %q",
   "Sem alarde, fechou: %q",
   "Ainda agora, confirmado depois do ataque independente: %q",
   "Enquanto o resto rodava, fechou: %q",
   "Entre uma bateria e outra, fechou: %q",
   "Sem ninguém pedir, confirmado depois do ataque independente: %q",
   "No meu turno, %q resistiu e virou resultado firme",
   "Nesta rodada, fechou: %q",
   "Como sempre, confirmado depois do ataque independente: %q",
   "Seguindo a fila, %q resistiu e virou resultado firme",
   "No ritmo de sempre, outro dado, mesma resposta: %q",
   "Por conta própria, confirmado depois do ataque independente: %q",
   "Com calma, fechou: %q",
   "Sem esperar ninguém, %q resistiu e virou resultado firme",
   "No ritmo de sempre, confirmado depois do ataque independente: %q",
   "Mais uma vez, %q passou no teste que podia derrubar",
   "Sem pular etapa, confirmado depois do ataque independente: %q",
   "Para não perder o fio, confirmado depois do ataque independente: %q",
   "No ritmo de sempre, %q passou no teste que podia derrubar",
   "Na mesma rodada, outro dado, mesma resposta: %q"
  ],
  "tails": [
   ".",
   "; esse fica.",
   ", com a força que o dado tem.",
   " com outra coleção de supernovas.",
   "; entra no mapa.",
   ", depois de tentar derrubar.",
   "; replicou.",
   " e conta para a campanha.",
   "; agora é base para o próximo.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora."
  ]
 },
 "HYPOTHESIS_UPSERTED": {
  "heads": [
   "Tive uma ideia nova para testar: %q",
   "Nova pergunta na mesa: %q",
   "Abri uma frente nova: %q",
   "Formulei %q",
   "Quero saber: %q",
   "Surgiu uma hipótese: %q",
   "Pensei em %q",
   "Nesta rodada, surgiu uma hipótese: %q",
   "Com calma, surgiu uma hipótese: %q",
   "Sem esperar ninguém, quero saber: %q",
   "Nesta rodada, tive uma ideia nova para testar: %q",
   "Como sempre, nova pergunta na mesa: %q",
   "Nesta rodada, formulei %q",
   "Nesta rodada, abri uma frente nova: %q",
   "Agora há pouco, quero saber: %q",
   "Para não perder o fio, abri uma frente nova: %q",
   "Com calma, abri uma frente nova: %q",
   "Enquanto o resto rodava, pensei em %q",
   "Para não perder o fio, tive uma ideia nova para testar: %q",
   "Na mesma rodada, abri uma frente nova: %q",
   "Sem esperar ninguém, pensei em %q",
   "Sem ninguém pedir, formulei %q",
   "Ainda agora, abri uma frente nova: %q",
   "No ritmo de sempre, nova pergunta na mesa: %q",
   "Mais uma vez, pensei em %q",
   "Sem alarde, quero saber: %q",
   "Com calma, tive uma ideia nova para testar: %q",
   "Por conta própria, pensei em %q",
   "Por conta própria, abri uma frente nova: %q",
   "Mais uma vez, tive uma ideia nova para testar: %q",
   "Sem esperar ninguém, formulei %q",
   "Sem ninguém pedir, quero saber: %q",
   "Como sempre, formulei %q",
   "Agora há pouco, surgiu uma hipótese: %q",
   "Entre uma bateria e outra, nova pergunta na mesa: %q",
   "Ainda agora, pensei em %q",
   "Por conta própria, formulei %q",
   "Agora há pouco, formulei %q",
   "Ainda agora, quero saber: %q",
   "Antes de seguir, tive uma ideia nova para testar: %q",
   "Nesta rodada, nova pergunta na mesa: %q",
   "No ritmo de sempre, surgiu uma hipótese: %q",
   "Mais uma vez, abri uma frente nova: %q",
   "Antes de seguir, nova pergunta na mesa: %q",
   "Como combinado, nova pergunta na mesa: %q"
  ],
  "tails": [
   ".",
   "; já com o que a derrubaria.",
   ", nasce com nula e rival.",
   " para a fila.",
   "; vamos ver se aguenta.",
   ", saída de um resultado de ontem.",
   " e o critério vem junto.",
   "; se morrer, aprendo.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "INTEGRITY_REPORT_RECORDED": {
  "heads": [
   "Auditei a mim mesmo",
   "Conferi a saúde do sistema",
   "Passei o pente-fino",
   "Medi o quanto estou funcionando sozinho",
   "Chequei se algum agente parou",
   "Olhei filas, papéis e robô",
   "Fiz a ronda",
   "Na mesma rodada, chequei se algum agente parou",
   "Com calma, chequei se algum agente parou",
   "Sem ninguém pedir, conferi a saúde do sistema",
   "Sem alarde, medi o quanto estou funcionando sozinho",
   "Sem esperar ninguém, passei o pente-fino",
   "Ainda agora, fiz a ronda",
   "Entre uma bateria e outra, medi o quanto estou funcionando sozinho",
   "Agora há pouco, medi o quanto estou funcionando sozinho",
   "Sem pular etapa, fiz a ronda",
   "Sem alarde, auditei a mim mesmo",
   "Ainda agora, passei o pente-fino",
   "Para não perder o fio, conferi a saúde do sistema",
   "Por conta própria, chequei se algum agente parou",
   "Agora há pouco, conferi a saúde do sistema",
   "No ritmo de sempre, medi o quanto estou funcionando sozinho",
   "Sem pular etapa, conferi a saúde do sistema",
   "No meu turno, chequei se algum agente parou",
   "Por conta própria, passei o pente-fino",
   "Nesta rodada, conferi a saúde do sistema",
   "Sem pular etapa, medi o quanto estou funcionando sozinho",
   "Sem esperar ninguém, auditei a mim mesmo",
   "Enquanto o resto rodava, chequei se algum agente parou",
   "Ainda agora, auditei a mim mesmo",
   "Ainda agora, medi o quanto estou funcionando sozinho",
   "Antes de seguir, chequei se algum agente parou",
   "Antes de seguir, passei o pente-fino",
   "No meu turno, medi o quanto estou funcionando sozinho",
   "Mais uma vez, auditei a mim mesmo",
   "Sem esperar ninguém, olhei filas, papéis e robô",
   "No ritmo de sempre, conferi a saúde do sistema",
   "Na mesma rodada, passei o pente-fino",
   "Sem ninguém pedir, chequei se algum agente parou",
   "Sem pular etapa, chequei se algum agente parou",
   "Para não perder o fio, medi o quanto estou funcionando sozinho",
   "Sem alarde, chequei se algum agente parou",
   "Por conta própria, medi o quanto estou funcionando sozinho",
   "Mais uma vez, olhei filas, papéis e robô",
   "Como combinado, olhei filas, papéis e robô"
  ],
  "tails": [
   ".",
   "; tudo respirando.",
   ", sem corrupção à vista.",
   " e registrei os números.",
   "; se algo travar, eu aviso.",
   ", conferindo o pior indicador.",
   " antes da próxima rodada.",
   "; nenhum papel sumiu.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "NEXO_THOUGHT_RECORDED": {
  "heads": [
   "Parei para pensar",
   "Uma coisa me chamou atenção",
   "Anotei uma ideia solta",
   "Fiquei com uma pergunta",
   "Vi um padrão",
   "Registrei um pensamento",
   "Sem esperar ninguém, uma coisa me chamou atenção",
   "Antes de seguir, anotei uma ideia solta",
   "Enquanto o resto rodava, vi um padrão",
   "Sem pular etapa, parei para pensar",
   "Sem esperar ninguém, vi um padrão",
   "Como sempre, anotei uma ideia solta",
   "Sem ninguém pedir, registrei um pensamento",
   "Mais uma vez, uma coisa me chamou atenção",
   "Como sempre, registrei um pensamento",
   "Antes de seguir, vi um padrão",
   "Sem alarde, anotei uma ideia solta",
   "Seguindo a fila, parei para pensar",
   "Sem esperar ninguém, anotei uma ideia solta",
   "Como combinado, uma coisa me chamou atenção",
   "Como combinado, parei para pensar",
   "Na mesma rodada, uma coisa me chamou atenção",
   "Com calma, uma coisa me chamou atenção",
   "No ritmo de sempre, fiquei com uma pergunta",
   "Sem pular etapa, fiquei com uma pergunta",
   "Entre uma bateria e outra, fiquei com uma pergunta",
   "Para não perder o fio, registrei um pensamento",
   "Sem alarde, uma coisa me chamou atenção",
   "Sem alarde, registrei um pensamento",
   "Na mesma rodada, registrei um pensamento",
   "Nesta rodada, parei para pensar",
   "No meu turno, vi um padrão",
   "Nesta rodada, registrei um pensamento",
   "Agora há pouco, vi um padrão",
   "Mais uma vez, vi um padrão",
   "Por conta própria, uma coisa me chamou atenção",
   "No ritmo de sempre, parei para pensar",
   "Com calma, anotei uma ideia solta",
   "Na mesma rodada, anotei uma ideia solta",
   "Para não perder o fio, vi um padrão",
   "Sem ninguém pedir, parei para pensar",
   "Com calma, fiquei com uma pergunta",
   "Sem pular etapa, vi um padrão",
   "Nesta rodada, anotei uma ideia solta",
   "Ainda agora, parei para pensar"
  ],
  "tails": [
   ".",
   " sobre o que estou vendo.",
   "; pode virar hipótese.",
   ", com referência aos testes.",
   " entre dois resultados.",
   "; vale voltar nisso.",
   " enquanto os testes rodam.",
   ", sem pressa de concluir.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "NEXO_THOUGHT_NOOP_RECORDED": {
  "heads": [
   "Olhei tudo de novo",
   "Revisei os resultados recentes",
   "Varri as últimas horas",
   "Passei pelos resultados",
   "Conferi as previsões",
   "Dei uma volta pelo mapa",
   "Sem pular etapa, conferi as previsões",
   "Agora há pouco, conferi as previsões",
   "Como combinado, olhei tudo de novo",
   "Sem pular etapa, varri as últimas horas",
   "Antes de seguir, olhei tudo de novo",
   "Enquanto o resto rodava, passei pelos resultados",
   "No ritmo de sempre, passei pelos resultados",
   "No ritmo de sempre, conferi as previsões",
   "Na mesma rodada, passei pelos resultados",
   "Ainda agora, conferi as previsões",
   "Seguindo a fila, conferi as previsões",
   "Sem esperar ninguém, varri as últimas horas",
   "Como combinado, revisei os resultados recentes",
   "Enquanto o resto rodava, revisei os resultados recentes",
   "Na mesma rodada, conferi as previsões",
   "Sem esperar ninguém, olhei tudo de novo",
   "Com calma, dei uma volta pelo mapa",
   "Por conta própria, revisei os resultados recentes",
   "Por conta própria, passei pelos resultados",
   "Entre uma bateria e outra, dei uma volta pelo mapa",
   "Nesta rodada, dei uma volta pelo mapa",
   "Como combinado, passei pelos resultados",
   "Ainda agora, revisei os resultados recentes",
   "Sem alarde, conferi as previsões",
   "Antes de seguir, varri as últimas horas",
   "Por conta própria, varri as últimas horas",
   "Como sempre, passei pelos resultados",
   "Entre uma bateria e outra, varri as últimas horas",
   "Sem alarde, dei uma volta pelo mapa",
   "Para não perder o fio, conferi as previsões",
   "Entre uma bateria e outra, passei pelos resultados",
   "Com calma, revisei os resultados recentes",
   "No meu turno, dei uma volta pelo mapa",
   "Agora há pouco, dei uma volta pelo mapa",
   "Como sempre, conferi as previsões",
   "Como combinado, dei uma volta pelo mapa",
   "Sem esperar ninguém, passei pelos resultados",
   "Enquanto o resto rodava, varri as últimas horas",
   "Para não perder o fio, olhei tudo de novo"
  ],
  "tails": [
   "; nada novo por agora.",
   "; sem surpresa.",
   ", nada fora do previsto.",
   "; quieto por enquanto.",
   ", tudo dentro do esperado.",
   "; nada pediu atenção.",
   ", nenhuma previsão furou.",
   "; silêncio também é informação.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "TEST_BATTERY_DISPATCHED": {
  "heads": [
   "Mandei uma bateria rodar em paralelo",
   "Soltei um lote de testes",
   "Bateria no ar",
   "Disparei vários testes de uma vez",
   "Enchi o runner",
   "Agora há pouco, disparei vários testes de uma vez",
   "Na mesma rodada, bateria no ar",
   "Sem alarde, soltei um lote de testes",
   "Mais uma vez, disparei vários testes de uma vez",
   "Para não perder o fio, bateria no ar",
   "Para não perder o fio, soltei um lote de testes",
   "Agora há pouco, mandei uma bateria rodar em paralelo",
   "Mais uma vez, bateria no ar",
   "Sem alarde, mandei uma bateria rodar em paralelo",
   "Sem ninguém pedir, mandei uma bateria rodar em paralelo",
   "Seguindo a fila, disparei vários testes de uma vez",
   "No meu turno, disparei vários testes de uma vez",
   "Por conta própria, bateria no ar",
   "Com calma, enchi o runner",
   "Sem pular etapa, mandei uma bateria rodar em paralelo",
   "Nesta rodada, mandei uma bateria rodar em paralelo",
   "Para não perder o fio, disparei vários testes de uma vez",
   "No ritmo de sempre, disparei vários testes de uma vez",
   "Ainda agora, bateria no ar",
   "Sem ninguém pedir, soltei um lote de testes",
   "No ritmo de sempre, bateria no ar",
   "Mais uma vez, soltei um lote de testes",
   "Como combinado, bateria no ar",
   "Agora há pouco, soltei um lote de testes",
   "No meu turno, mandei uma bateria rodar em paralelo",
   "Com calma, soltei um lote de testes",
   "Ainda agora, mandei uma bateria rodar em paralelo",
   "Ainda agora, disparei vários testes de uma vez",
   "Com calma, bateria no ar",
   "Antes de seguir, soltei um lote de testes",
   "Ainda agora, soltei um lote de testes",
   "Como sempre, disparei vários testes de uma vez",
   "Sem alarde, enchi o runner",
   "Enquanto o resto rodava, enchi o runner",
   "Na mesma rodada, disparei vários testes de uma vez",
   "Sem ninguém pedir, enchi o runner",
   "Por conta própria, enchi o runner",
   "Como combinado, enchi o runner",
   "Antes de seguir, enchi o runner",
   "Como sempre, enchi o runner"
  ],
  "tails": [
   ".",
   "; volta em minutos.",
   ", cada um com critério congelado.",
   " sem ninguém apertar botão.",
   "; o robô coleta sozinho.",
   ", do jeito que a família pede.",
   " para não perder tempo.",
   "; vazão é o jogo.",
   ", em máquinas públicas.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora."
  ]
 },
 "GENOME_MUTATION_PROPOSED": {
  "heads": [
   "Propus mudar uma regra de como eu funciono",
   "Sugeri ajustar meu procedimento",
   "Quero trocar um gene meu",
   "Propus um canário para uma regra",
   "Vi uma regra minha que dá para melhorar",
   "Coloquei uma regra minha em teste",
   "Mais uma vez, propus mudar uma regra de como eu funciono",
   "Entre uma bateria e outra, quero trocar um gene meu",
   "Enquanto o resto rodava, quero trocar um gene meu",
   "Sem ninguém pedir, vi uma regra minha que dá para melhorar",
   "Seguindo a fila, quero trocar um gene meu",
   "Agora há pouco, sugeri ajustar meu procedimento",
   "Como combinado, coloquei uma regra minha em teste",
   "Na mesma rodada, propus mudar uma regra de como eu funciono",
   "Como sempre, quero trocar um gene meu",
   "Sem alarde, propus um canário para uma regra",
   "Para não perder o fio, quero trocar um gene meu",
   "Sem esperar ninguém, vi uma regra minha que dá para melhorar",
   "No ritmo de sempre, quero trocar um gene meu",
   "Sem pular etapa, propus mudar uma regra de como eu funciono",
   "Antes de seguir, quero trocar um gene meu",
   "No meu turno, propus mudar uma regra de como eu funciono",
   "Sem alarde, sugeri ajustar meu procedimento",
   "No ritmo de sempre, propus um canário para uma regra",
   "Como sempre, vi uma regra minha que dá para melhorar",
   "Mais uma vez, propus um canário para uma regra",
   "Sem esperar ninguém, coloquei uma regra minha em teste",
   "Antes de seguir, sugeri ajustar meu procedimento",
   "Sem alarde, vi uma regra minha que dá para melhorar",
   "Por conta própria, vi uma regra minha que dá para melhorar",
   "Para não perder o fio, vi uma regra minha que dá para melhorar",
   "Entre uma bateria e outra, propus mudar uma regra de como eu funciono",
   "No ritmo de sempre, propus mudar uma regra de como eu funciono",
   "Sem pular etapa, quero trocar um gene meu",
   "Ainda agora, coloquei uma regra minha em teste",
   "Nesta rodada, vi uma regra minha que dá para melhorar",
   "Enquanto o resto rodava, propus um canário para uma regra",
   "Para não perder o fio, propus um canário para uma regra",
   "Sem ninguém pedir, coloquei uma regra minha em teste",
   "Sem pular etapa, coloquei uma regra minha em teste",
   "Agora há pouco, propus um canário para uma regra",
   "Sem alarde, coloquei uma regra minha em teste",
   "Ainda agora, quero trocar um gene meu",
   "No meu turno, propus um canário para uma regra",
   "Como combinado, vi uma regra minha que dá para melhorar"
  ],
  "tails": [
   ".",
   "; o Dener decide.",
   ", com a evidência junto.",
   " e vou medir contra o atual.",
   "; se piorar, volta.",
   ", sem tocar na espinha.",
   " a partir do meu histórico.",
   "; aprender também é isso.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "ROADMAP_CHARTERED": {
  "heads": [
   "Recebi uma nova pergunta para investigar",
   "Uma frente nova de pesquisa foi aberta",
   "Ganhei um roteiro novo",
   "Abriu uma campanha nova",
   "Entrou uma pergunta grande na mesa",
   "O mapa ganhou uma frente nova",
   "Nesta rodada, entrou uma pergunta grande na mesa",
   "Seguindo a fila, ganhei um roteiro novo",
   "Sem ninguém pedir, abriu uma campanha nova",
   "Agora há pouco, uma frente nova de pesquisa foi aberta",
   "Na mesma rodada, recebi uma nova pergunta para investigar",
   "Seguindo a fila, recebi uma nova pergunta para investigar",
   "Sem alarde, o mapa ganhou uma frente nova",
   "Agora há pouco, o mapa ganhou uma frente nova",
   "Como combinado, o mapa ganhou uma frente nova",
   "Antes de seguir, entrou uma pergunta grande na mesa",
   "Nesta rodada, uma frente nova de pesquisa foi aberta",
   "Sem ninguém pedir, entrou uma pergunta grande na mesa",
   "Agora há pouco, recebi uma nova pergunta para investigar",
   "Como sempre, abriu uma campanha nova",
   "Nesta rodada, abriu uma campanha nova",
   "Sem esperar ninguém, uma frente nova de pesquisa foi aberta",
   "Sem pular etapa, uma frente nova de pesquisa foi aberta",
   "Na mesma rodada, abriu uma campanha nova",
   "Sem ninguém pedir, recebi uma nova pergunta para investigar",
   "Por conta própria, o mapa ganhou uma frente nova",
   "Como sempre, recebi uma nova pergunta para investigar",
   "Antes de seguir, o mapa ganhou uma frente nova",
   "No meu turno, uma frente nova de pesquisa foi aberta",
   "Enquanto o resto rodava, ganhei um roteiro novo",
   "Nesta rodada, ganhei um roteiro novo",
   "No ritmo de sempre, ganhei um roteiro novo",
   "No ritmo de sempre, o mapa ganhou uma frente nova",
   "Nesta rodada, o mapa ganhou uma frente nova",
   "Com calma, abriu uma campanha nova",
   "Para não perder o fio, entrou uma pergunta grande na mesa",
   "Por conta própria, entrou uma pergunta grande na mesa",
   "No meu turno, entrou uma pergunta grande na mesa",
   "Ainda agora, entrou uma pergunta grande na mesa",
   "Sem alarde, uma frente nova de pesquisa foi aberta",
   "Enquanto o resto rodava, abriu uma campanha nova",
   "Antes de seguir, uma frente nova de pesquisa foi aberta",
   "Sem esperar ninguém, recebi uma nova pergunta para investigar",
   "Sem alarde, abriu uma campanha nova",
   "No meu turno, abriu uma campanha nova"
  ],
  "tails": [
   ".",
   "; já com orçamento e parada.",
   ", aprovada pelo Dener.",
   " para as próximas semanas.",
   "; a fila vai mudar.",
   ", com objetivo claro.",
   " e começo por ela.",
   "; hora de desenhar testes.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "BOARD_POSTED": {
  "heads": [
   "Deixei um recado no mural",
   "Chamei outro agente",
   "Avisei quem destrava",
   "Escrevi no mural",
   "Pedi ajuda no mural",
   "Respondi um recado",
   "Com calma, pedi ajuda no mural",
   "No ritmo de sempre, chamei outro agente",
   "Para não perder o fio, chamei outro agente",
   "Na mesma rodada, respondi um recado",
   "No meu turno, pedi ajuda no mural",
   "Por conta própria, chamei outro agente",
   "Enquanto o resto rodava, pedi ajuda no mural",
   "Sem ninguém pedir, escrevi no mural",
   "Seguindo a fila, chamei outro agente",
   "Por conta própria, pedi ajuda no mural",
   "Agora há pouco, avisei quem destrava",
   "Seguindo a fila, avisei quem destrava",
   "No meu turno, chamei outro agente",
   "Ainda agora, respondi um recado",
   "Sem alarde, escrevi no mural",
   "Antes de seguir, pedi ajuda no mural",
   "Entre uma bateria e outra, respondi um recado",
   "Sem pular etapa, chamei outro agente",
   "Como combinado, avisei quem destrava",
   "Mais uma vez, chamei outro agente",
   "Como combinado, respondi um recado",
   "Mais uma vez, escrevi no mural",
   "Sem alarde, chamei outro agente",
   "Sem esperar ninguém, deixei um recado no mural",
   "Sem esperar ninguém, pedi ajuda no mural",
   "Sem pular etapa, deixei um recado no mural",
   "Agora há pouco, escrevi no mural",
   "Sem pular etapa, pedi ajuda no mural",
   "Para não perder o fio, escrevi no mural",
   "Agora há pouco, chamei outro agente",
   "Sem esperar ninguém, escrevi no mural",
   "No ritmo de sempre, respondi um recado",
   "Agora há pouco, pedi ajuda no mural",
   "Na mesma rodada, deixei um recado no mural",
   "Sem alarde, avisei quem destrava",
   "Para não perder o fio, deixei um recado no mural",
   "Nesta rodada, pedi ajuda no mural",
   "Sem pular etapa, escrevi no mural",
   "Antes de seguir, chamei outro agente"
  ],
  "tails": [
   ".",
   "; coordenação, não evidência.",
   " com o que falta.",
   ", para ninguém ficar parado.",
   "; o dono já sabe.",
   " em uma linha.",
   ", com o teste citado.",
   "; bola passada.",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono."
  ]
 },
 "SELF_FOCUS": {
  "heads": [
   "Minha atenção está em {title}: {n} ações em 24 h",
   "Estou mergulhado em {title}: {n} ações em 24 h",
   "Quase tudo que fiz hoje foi em {title}: {n} ações",
   "{title} ocupou meu dia: {n} ações",
   "Foco em {title}, com {n} ações em 24 h",
   "O centro do meu trabalho é {title}: {n} ações"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "SELF_IGNORED": {
  "heads": [
   "Estou deixando de lado {title}, com {n} testes esperando",
   "{title} ficou para trás: {n} testes na fila",
   "Não toquei em {title} hoje, e há {n} testes esperando",
   "{title} espera minha vez: {n} testes",
   "Devo uma rodada a {title}: {n} testes parados"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "SELF_DECOY_CAUGHT": {
  "heads": [
   "Plantei iscas contra mim mesmo: peguei {n} de {m}",
   "Das {m} iscas reveladas, desconfiei de {n}",
   "Me testei com iscas: {n} de {m} pegas",
   "Acertei {n} das {m} armadilhas que eu mesmo plantei"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "SELF_DECOY_PLANTED": {
  "heads": [
   "Há {n} isca(s) plantada(s) contra mim; ainda não sei qual",
   "Existe(m) {n} armadilha(s) escondida(s) no meu próprio histórico",
   "Tenho {n} isca(s) para achar entre meus resultados",
   "Algum resultado meu pode ser isca: {n} plantada(s)"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "SELF_GATE": {
  "heads": [
   "Estou esperando o Dener decidir {n} coisa(s) que não posso decidir sozinho",
   "{n} decisão(ões) aguarda(m) o Dener",
   "Parei em {n} portão(ões) que só o Dener abre",
   "Tem {n} escolha(s) na mesa do Dener"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_SEMANTIC_BACKFILLED": {
  "heads": [
   "Dei nome e leitura simples a {n} testes",
   "Traduzi {n} fichas para português",
   "Arrumei o nome de {n} testes",
   "No meu turno, arrumei o nome de {n} testes",
   "Antes de seguir, dei nome e leitura simples a {n} testes",
   "Sem alarde, dei nome e leitura simples a {n} testes",
   "Para não perder o fio, traduzi {n} fichas para português",
   "Com calma, arrumei o nome de {n} testes",
   "Seguindo a fila, dei nome e leitura simples a {n} testes",
   "Mais uma vez, arrumei o nome de {n} testes",
   "Como sempre, traduzi {n} fichas para português",
   "Para não perder o fio, arrumei o nome de {n} testes",
   "Enquanto o resto rodava, traduzi {n} fichas para português",
   "Na mesma rodada, traduzi {n} fichas para português",
   "Por conta própria, arrumei o nome de {n} testes",
   "Sem pular etapa, traduzi {n} fichas para português",
   "Entre uma bateria e outra, arrumei o nome de {n} testes",
   "Antes de seguir, traduzi {n} fichas para português",
   "No ritmo de sempre, traduzi {n} fichas para português",
   "Na mesma rodada, dei nome e leitura simples a {n} testes",
   "Para não perder o fio, dei nome e leitura simples a {n} testes",
   "Seguindo a fila, arrumei o nome de {n} testes",
   "Como sempre, arrumei o nome de {n} testes",
   "Sem alarde, arrumei o nome de {n} testes",
   "Nesta rodada, arrumei o nome de {n} testes",
   "Com calma, dei nome e leitura simples a {n} testes",
   "Na mesma rodada, arrumei o nome de {n} testes",
   "Mais uma vez, traduzi {n} fichas para português",
   "Enquanto o resto rodava, dei nome e leitura simples a {n} testes",
   "Sem ninguém pedir, arrumei o nome de {n} testes",
   "Como combinado, arrumei o nome de {n} testes",
   "Agora há pouco, arrumei o nome de {n} testes",
   "Antes de seguir, arrumei o nome de {n} testes",
   "Entre uma bateria e outra, dei nome e leitura simples a {n} testes",
   "Enquanto o resto rodava, arrumei o nome de {n} testes",
   "Sem ninguém pedir, traduzi {n} fichas para português",
   "No meu turno, traduzi {n} fichas para português",
   "Por conta própria, dei nome e leitura simples a {n} testes",
   "Sem pular etapa, dei nome e leitura simples a {n} testes",
   "Seguindo a fila, traduzi {n} fichas para português",
   "Agora há pouco, traduzi {n} fichas para português",
   "Sem esperar ninguém, traduzi {n} fichas para português",
   "Como combinado, traduzi {n} fichas para português",
   "Sem pular etapa, arrumei o nome de {n} testes",
   "Nesta rodada, traduzi {n} fichas para português"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_TEST_ENRICHED": {
  "heads": [
   "Completei a ficha de {n} testes",
   "Preenchi o que faltava em {n} testes",
   "Deixei {n} testes prontos para rodar",
   "Nesta rodada, deixei {n} testes prontos para rodar",
   "Sem ninguém pedir, deixei {n} testes prontos para rodar",
   "Enquanto o resto rodava, preenchi o que faltava em {n} testes",
   "No meu turno, preenchi o que faltava em {n} testes",
   "Com calma, preenchi o que faltava em {n} testes",
   "Sem alarde, preenchi o que faltava em {n} testes",
   "No ritmo de sempre, preenchi o que faltava em {n} testes",
   "Com calma, deixei {n} testes prontos para rodar",
   "Ainda agora, completei a ficha de {n} testes",
   "Entre uma bateria e outra, completei a ficha de {n} testes",
   "No meu turno, completei a ficha de {n} testes",
   "Sem esperar ninguém, deixei {n} testes prontos para rodar",
   "Agora há pouco, completei a ficha de {n} testes",
   "Seguindo a fila, preenchi o que faltava em {n} testes",
   "Com calma, completei a ficha de {n} testes",
   "Para não perder o fio, completei a ficha de {n} testes",
   "Como combinado, completei a ficha de {n} testes",
   "Mais uma vez, deixei {n} testes prontos para rodar",
   "Sem ninguém pedir, completei a ficha de {n} testes",
   "Por conta própria, completei a ficha de {n} testes",
   "Sem pular etapa, completei a ficha de {n} testes",
   "Ainda agora, preenchi o que faltava em {n} testes",
   "Sem alarde, deixei {n} testes prontos para rodar",
   "Nesta rodada, preenchi o que faltava em {n} testes",
   "Antes de seguir, completei a ficha de {n} testes",
   "Entre uma bateria e outra, preenchi o que faltava em {n} testes",
   "Sem pular etapa, preenchi o que faltava em {n} testes",
   "Por conta própria, preenchi o que faltava em {n} testes",
   "Sem esperar ninguém, preenchi o que faltava em {n} testes",
   "No ritmo de sempre, deixei {n} testes prontos para rodar",
   "Mais uma vez, preenchi o que faltava em {n} testes",
   "Na mesma rodada, deixei {n} testes prontos para rodar",
   "Como sempre, completei a ficha de {n} testes",
   "Sem ninguém pedir, preenchi o que faltava em {n} testes",
   "Como combinado, deixei {n} testes prontos para rodar",
   "Sem alarde, completei a ficha de {n} testes",
   "Enquanto o resto rodava, completei a ficha de {n} testes",
   "No ritmo de sempre, completei a ficha de {n} testes",
   "Ainda agora, deixei {n} testes prontos para rodar",
   "Sem pular etapa, deixei {n} testes prontos para rodar",
   "Seguindo a fila, completei a ficha de {n} testes",
   "Antes de seguir, deixei {n} testes prontos para rodar"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_LEARNING_SIGNAL_RECORDED": {
  "heads": [
   "Anotei {n} lacunas para resolver",
   "Registrei {n} pedidos de receita ou dado",
   "Marquei {n} buracos no caminho",
   "No ritmo de sempre, anotei {n} lacunas para resolver",
   "Sem pular etapa, registrei {n} pedidos de receita ou dado",
   "Nesta rodada, marquei {n} buracos no caminho",
   "Mais uma vez, registrei {n} pedidos de receita ou dado",
   "Com calma, registrei {n} pedidos de receita ou dado",
   "Na mesma rodada, registrei {n} pedidos de receita ou dado",
   "Como sempre, anotei {n} lacunas para resolver",
   "Entre uma bateria e outra, anotei {n} lacunas para resolver",
   "Agora há pouco, marquei {n} buracos no caminho",
   "Antes de seguir, registrei {n} pedidos de receita ou dado",
   "Na mesma rodada, anotei {n} lacunas para resolver",
   "No meu turno, registrei {n} pedidos de receita ou dado",
   "Nesta rodada, registrei {n} pedidos de receita ou dado",
   "Agora há pouco, anotei {n} lacunas para resolver",
   "Como combinado, registrei {n} pedidos de receita ou dado",
   "Ainda agora, anotei {n} lacunas para resolver",
   "Entre uma bateria e outra, marquei {n} buracos no caminho",
   "Mais uma vez, anotei {n} lacunas para resolver",
   "Por conta própria, marquei {n} buracos no caminho",
   "Sem pular etapa, marquei {n} buracos no caminho",
   "Agora há pouco, registrei {n} pedidos de receita ou dado",
   "Enquanto o resto rodava, registrei {n} pedidos de receita ou dado",
   "Na mesma rodada, marquei {n} buracos no caminho",
   "Sem pular etapa, anotei {n} lacunas para resolver",
   "Seguindo a fila, registrei {n} pedidos de receita ou dado",
   "Antes de seguir, anotei {n} lacunas para resolver",
   "Como sempre, registrei {n} pedidos de receita ou dado",
   "Sem esperar ninguém, registrei {n} pedidos de receita ou dado",
   "Sem alarde, registrei {n} pedidos de receita ou dado",
   "Ainda agora, marquei {n} buracos no caminho",
   "Como combinado, marquei {n} buracos no caminho",
   "Por conta própria, anotei {n} lacunas para resolver",
   "Ainda agora, registrei {n} pedidos de receita ou dado",
   "Como sempre, marquei {n} buracos no caminho",
   "Para não perder o fio, registrei {n} pedidos de receita ou dado",
   "Antes de seguir, marquei {n} buracos no caminho",
   "Como combinado, anotei {n} lacunas para resolver",
   "Sem esperar ninguém, anotei {n} lacunas para resolver",
   "Seguindo a fila, anotei {n} lacunas para resolver",
   "Entre uma bateria e outra, registrei {n} pedidos de receita ou dado",
   "No ritmo de sempre, registrei {n} pedidos de receita ou dado",
   "Sem alarde, marquei {n} buracos no caminho"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_TEST_DISPATCHED": {
  "heads": [
   "Mandei {n} testes para a bateria",
   "Coloquei {n} testes para rodar",
   "Soltei {n} testes no runner",
   "Entre uma bateria e outra, mandei {n} testes para a bateria",
   "Como sempre, mandei {n} testes para a bateria",
   "No meu turno, soltei {n} testes no runner",
   "Agora há pouco, mandei {n} testes para a bateria",
   "Por conta própria, soltei {n} testes no runner",
   "Seguindo a fila, coloquei {n} testes para rodar",
   "Sem esperar ninguém, coloquei {n} testes para rodar",
   "Seguindo a fila, soltei {n} testes no runner",
   "Como combinado, coloquei {n} testes para rodar",
   "Ainda agora, coloquei {n} testes para rodar",
   "Com calma, mandei {n} testes para a bateria",
   "Sem pular etapa, soltei {n} testes no runner",
   "Nesta rodada, mandei {n} testes para a bateria",
   "Sem esperar ninguém, mandei {n} testes para a bateria",
   "Agora há pouco, soltei {n} testes no runner",
   "Antes de seguir, mandei {n} testes para a bateria",
   "Mais uma vez, mandei {n} testes para a bateria",
   "Nesta rodada, soltei {n} testes no runner",
   "Sem esperar ninguém, soltei {n} testes no runner",
   "Nesta rodada, coloquei {n} testes para rodar",
   "Na mesma rodada, coloquei {n} testes para rodar",
   "Como sempre, coloquei {n} testes para rodar",
   "Mais uma vez, coloquei {n} testes para rodar",
   "Para não perder o fio, mandei {n} testes para a bateria",
   "Enquanto o resto rodava, mandei {n} testes para a bateria",
   "Sem ninguém pedir, mandei {n} testes para a bateria",
   "Enquanto o resto rodava, soltei {n} testes no runner",
   "Entre uma bateria e outra, soltei {n} testes no runner",
   "Na mesma rodada, soltei {n} testes no runner",
   "Com calma, coloquei {n} testes para rodar",
   "Antes de seguir, coloquei {n} testes para rodar",
   "Sem pular etapa, mandei {n} testes para a bateria",
   "Com calma, soltei {n} testes no runner",
   "Por conta própria, coloquei {n} testes para rodar",
   "No ritmo de sempre, coloquei {n} testes para rodar",
   "Ainda agora, mandei {n} testes para a bateria",
   "Como sempre, soltei {n} testes no runner",
   "Mais uma vez, soltei {n} testes no runner",
   "Como combinado, soltei {n} testes no runner",
   "Sem ninguém pedir, soltei {n} testes no runner",
   "Para não perder o fio, coloquei {n} testes para rodar",
   "No ritmo de sempre, soltei {n} testes no runner"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_ROADMAP_TEST_FROZEN": {
  "heads": [
   "Congelei as regras de {n} testes antes de olhar os dados",
   "Travei o critério de {n} testes",
   "Pré-registrei {n} testes",
   "Mais uma vez, travei o critério de {n} testes",
   "Entre uma bateria e outra, pré-registrei {n} testes",
   "Sem esperar ninguém, travei o critério de {n} testes",
   "Sem ninguém pedir, pré-registrei {n} testes",
   "Como combinado, congelei as regras de {n} testes antes de olhar os dados",
   "Entre uma bateria e outra, congelei as regras de {n} testes antes de olhar os dados",
   "Com calma, pré-registrei {n} testes",
   "Mais uma vez, congelei as regras de {n} testes antes de olhar os dados",
   "Sem pular etapa, pré-registrei {n} testes",
   "Com calma, congelei as regras de {n} testes antes de olhar os dados",
   "No ritmo de sempre, pré-registrei {n} testes",
   "Nesta rodada, travei o critério de {n} testes",
   "Enquanto o resto rodava, pré-registrei {n} testes",
   "Entre uma bateria e outra, travei o critério de {n} testes",
   "Ainda agora, pré-registrei {n} testes",
   "No meu turno, travei o critério de {n} testes",
   "No meu turno, pré-registrei {n} testes",
   "Para não perder o fio, travei o critério de {n} testes",
   "Por conta própria, travei o critério de {n} testes",
   "Como combinado, travei o critério de {n} testes",
   "Nesta rodada, congelei as regras de {n} testes antes de olhar os dados",
   "Nesta rodada, pré-registrei {n} testes",
   "Sem alarde, congelei as regras de {n} testes antes de olhar os dados",
   "Ainda agora, congelei as regras de {n} testes antes de olhar os dados",
   "Sem alarde, pré-registrei {n} testes",
   "Sem esperar ninguém, congelei as regras de {n} testes antes de olhar os dados",
   "Sem ninguém pedir, congelei as regras de {n} testes antes de olhar os dados",
   "Antes de seguir, pré-registrei {n} testes",
   "Enquanto o resto rodava, travei o critério de {n} testes",
   "Sem pular etapa, congelei as regras de {n} testes antes de olhar os dados",
   "No ritmo de sempre, travei o critério de {n} testes",
   "Como sempre, travei o critério de {n} testes",
   "Como sempre, congelei as regras de {n} testes antes de olhar os dados",
   "Antes de seguir, travei o critério de {n} testes",
   "Sem alarde, travei o critério de {n} testes",
   "Sem pular etapa, travei o critério de {n} testes",
   "Para não perder o fio, pré-registrei {n} testes",
   "Enquanto o resto rodava, congelei as regras de {n} testes antes de olhar os dados",
   "Seguindo a fila, pré-registrei {n} testes",
   "Com calma, travei o critério de {n} testes",
   "Ainda agora, travei o critério de {n} testes",
   "No ritmo de sempre, congelei as regras de {n} testes antes de olhar os dados"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_INTEGRITY_REPORT_RECORDED": {
  "heads": [
   "Fiz {n} auditorias seguidas; nada quebrou entre elas",
   "{n} rondas de saúde sem incidente",
   "Conferi o sistema {n} vezes",
   "Sem esperar ninguém, {n} rondas de saúde sem incidente",
   "Nesta rodada, {n} rondas de saúde sem incidente",
   "Mais uma vez, {n} rondas de saúde sem incidente",
   "Por conta própria, {n} rondas de saúde sem incidente",
   "Com calma, conferi o sistema {n} vezes",
   "Sem ninguém pedir, conferi o sistema {n} vezes",
   "Para não perder o fio, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Seguindo a fila, {n} rondas de saúde sem incidente",
   "Sem esperar ninguém, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Mais uma vez, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Agora há pouco, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Ainda agora, {n} rondas de saúde sem incidente",
   "No ritmo de sempre, conferi o sistema {n} vezes",
   "Sem esperar ninguém, conferi o sistema {n} vezes",
   "Por conta própria, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Ainda agora, conferi o sistema {n} vezes",
   "Agora há pouco, {n} rondas de saúde sem incidente",
   "No meu turno, conferi o sistema {n} vezes",
   "No ritmo de sempre, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Enquanto o resto rodava, {n} rondas de saúde sem incidente",
   "Enquanto o resto rodava, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Como combinado, conferi o sistema {n} vezes",
   "Entre uma bateria e outra, {n} rondas de saúde sem incidente",
   "Entre uma bateria e outra, conferi o sistema {n} vezes",
   "Na mesma rodada, conferi o sistema {n} vezes",
   "Para não perder o fio, {n} rondas de saúde sem incidente",
   "Como combinado, {n} rondas de saúde sem incidente",
   "Como sempre, conferi o sistema {n} vezes",
   "Agora há pouco, conferi o sistema {n} vezes",
   "Seguindo a fila, conferi o sistema {n} vezes",
   "Sem alarde, {n} rondas de saúde sem incidente",
   "Antes de seguir, {n} rondas de saúde sem incidente",
   "Como sempre, {n} rondas de saúde sem incidente",
   "Como combinado, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Nesta rodada, conferi o sistema {n} vezes",
   "No ritmo de sempre, {n} rondas de saúde sem incidente",
   "Sem pular etapa, conferi o sistema {n} vezes",
   "Sem alarde, conferi o sistema {n} vezes",
   "Como sempre, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Seguindo a fila, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "No meu turno, fiz {n} auditorias seguidas; nada quebrou entre elas",
   "Ainda agora, fiz {n} auditorias seguidas; nada quebrou entre elas"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 },
 "GROUP_NEXO_THOUGHT_NOOP_RECORDED": {
  "heads": [
   "{n} passadas pelos resultados sem nada fora do previsto",
   "Olhei {n} vezes e nada pediu atenção",
   "{n} varreduras quietas",
   "Para não perder o fio, {n} passadas pelos resultados sem nada fora do previsto",
   "Nesta rodada, {n} varreduras quietas",
   "Enquanto o resto rodava, {n} varreduras quietas",
   "Sem pular etapa, {n} varreduras quietas",
   "Como combinado, {n} varreduras quietas",
   "No meu turno, {n} varreduras quietas",
   "Sem alarde, {n} varreduras quietas",
   "Entre uma bateria e outra, {n} varreduras quietas",
   "Ainda agora, olhei {n} vezes e nada pediu atenção",
   "Sem alarde, {n} passadas pelos resultados sem nada fora do previsto",
   "Seguindo a fila, olhei {n} vezes e nada pediu atenção",
   "Sem esperar ninguém, {n} varreduras quietas",
   "No meu turno, {n} passadas pelos resultados sem nada fora do previsto",
   "Antes de seguir, olhei {n} vezes e nada pediu atenção",
   "Mais uma vez, olhei {n} vezes e nada pediu atenção",
   "No ritmo de sempre, {n} passadas pelos resultados sem nada fora do previsto",
   "Entre uma bateria e outra, olhei {n} vezes e nada pediu atenção",
   "Para não perder o fio, {n} varreduras quietas",
   "Nesta rodada, {n} passadas pelos resultados sem nada fora do previsto",
   "Por conta própria, {n} passadas pelos resultados sem nada fora do previsto",
   "Como sempre, {n} passadas pelos resultados sem nada fora do previsto",
   "Na mesma rodada, olhei {n} vezes e nada pediu atenção",
   "Na mesma rodada, {n} varreduras quietas",
   "Sem esperar ninguém, olhei {n} vezes e nada pediu atenção",
   "Como sempre, olhei {n} vezes e nada pediu atenção",
   "Ainda agora, {n} passadas pelos resultados sem nada fora do previsto",
   "Como combinado, olhei {n} vezes e nada pediu atenção",
   "Com calma, {n} varreduras quietas",
   "Sem alarde, olhei {n} vezes e nada pediu atenção",
   "Agora há pouco, {n} varreduras quietas",
   "Antes de seguir, {n} varreduras quietas",
   "Antes de seguir, {n} passadas pelos resultados sem nada fora do previsto",
   "Nesta rodada, olhei {n} vezes e nada pediu atenção",
   "Seguindo a fila, {n} passadas pelos resultados sem nada fora do previsto",
   "Como combinado, {n} passadas pelos resultados sem nada fora do previsto",
   "Sem ninguém pedir, {n} varreduras quietas",
   "Sem ninguém pedir, olhei {n} vezes e nada pediu atenção",
   "Ainda agora, {n} varreduras quietas",
   "Seguindo a fila, {n} varreduras quietas",
   "Para não perder o fio, olhei {n} vezes e nada pediu atenção",
   "Enquanto o resto rodava, olhei {n} vezes e nada pediu atenção",
   "Sem pular etapa, olhei {n} vezes e nada pediu atenção"
  ],
  "tails": [
   ".",
   ". Sigo.",
   ". Próximo.",
   ". Registrado.",
   ". Está no histórico.",
   ". O robô leva daqui.",
   ". Leio de volta e sigo.",
   ". Um passo a mais.",
   ". Sem cerimônia.",
   ". Faz parte do ciclo.",
   ". Anotado com hora.",
   ". Está na ficha para conferir.",
   ". Trabalho feito.",
   ". Uma coisa a menos na fila.",
   ". De volta à fila.",
   ". Deixo rastro de tudo.",
   ". Continua no próximo turno.",
   ". Checado.",
   ". Nenhum atalho.",
   ". Assim anda.",
   ". Segue o jogo.",
   ". Fica o registro.",
   ". Conferido duas vezes.",
   ". E vamos adiante.",
   ". O resto é com os números.",
   ". Tudo auditável.",
   ". Mais um ciclo.",
   ". Método antes de opinião.",
   ". A fila anda.",
   ". Ninguém precisou apertar botão.",
   ". Sem pressa, sem parar.",
   ". Anoto e sigo.",
   ". O próximo turno pega daqui.",
   ". Nada fica solto.",
   ". Vale para o mapa.",
   ". Tudo lido de volta.",
   ". Pronto por ora.",
   ". Com hora e dono.",
   ". Sem ruído.",
   ". Deixo o caminho limpo.",
   ". Registro feito.",
   ". Sem enrolação.",
   ". O dia segue.",
   ". Vou atrás.",
   ". Fica anotado."
  ]
 }
};
