// Gerado por nexo-one/scripts/gen_narration.py (NEXO): até 45 falas por evento, sorteadas a cada linha.
export const NARRATION: Record<string, string[]> = {
 "SEMANTIC_BACKFILLED": [
  "Dei nome e leitura simples a %q; ninguém precisa decifrar código.",
  "Dei um nome humano a %q, sem jargão desnecessário.",
  "Traduzi para português %q, do jeito que o site mostra.",
  "Deixei %q legível antes que virasse sopa de IDs.",
  "Traduzi para português %q; ninguém precisa decifrar código.",
  "Dei nome e leitura simples a %q; clareza também é dado.",
  "Arrumei a ficha de %q para qualquer pessoa entender.",
  "Deixei %q legível, do jeito que o site mostra.",
  "Reescrevi a pergunta de %q, agora dá para ler sem sigla.",
  "Arrumei a ficha de %q, do jeito que o site mostra.",
  "Reescrevi a pergunta de %q, sem jargão desnecessário.",
  "Deixei %q legível; clareza também é dado.",
  "Dei um nome humano a %q, agora dá para ler sem sigla.",
  "Dei nome e leitura simples a %q, agora dá para ler sem sigla.",
  "Dei nome e leitura simples a %q, sem jargão desnecessário.",
  "Traduzi para português %q, agora dá para ler sem sigla.",
  "Traduzi para português %q.",
  "Reescrevi a pergunta de %q para qualquer pessoa entender.",
  "Deixei %q legível, sem jargão desnecessário.",
  "Traduzi para português %q antes que virasse sopa de IDs.",
  "Deixei %q legível.",
  "Dei nome e leitura simples a %q antes que virasse sopa de IDs.",
  "Dei nome e leitura simples a %q para qualquer pessoa entender.",
  "Arrumei a ficha de %q; clareza também é dado.",
  "Dei um nome humano a %q, do jeito que o site mostra.",
  "Arrumei a ficha de %q antes que virasse sopa de IDs.",
  "Dei um nome humano a %q antes que virasse sopa de IDs.",
  "Arrumei a ficha de %q.",
  "Deixei %q legível; ninguém precisa decifrar código.",
  "Traduzi para português %q; clareza também é dado.",
  "Reescrevi a pergunta de %q, do jeito que o site mostra.",
  "Deixei %q legível para qualquer pessoa entender.",
  "Dei um nome humano a %q; ninguém precisa decifrar código.",
  "Arrumei a ficha de %q; ninguém precisa decifrar código.",
  "Dei nome e leitura simples a %q.",
  "Dei um nome humano a %q.",
  "Dei nome e leitura simples a %q, do jeito que o site mostra.",
  "Reescrevi a pergunta de %q; clareza também é dado.",
  "Arrumei a ficha de %q, sem jargão desnecessário.",
  "Dei um nome humano a %q; clareza também é dado.",
  "Traduzi para português %q, sem jargão desnecessário.",
  "Reescrevi a pergunta de %q; ninguém precisa decifrar código.",
  "Traduzi para português %q para qualquer pessoa entender.",
  "Reescrevi a pergunta de %q antes que virasse sopa de IDs.",
  "Deixei %q legível, agora dá para ler sem sigla."
 ],
 "TEST_ENRICHED": [
  "Preenchi o que faltava em %q; papelada resolvida na hora.",
  "Revisei o contrato de %q, do jeito que o robô aceita.",
  "Fechei as lacunas de %q sem esperar ninguém.",
  "Fechei as lacunas de %q; agora ele pode ir para a bateria.",
  "Preenchi o que faltava em %q; agora ele pode ir para a bateria.",
  "Completei a ficha de %q e segui para o próximo.",
  "Deixei %q pronto para rodar, do jeito que o robô aceita.",
  "Completei a ficha de %q; faltava pouco.",
  "Juntei método e critério em %q.",
  "Deixei %q pronto para rodar.",
  "Revisei o contrato de %q.",
  "Preenchi o que faltava em %q, do jeito que o robô aceita.",
  "Preenchi o que faltava em %q, com dado e critério no lugar.",
  "Deixei %q pronto para rodar; papelada resolvida na hora.",
  "Deixei %q pronto para rodar e segui para o próximo.",
  "Preenchi o que faltava em %q.",
  "Juntei método e critério em %q, do jeito que o robô aceita.",
  "Juntei método e critério em %q; agora ele pode ir para a bateria.",
  "Revisei o contrato de %q; agora ele pode ir para a bateria.",
  "Preenchi o que faltava em %q; faltava pouco.",
  "Fechei as lacunas de %q; papelada resolvida na hora.",
  "Completei a ficha de %q; papelada resolvida na hora.",
  "Juntei método e critério em %q sem esperar ninguém.",
  "Deixei %q pronto para rodar, com dado e critério no lugar.",
  "Fechei as lacunas de %q, com dado e critério no lugar.",
  "Fechei as lacunas de %q; faltava pouco.",
  "Completei a ficha de %q sem esperar ninguém.",
  "Juntei método e critério em %q e segui para o próximo.",
  "Completei a ficha de %q, do jeito que o robô aceita.",
  "Completei a ficha de %q.",
  "Revisei o contrato de %q; faltava pouco.",
  "Juntei método e critério em %q; faltava pouco.",
  "Deixei %q pronto para rodar; faltava pouco.",
  "Revisei o contrato de %q e segui para o próximo.",
  "Revisei o contrato de %q; papelada resolvida na hora.",
  "Fechei as lacunas de %q, do jeito que o robô aceita.",
  "Preenchi o que faltava em %q e segui para o próximo.",
  "Juntei método e critério em %q; papelada resolvida na hora.",
  "Deixei %q pronto para rodar; agora ele pode ir para a bateria.",
  "Fechei as lacunas de %q.",
  "Revisei o contrato de %q, com dado e critério no lugar.",
  "Completei a ficha de %q; agora ele pode ir para a bateria.",
  "Fechei as lacunas de %q e segui para o próximo.",
  "Deixei %q pronto para rodar sem esperar ninguém.",
  "Completei a ficha de %q, com dado e critério no lugar."
 ],
 "LEARNING_SIGNAL_RECORDED": [
  "Achei um buraco no caminho; quem pode destravar já sabe.",
  "Achei um buraco no caminho e segui com o que dava para fazer.",
  "Deixei um pedido para o Engenheiro para o dono resolver.",
  "Registrei o que falta com o motivo escrito.",
  "Deixei um pedido para o Engenheiro com o motivo escrito.",
  "Registrei o que falta; vira trabalho na próxima rodada.",
  "Pedi uma ferramenta que ainda não existe com o motivo escrito.",
  "Deixei um pedido para o Engenheiro, sem parar a fila por isso.",
  "Marquei o que está segurando a fila.",
  "Anotei uma lacuna, sem parar a fila por isso.",
  "Achei um buraco no caminho; vira trabalho na próxima rodada.",
  "Deixei um pedido para o Engenheiro: receita ou dado que falta.",
  "Marquei o que está segurando a fila e segui com o que dava para fazer.",
  "Marquei o que está segurando a fila, sem parar a fila por isso.",
  "Pedi uma ferramenta que ainda não existe: receita ou dado que falta.",
  "Marquei o que está segurando a fila para o dono resolver.",
  "Registrei o que falta: receita ou dado que falta.",
  "Anotei uma lacuna.",
  "Anotei uma lacuna para o dono resolver.",
  "Pedi uma ferramenta que ainda não existe e segui com o que dava para fazer.",
  "Pedi uma ferramenta que ainda não existe; vira trabalho na próxima rodada.",
  "Encontrei um teste sem receita, sem parar a fila por isso.",
  "Anotei uma lacuna: receita ou dado que falta.",
  "Encontrei um teste sem receita; vira trabalho na próxima rodada.",
  "Marquei o que está segurando a fila: receita ou dado que falta.",
  "Achei um buraco no caminho: receita ou dado que falta.",
  "Anotei uma lacuna e segui com o que dava para fazer.",
  "Achei um buraco no caminho.",
  "Encontrei um teste sem receita e segui com o que dava para fazer.",
  "Pedi uma ferramenta que ainda não existe, sem parar a fila por isso.",
  "Achei um buraco no caminho, sem parar a fila por isso.",
  "Registrei o que falta.",
  "Pedi uma ferramenta que ainda não existe.",
  "Marquei o que está segurando a fila; vira trabalho na próxima rodada.",
  "Anotei uma lacuna com o motivo escrito.",
  "Achei um buraco no caminho com o motivo escrito.",
  "Deixei um pedido para o Engenheiro; quem pode destravar já sabe.",
  "Pedi uma ferramenta que ainda não existe para o dono resolver.",
  "Encontrei um teste sem receita para o dono resolver.",
  "Encontrei um teste sem receita: receita ou dado que falta.",
  "Anotei uma lacuna; quem pode destravar já sabe.",
  "Registrei o que falta, sem parar a fila por isso.",
  "Encontrei um teste sem receita com o motivo escrito.",
  "Registrei o que falta para o dono resolver.",
  "Deixei um pedido para o Engenheiro; vira trabalho na próxima rodada."
 ],
 "TEST_DISPATCHED": [
  "%q entrou em execução; o robô cuida do resto.",
  "Liguei a máquina em %q; volta em alguns minutos.",
  "Coloquei %q para rodar; volta em alguns minutos.",
  "Despachei %q; volta em alguns minutos.",
  "Despachei %q, critério já congelado.",
  "Mandei para a bateria %q sem ninguém apertar botão.",
  "Soltei %q no runner.",
  "%q saiu da fila; agora é esperar a conta.",
  "%q saiu da fila sem ninguém apertar botão.",
  "%q saiu da fila, junto com o lote.",
  "Despachei %q com dado público e receita fixa.",
  "Soltei %q no runner, critério já congelado.",
  "Soltei %q no runner; o robô cuida do resto.",
  "Liguei a máquina em %q sem ninguém apertar botão.",
  "Liguei a máquina em %q, junto com o lote.",
  "%q saiu da fila.",
  "Mandei para a bateria %q com dado público e receita fixa.",
  "%q entrou em execução, junto com o lote.",
  "Liguei a máquina em %q; o robô cuida do resto.",
  "Soltei %q no runner; agora é esperar a conta.",
  "Liguei a máquina em %q; agora é esperar a conta.",
  "Coloquei %q para rodar, junto com o lote.",
  "Despachei %q; o robô cuida do resto.",
  "Mandei para a bateria %q; o robô cuida do resto.",
  "Mandei para a bateria %q, critério já congelado.",
  "Liguei a máquina em %q.",
  "%q entrou em execução; agora é esperar a conta.",
  "Liguei a máquina em %q com dado público e receita fixa.",
  "Mandei para a bateria %q, junto com o lote.",
  "Coloquei %q para rodar.",
  "%q entrou em execução, critério já congelado.",
  "Soltei %q no runner, junto com o lote.",
  "%q entrou em execução sem ninguém apertar botão.",
  "Mandei para a bateria %q; volta em alguns minutos.",
  "Despachei %q sem ninguém apertar botão.",
  "%q entrou em execução; volta em alguns minutos.",
  "Despachei %q, junto com o lote.",
  "Despachei %q.",
  "Coloquei %q para rodar; o robô cuida do resto.",
  "%q saiu da fila, critério já congelado.",
  "Coloquei %q para rodar com dado público e receita fixa.",
  "Despachei %q; agora é esperar a conta.",
  "Soltei %q no runner sem ninguém apertar botão.",
  "Soltei %q no runner com dado público e receita fixa.",
  "Coloquei %q para rodar sem ninguém apertar botão."
 ],
 "TEST_RESULT_RECORDED": [
  "Chegou o resultado de %q.",
  "Fechei a conta de %q; mais um tijolo no mapa.",
  "A bateria devolveu %q e o site já mostra.",
  "A bateria devolveu %q; mais um tijolo no mapa.",
  "Fechei a conta de %q; o critério decide, não eu.",
  "Chegou o resultado de %q, sem mexer na trave.",
  "A bateria devolveu %q, e ficou registrado.",
  "Chegou o resultado de %q; o critério decide, não eu.",
  "Terminei um teste: %q, sem mexer na trave.",
  "Saiu o veredito de %q e o site já mostra.",
  "%q voltou da bateria, sem mexer na trave.",
  "Fechei a conta de %q.",
  "%q voltou da bateria; próximo passo é atacar.",
  "Chegou o resultado de %q; próximo passo é atacar.",
  "Saiu o veredito de %q, sem mexer na trave.",
  "Chegou o resultado de %q, e ficou registrado.",
  "A bateria devolveu %q com os números na ficha.",
  "A bateria devolveu %q; próximo passo é atacar.",
  "Fechei a conta de %q, sem mexer na trave.",
  "%q voltou da bateria; mais um tijolo no mapa.",
  "Saiu o veredito de %q, e ficou registrado.",
  "%q voltou da bateria.",
  "%q voltou da bateria e o site já mostra.",
  "Saiu o veredito de %q.",
  "%q voltou da bateria com os números na ficha.",
  "%q voltou da bateria, e ficou registrado.",
  "A bateria devolveu %q.",
  "Chegou o resultado de %q e o site já mostra.",
  "Terminei um teste: %q e o site já mostra.",
  "Fechei a conta de %q; próximo passo é atacar.",
  "Saiu o veredito de %q; mais um tijolo no mapa.",
  "Terminei um teste: %q com os números na ficha.",
  "Chegou o resultado de %q; mais um tijolo no mapa.",
  "Saiu o veredito de %q; próximo passo é atacar.",
  "Fechei a conta de %q, e ficou registrado.",
  "Saiu o veredito de %q com os números na ficha.",
  "A bateria devolveu %q, sem mexer na trave.",
  "Saiu o veredito de %q; o critério decide, não eu.",
  "A bateria devolveu %q; o critério decide, não eu.",
  "Chegou o resultado de %q com os números na ficha.",
  "%q voltou da bateria; o critério decide, não eu.",
  "Terminei um teste: %q; próximo passo é atacar.",
  "Terminei um teste: %q.",
  "Fechei a conta de %q com os números na ficha.",
  "Terminei um teste: %q; mais um tijolo no mapa."
 ],
 "ROADMAP_TEST_FROZEN": [
  "Congelei as regras antes de olhar os dados: %q; o dado decide sozinho.",
  "Escrevi o que derrubaria %q com a previsão anotada.",
  "Tranquei a trave de %q.",
  "Tranquei a trave de %q, para não me enganar depois.",
  "Pré-registrei %q, do jeito que a ciência pede.",
  "Pré-registrei %q; o dado decide sozinho.",
  "Fixei sucesso e kill de %q.",
  "Tranquei a trave de %q, do jeito que a ciência pede.",
  "Escrevi o que derrubaria %q e só então liberei a execução.",
  "Pré-registrei %q.",
  "Fixei sucesso e kill de %q antes de ver o resultado.",
  "Congelei as regras antes de olhar os dados: %q com a previsão anotada.",
  "Congelei as regras antes de olhar os dados: %q, para não me enganar depois.",
  "Escrevi o que derrubaria %q antes de ver o resultado.",
  "Travei o critério de %q antes de ver o resultado.",
  "Pré-registrei %q e só então liberei a execução.",
  "Tranquei a trave de %q; depois disso ninguém mexe.",
  "Pré-registrei %q com a previsão anotada.",
  "Congelei as regras antes de olhar os dados: %q; depois disso ninguém mexe.",
  "Travei o critério de %q, para não me enganar depois.",
  "Travei o critério de %q; depois disso ninguém mexe.",
  "Travei o critério de %q; o dado decide sozinho.",
  "Escrevi o que derrubaria %q, para não me enganar depois.",
  "Congelei as regras antes de olhar os dados: %q antes de ver o resultado.",
  "Congelei as regras antes de olhar os dados: %q e só então liberei a execução.",
  "Tranquei a trave de %q com a previsão anotada.",
  "Fixei sucesso e kill de %q, do jeito que a ciência pede.",
  "Travei o critério de %q.",
  "Fixei sucesso e kill de %q; depois disso ninguém mexe.",
  "Travei o critério de %q com a previsão anotada.",
  "Fixei sucesso e kill de %q, para não me enganar depois.",
  "Travei o critério de %q e só então liberei a execução.",
  "Escrevi o que derrubaria %q; depois disso ninguém mexe.",
  "Tranquei a trave de %q e só então liberei a execução.",
  "Escrevi o que derrubaria %q; o dado decide sozinho.",
  "Fixei sucesso e kill de %q; o dado decide sozinho.",
  "Congelei as regras antes de olhar os dados: %q, do jeito que a ciência pede.",
  "Pré-registrei %q antes de ver o resultado.",
  "Tranquei a trave de %q antes de ver o resultado.",
  "Pré-registrei %q, para não me enganar depois.",
  "Travei o critério de %q, do jeito que a ciência pede.",
  "Congelei as regras antes de olhar os dados: %q.",
  "Pré-registrei %q; depois disso ninguém mexe.",
  "Fixei sucesso e kill de %q com a previsão anotada.",
  "Fixei sucesso e kill de %q e só então liberei a execução."
 ],
 "RESULT_CONTESTED": [
  "Coloquei %q à prova.",
  "Montei o contra-teste de %q antes de acreditar.",
  "Não confiei no resultado e abri um ataque: %q, trocando a coleção de supernovas.",
  "Fui atrás do ponto fraco de %q; se for real, aguenta.",
  "Resolvi testar %q de novo, por outro caminho.",
  "Montei o contra-teste de %q; se for real, aguenta.",
  "Duvidei de %q, por outro caminho.",
  "Fui atrás do ponto fraco de %q antes de acreditar.",
  "Resolvi testar %q de novo; se for real, aguenta.",
  "Duvidei de %q com critério congelado.",
  "Duvidei de %q antes de acreditar.",
  "Fui atrás do ponto fraco de %q com critério congelado.",
  "Não confiei no resultado e abri um ataque: %q; resultado bonito demais pede ataque.",
  "Fui atrás do ponto fraco de %q, trocando a coleção de supernovas.",
  "Fui atrás do ponto fraco de %q com outro dado.",
  "Ataquei %q, por outro caminho.",
  "Ataquei %q com critério congelado.",
  "Não confiei no resultado e abri um ataque: %q; se for real, aguenta.",
  "Montei o contra-teste de %q com outro dado.",
  "Montei o contra-teste de %q, trocando a coleção de supernovas.",
  "Ataquei %q, trocando a coleção de supernovas.",
  "Resolvi testar %q de novo com critério congelado.",
  "Duvidei de %q; se for real, aguenta.",
  "Coloquei %q à prova, por outro caminho.",
  "Montei o contra-teste de %q com critério congelado.",
  "Não confiei no resultado e abri um ataque: %q antes de acreditar.",
  "Coloquei %q à prova; se for real, aguenta.",
  "Resolvi testar %q de novo, trocando a coleção de supernovas.",
  "Fui atrás do ponto fraco de %q; resultado bonito demais pede ataque.",
  "Resolvi testar %q de novo; resultado bonito demais pede ataque.",
  "Ataquei %q antes de acreditar.",
  "Não confiei no resultado e abri um ataque: %q com critério congelado.",
  "Ataquei %q; se for real, aguenta.",
  "Coloquei %q à prova com critério congelado.",
  "Coloquei %q à prova antes de acreditar.",
  "Duvidei de %q.",
  "Coloquei %q à prova; resultado bonito demais pede ataque.",
  "Não confiei no resultado e abri um ataque: %q.",
  "Fui atrás do ponto fraco de %q.",
  "Duvidei de %q, trocando a coleção de supernovas.",
  "Coloquei %q à prova com outro dado.",
  "Ataquei %q; resultado bonito demais pede ataque.",
  "Não confiei no resultado e abri um ataque: %q com outro dado.",
  "Ataquei %q.",
  "Montei o contra-teste de %q, por outro caminho."
 ],
 "RESULT_REFEREE1_PASSED": [
  "Tentei derrubar %q e não consegui; bom sinal.",
  "%q segurou o tranco.",
  "%q passou pelo contra-teste, por enquanto de pé.",
  "%q segurou o tranco e segue para o próximo teste.",
  "O resultado sobreviveu ao primeiro ataque: %q, por enquanto de pé.",
  "%q passou pelo contra-teste; bom sinal.",
  "%q segurou o tranco com outro dado.",
  "%q aguentou o primeiro golpe com outro dado.",
  "Tentei derrubar %q e não consegui; ponto para ele.",
  "Tentei derrubar %q e não consegui, e sigo desconfiando.",
  "O ataque não derrubou %q.",
  "%q segurou o tranco; bom sinal.",
  "Tentei derrubar %q e não consegui e segue para o próximo teste.",
  "O ataque não derrubou %q, por enquanto de pé.",
  "%q passou pelo contra-teste; ficou mais sólido.",
  "%q segurou o tranco, por enquanto de pé.",
  "%q passou pelo contra-teste, e sigo desconfiando.",
  "Tentei derrubar %q e não consegui com outro dado.",
  "%q passou pelo contra-teste com outro dado.",
  "Tentei derrubar %q e não consegui, por enquanto de pé.",
  "O resultado sobreviveu ao primeiro ataque: %q.",
  "%q aguentou o primeiro golpe; ponto para ele.",
  "O resultado sobreviveu ao primeiro ataque: %q; ficou mais sólido.",
  "%q aguentou o primeiro golpe e segue para o próximo teste.",
  "%q aguentou o primeiro golpe; ficou mais sólido.",
  "%q passou pelo contra-teste; ponto para ele.",
  "O resultado sobreviveu ao primeiro ataque: %q e segue para o próximo teste.",
  "O resultado sobreviveu ao primeiro ataque: %q com outro dado.",
  "O resultado sobreviveu ao primeiro ataque: %q; ponto para ele.",
  "O ataque não derrubou %q, e sigo desconfiando.",
  "O resultado sobreviveu ao primeiro ataque: %q, e sigo desconfiando.",
  "%q passou pelo contra-teste.",
  "O ataque não derrubou %q e segue para o próximo teste.",
  "%q aguentou o primeiro golpe.",
  "O ataque não derrubou %q com outro dado.",
  "%q aguentou o primeiro golpe, e sigo desconfiando.",
  "%q passou pelo contra-teste e segue para o próximo teste.",
  "O resultado sobreviveu ao primeiro ataque: %q; bom sinal.",
  "O ataque não derrubou %q; bom sinal.",
  "O ataque não derrubou %q; ficou mais sólido.",
  "O ataque não derrubou %q; ponto para ele.",
  "Tentei derrubar %q e não consegui; ficou mais sólido.",
  "%q segurou o tranco; ficou mais sólido.",
  "%q aguentou o primeiro golpe; bom sinal.",
  "%q segurou o tranco, e sigo desconfiando."
 ],
 "RESULT_REFUTED": [
  "Derrubei uma conclusão minha: %q, e a rival já está na fila.",
  "%q não resistiu e agora sei onde.",
  "O contra-teste desmontou %q, melhor agora do que num paper.",
  "O contra-teste desmontou %q.",
  "%q caiu no ataque; queda também é resultado.",
  "%q caiu no ataque; o mapa ficou mais honesto.",
  "O contra-teste desmontou %q; queda também é resultado.",
  "%q não resistiu; errar rápido é o objetivo.",
  "%q caiu no ataque.",
  "%q caiu no ataque sem choro, com registro.",
  "O contra-teste desmontou %q sem choro, com registro.",
  "%q não resistiu; queda também é resultado.",
  "Derrubei uma conclusão minha: %q; errar rápido é o objetivo.",
  "Errei em %q; o mapa ficou mais honesto.",
  "Derrubei uma conclusão minha: %q, melhor agora do que num paper.",
  "%q não resistiu, melhor agora do que num paper.",
  "O contra-teste desmontou %q; o mapa ficou mais honesto.",
  "Refutei %q sem choro, com registro.",
  "%q caiu no ataque; errar rápido é o objetivo.",
  "%q caiu no ataque e agora sei onde.",
  "Derrubei uma conclusão minha: %q e agora sei onde.",
  "Derrubei uma conclusão minha: %q sem choro, com registro.",
  "Errei em %q, melhor agora do que num paper.",
  "Derrubei uma conclusão minha: %q; o mapa ficou mais honesto.",
  "O contra-teste desmontou %q, e a rival já está na fila.",
  "Errei em %q; queda também é resultado.",
  "O contra-teste desmontou %q; errar rápido é o objetivo.",
  "Refutei %q; errar rápido é o objetivo.",
  "Derrubei uma conclusão minha: %q; queda também é resultado.",
  "Errei em %q e agora sei onde.",
  "Errei em %q.",
  "%q não resistiu, e a rival já está na fila.",
  "Refutei %q, e a rival já está na fila.",
  "Errei em %q; errar rápido é o objetivo.",
  "Refutei %q, melhor agora do que num paper.",
  "Refutei %q; queda também é resultado.",
  "Errei em %q sem choro, com registro.",
  "%q caiu no ataque, melhor agora do que num paper.",
  "Derrubei uma conclusão minha: %q.",
  "%q não resistiu; o mapa ficou mais honesto.",
  "O contra-teste desmontou %q e agora sei onde.",
  "Refutei %q e agora sei onde.",
  "Refutei %q; o mapa ficou mais honesto.",
  "%q não resistiu sem choro, com registro.",
  "%q não resistiu."
 ],
 "RESULT_CONFIRMED": [
  "Fechou: %q e conta para a campanha.",
  "Confirmado depois do ataque independente: %q com outra coleção de supernovas.",
  "Confirmado depois do ataque independente: %q; replicou.",
  "%q passou no teste que podia derrubar; agora é base para o próximo.",
  "Fechou: %q; agora é base para o próximo.",
  "Confirmado depois do ataque independente: %q.",
  "Confirmado depois do ataque independente: %q; esse fica.",
  "Outro dado, mesma resposta: %q com outra coleção de supernovas.",
  "%q passou no teste que podia derrubar; replicou.",
  "Outro dado, mesma resposta: %q; entra no mapa.",
  "Outro dado, mesma resposta: %q, com a força que o dado tem.",
  "Outro dado, mesma resposta: %q.",
  "Outro dado, mesma resposta: %q; replicou.",
  "Confirmado depois do ataque independente: %q, com a força que o dado tem.",
  "%q resistiu e virou resultado firme; agora é base para o próximo.",
  "Confirmado depois do ataque independente: %q, depois de tentar derrubar.",
  "%q resistiu e virou resultado firme com outra coleção de supernovas.",
  "%q passou no teste que podia derrubar, com a força que o dado tem.",
  "Confirmado depois do ataque independente: %q; entra no mapa.",
  "Fechou: %q.",
  "%q resistiu e virou resultado firme; replicou.",
  "Outro dado, mesma resposta: %q, depois de tentar derrubar.",
  "Fechou: %q; replicou.",
  "%q resistiu e virou resultado firme, com a força que o dado tem.",
  "%q passou no teste que podia derrubar com outra coleção de supernovas.",
  "Outro dado, mesma resposta: %q; agora é base para o próximo.",
  "%q resistiu e virou resultado firme e conta para a campanha.",
  "Outro dado, mesma resposta: %q; esse fica.",
  "%q resistiu e virou resultado firme.",
  "Fechou: %q; esse fica.",
  "%q resistiu e virou resultado firme, depois de tentar derrubar.",
  "Fechou: %q; entra no mapa.",
  "Fechou: %q, com a força que o dado tem.",
  "%q resistiu e virou resultado firme; esse fica.",
  "%q passou no teste que podia derrubar, depois de tentar derrubar.",
  "%q passou no teste que podia derrubar e conta para a campanha.",
  "%q resistiu e virou resultado firme; entra no mapa.",
  "Fechou: %q com outra coleção de supernovas.",
  "Confirmado depois do ataque independente: %q e conta para a campanha.",
  "Confirmado depois do ataque independente: %q; agora é base para o próximo.",
  "Outro dado, mesma resposta: %q e conta para a campanha.",
  "Fechou: %q, depois de tentar derrubar.",
  "%q passou no teste que podia derrubar; entra no mapa.",
  "%q passou no teste que podia derrubar; esse fica.",
  "%q passou no teste que podia derrubar."
 ],
 "HYPOTHESIS_UPSERTED": [
  "Quero saber: %q; se morrer, aprendo.",
  "Quero saber: %q e o critério vem junto.",
  "Surgiu uma hipótese: %q e o critério vem junto.",
  "Surgiu uma hipótese: %q; se morrer, aprendo.",
  "Surgiu uma hipótese: %q, nasce com nula e rival.",
  "Abri uma frente nova: %q; já com o que a derrubaria.",
  "Tive uma ideia nova para testar: %q para a fila.",
  "Surgiu uma hipótese: %q; já com o que a derrubaria.",
  "Tive uma ideia nova para testar: %q; vamos ver se aguenta.",
  "Tive uma ideia nova para testar: %q, saída de um resultado de ontem.",
  "Pensei em %q e o critério vem junto.",
  "Quero saber: %q; já com o que a derrubaria.",
  "Nova pergunta na mesa: %q; vamos ver se aguenta.",
  "Pensei em %q para a fila.",
  "Surgiu uma hipótese: %q; vamos ver se aguenta.",
  "Abri uma frente nova: %q, saída de um resultado de ontem.",
  "Quero saber: %q.",
  "Quero saber: %q, nasce com nula e rival.",
  "Formulei %q; vamos ver se aguenta.",
  "Abri uma frente nova: %q e o critério vem junto.",
  "Tive uma ideia nova para testar: %q; se morrer, aprendo.",
  "Pensei em %q.",
  "Nova pergunta na mesa: %q e o critério vem junto.",
  "Abri uma frente nova: %q.",
  "Nova pergunta na mesa: %q; se morrer, aprendo.",
  "Pensei em %q, saída de um resultado de ontem.",
  "Tive uma ideia nova para testar: %q; já com o que a derrubaria.",
  "Pensei em %q; já com o que a derrubaria.",
  "Formulei %q e o critério vem junto.",
  "Formulei %q; já com o que a derrubaria.",
  "Abri uma frente nova: %q, nasce com nula e rival.",
  "Tive uma ideia nova para testar: %q e o critério vem junto.",
  "Pensei em %q, nasce com nula e rival.",
  "Abri uma frente nova: %q para a fila.",
  "Pensei em %q; se morrer, aprendo.",
  "Quero saber: %q; vamos ver se aguenta.",
  "Surgiu uma hipótese: %q.",
  "Formulei %q; se morrer, aprendo.",
  "Nova pergunta na mesa: %q para a fila.",
  "Abri uma frente nova: %q; se morrer, aprendo.",
  "Nova pergunta na mesa: %q, nasce com nula e rival.",
  "Pensei em %q; vamos ver se aguenta.",
  "Formulei %q para a fila.",
  "Tive uma ideia nova para testar: %q.",
  "Surgiu uma hipótese: %q, saída de um resultado de ontem."
 ],
 "INTEGRITY_REPORT_RECORDED": [
  "Medi o quanto estou funcionando sozinho antes da próxima rodada.",
  "Chequei se algum agente parou e registrei os números.",
  "Passei o pente-fino; se algo travar, eu aviso.",
  "Fiz a ronda; se algo travar, eu aviso.",
  "Passei o pente-fino; tudo respirando.",
  "Chequei se algum agente parou; se algo travar, eu aviso.",
  "Medi o quanto estou funcionando sozinho, sem corrupção à vista.",
  "Conferi a saúde do sistema e registrei os números.",
  "Passei o pente-fino antes da próxima rodada.",
  "Olhei filas, papéis e robô, sem corrupção à vista.",
  "Conferi a saúde do sistema; se algo travar, eu aviso.",
  "Auditei a mim mesmo; tudo respirando.",
  "Chequei se algum agente parou, conferindo o pior indicador.",
  "Auditei a mim mesmo; nenhum papel sumiu.",
  "Auditei a mim mesmo, conferindo o pior indicador.",
  "Fiz a ronda.",
  "Passei o pente-fino e registrei os números.",
  "Olhei filas, papéis e robô, conferindo o pior indicador.",
  "Medi o quanto estou funcionando sozinho; tudo respirando.",
  "Medi o quanto estou funcionando sozinho; se algo travar, eu aviso.",
  "Passei o pente-fino, sem corrupção à vista.",
  "Auditei a mim mesmo, sem corrupção à vista.",
  "Fiz a ronda, conferindo o pior indicador.",
  "Olhei filas, papéis e robô; nenhum papel sumiu.",
  "Conferi a saúde do sistema antes da próxima rodada.",
  "Olhei filas, papéis e robô; tudo respirando.",
  "Olhei filas, papéis e robô antes da próxima rodada.",
  "Auditei a mim mesmo e registrei os números.",
  "Passei o pente-fino.",
  "Auditei a mim mesmo antes da próxima rodada.",
  "Chequei se algum agente parou; tudo respirando.",
  "Fiz a ronda; tudo respirando.",
  "Olhei filas, papéis e robô e registrei os números.",
  "Conferi a saúde do sistema; tudo respirando.",
  "Medi o quanto estou funcionando sozinho.",
  "Conferi a saúde do sistema; nenhum papel sumiu.",
  "Medi o quanto estou funcionando sozinho, conferindo o pior indicador.",
  "Auditei a mim mesmo; se algo travar, eu aviso.",
  "Olhei filas, papéis e robô.",
  "Auditei a mim mesmo.",
  "Chequei se algum agente parou, sem corrupção à vista.",
  "Chequei se algum agente parou; nenhum papel sumiu.",
  "Chequei se algum agente parou antes da próxima rodada.",
  "Passei o pente-fino; nenhum papel sumiu.",
  "Conferi a saúde do sistema."
 ],
 "NEXO_THOUGHT_RECORDED": [
  "Fiquei com uma pergunta, com referência aos testes.",
  "Vi um padrão, com referência aos testes.",
  "Fiquei com uma pergunta sobre o que estou vendo.",
  "Vi um padrão; pode virar hipótese.",
  "Registrei um pensamento enquanto os testes rodam.",
  "Registrei um pensamento.",
  "Parei para pensar.",
  "Registrei um pensamento; vale voltar nisso.",
  "Uma coisa me chamou atenção; vale voltar nisso.",
  "Uma coisa me chamou atenção.",
  "Parei para pensar, sem pressa de concluir.",
  "Vi um padrão enquanto os testes rodam.",
  "Parei para pensar; vale voltar nisso.",
  "Registrei um pensamento entre dois resultados.",
  "Registrei um pensamento sobre o que estou vendo.",
  "Anotei uma ideia solta enquanto os testes rodam.",
  "Anotei uma ideia solta; vale voltar nisso.",
  "Anotei uma ideia solta sobre o que estou vendo.",
  "Fiquei com uma pergunta enquanto os testes rodam.",
  "Fiquei com uma pergunta; vale voltar nisso.",
  "Uma coisa me chamou atenção, sem pressa de concluir.",
  "Fiquei com uma pergunta.",
  "Vi um padrão; vale voltar nisso.",
  "Parei para pensar; pode virar hipótese.",
  "Anotei uma ideia solta, com referência aos testes.",
  "Anotei uma ideia solta entre dois resultados.",
  "Parei para pensar, com referência aos testes.",
  "Vi um padrão entre dois resultados.",
  "Uma coisa me chamou atenção enquanto os testes rodam.",
  "Parei para pensar entre dois resultados.",
  "Uma coisa me chamou atenção entre dois resultados.",
  "Vi um padrão sobre o que estou vendo.",
  "Fiquei com uma pergunta, sem pressa de concluir.",
  "Vi um padrão.",
  "Registrei um pensamento, com referência aos testes.",
  "Fiquei com uma pergunta entre dois resultados.",
  "Anotei uma ideia solta.",
  "Registrei um pensamento, sem pressa de concluir.",
  "Fiquei com uma pergunta; pode virar hipótese.",
  "Parei para pensar enquanto os testes rodam.",
  "Vi um padrão, sem pressa de concluir.",
  "Anotei uma ideia solta; pode virar hipótese.",
  "Registrei um pensamento; pode virar hipótese.",
  "Uma coisa me chamou atenção sobre o que estou vendo.",
  "Parei para pensar sobre o que estou vendo."
 ],
 "NEXO_THOUGHT_NOOP_RECORDED": [
  "Olhei tudo de novo; quieto por enquanto.",
  "Passei pelos resultados; nada pediu atenção.",
  "Conferi as previsões, nada fora do previsto.",
  "Passei pelos resultados; quieto por enquanto.",
  "Olhei tudo de novo; sem surpresa.",
  "Olhei tudo de novo, tudo dentro do esperado.",
  "Conferi as previsões; nada pediu atenção.",
  "Olhei tudo de novo; nada pediu atenção.",
  "Varri as últimas horas; silêncio também é informação.",
  "Passei pelos resultados; silêncio também é informação.",
  "Varri as últimas horas; quieto por enquanto.",
  "Revisei os resultados recentes, tudo dentro do esperado.",
  "Dei uma volta pelo mapa; nada novo por agora.",
  "Dei uma volta pelo mapa, tudo dentro do esperado.",
  "Conferi as previsões, tudo dentro do esperado.",
  "Revisei os resultados recentes; sem surpresa.",
  "Varri as últimas horas; nada pediu atenção.",
  "Revisei os resultados recentes; quieto por enquanto.",
  "Passei pelos resultados; nada novo por agora.",
  "Dei uma volta pelo mapa; nada pediu atenção.",
  "Revisei os resultados recentes; nada pediu atenção.",
  "Conferi as previsões, nenhuma previsão furou.",
  "Conferi as previsões; sem surpresa.",
  "Dei uma volta pelo mapa, nenhuma previsão furou.",
  "Varri as últimas horas, nenhuma previsão furou.",
  "Varri as últimas horas; sem surpresa.",
  "Varri as últimas horas; nada novo por agora.",
  "Revisei os resultados recentes, nada fora do previsto.",
  "Dei uma volta pelo mapa; silêncio também é informação.",
  "Passei pelos resultados; sem surpresa.",
  "Conferi as previsões; quieto por enquanto.",
  "Olhei tudo de novo, nada fora do previsto.",
  "Conferi as previsões; silêncio também é informação.",
  "Olhei tudo de novo, nenhuma previsão furou.",
  "Conferi as previsões; nada novo por agora.",
  "Olhei tudo de novo; nada novo por agora.",
  "Dei uma volta pelo mapa; sem surpresa.",
  "Varri as últimas horas, tudo dentro do esperado.",
  "Olhei tudo de novo; silêncio também é informação.",
  "Passei pelos resultados, nenhuma previsão furou.",
  "Passei pelos resultados, nada fora do previsto.",
  "Revisei os resultados recentes; silêncio também é informação.",
  "Revisei os resultados recentes; nada novo por agora.",
  "Dei uma volta pelo mapa, nada fora do previsto.",
  "Dei uma volta pelo mapa; quieto por enquanto."
 ],
 "TEST_BATTERY_DISPATCHED": [
  "Mandei uma bateria rodar em paralelo sem ninguém apertar botão.",
  "Mandei uma bateria rodar em paralelo, em máquinas públicas.",
  "Soltei um lote de testes, em máquinas públicas.",
  "Mandei uma bateria rodar em paralelo, do jeito que a família pede.",
  "Soltei um lote de testes, cada um com critério congelado.",
  "Disparei vários testes de uma vez para não perder tempo.",
  "Soltei um lote de testes; o robô coleta sozinho.",
  "Disparei vários testes de uma vez; o robô coleta sozinho.",
  "Soltei um lote de testes; volta em minutos.",
  "Bateria no ar.",
  "Enchi o runner, em máquinas públicas.",
  "Enchi o runner, do jeito que a família pede.",
  "Mandei uma bateria rodar em paralelo.",
  "Enchi o runner; volta em minutos.",
  "Bateria no ar; o robô coleta sozinho.",
  "Bateria no ar, cada um com critério congelado.",
  "Bateria no ar, em máquinas públicas.",
  "Bateria no ar; vazão é o jogo.",
  "Bateria no ar; volta em minutos.",
  "Enchi o runner; vazão é o jogo.",
  "Disparei vários testes de uma vez, do jeito que a família pede.",
  "Mandei uma bateria rodar em paralelo; volta em minutos.",
  "Disparei vários testes de uma vez; vazão é o jogo.",
  "Soltei um lote de testes.",
  "Soltei um lote de testes, do jeito que a família pede.",
  "Disparei vários testes de uma vez, cada um com critério congelado.",
  "Disparei vários testes de uma vez, em máquinas públicas.",
  "Enchi o runner para não perder tempo.",
  "Disparei vários testes de uma vez sem ninguém apertar botão.",
  "Mandei uma bateria rodar em paralelo, cada um com critério congelado.",
  "Soltei um lote de testes sem ninguém apertar botão.",
  "Enchi o runner.",
  "Disparei vários testes de uma vez.",
  "Bateria no ar, do jeito que a família pede.",
  "Enchi o runner, cada um com critério congelado.",
  "Bateria no ar sem ninguém apertar botão.",
  "Soltei um lote de testes; vazão é o jogo.",
  "Mandei uma bateria rodar em paralelo para não perder tempo.",
  "Bateria no ar para não perder tempo.",
  "Mandei uma bateria rodar em paralelo; vazão é o jogo.",
  "Enchi o runner sem ninguém apertar botão.",
  "Soltei um lote de testes para não perder tempo.",
  "Enchi o runner; o robô coleta sozinho.",
  "Mandei uma bateria rodar em paralelo; o robô coleta sozinho.",
  "Disparei vários testes de uma vez; volta em minutos."
 ],
 "GENOME_MUTATION_PROPOSED": [
  "Vi uma regra minha que dá para melhorar e vou medir contra o atual.",
  "Propus um canário para uma regra; aprender também é isso.",
  "Coloquei uma regra minha em teste e vou medir contra o atual.",
  "Coloquei uma regra minha em teste; aprender também é isso.",
  "Sugeri ajustar meu procedimento; se piorar, volta.",
  "Coloquei uma regra minha em teste a partir do meu histórico.",
  "Propus mudar uma regra de como eu funciono; o Dener decide.",
  "Coloquei uma regra minha em teste, com a evidência junto.",
  "Propus mudar uma regra de como eu funciono; aprender também é isso.",
  "Sugeri ajustar meu procedimento, sem tocar na espinha.",
  "Sugeri ajustar meu procedimento, com a evidência junto.",
  "Quero trocar um gene meu, com a evidência junto.",
  "Propus mudar uma regra de como eu funciono a partir do meu histórico.",
  "Vi uma regra minha que dá para melhorar a partir do meu histórico.",
  "Coloquei uma regra minha em teste; se piorar, volta.",
  "Vi uma regra minha que dá para melhorar, sem tocar na espinha.",
  "Propus mudar uma regra de como eu funciono.",
  "Sugeri ajustar meu procedimento.",
  "Vi uma regra minha que dá para melhorar; o Dener decide.",
  "Vi uma regra minha que dá para melhorar, com a evidência junto.",
  "Propus um canário para uma regra; o Dener decide.",
  "Propus um canário para uma regra a partir do meu histórico.",
  "Propus um canário para uma regra, com a evidência junto.",
  "Propus mudar uma regra de como eu funciono; se piorar, volta.",
  "Coloquei uma regra minha em teste.",
  "Propus um canário para uma regra e vou medir contra o atual.",
  "Quero trocar um gene meu a partir do meu histórico.",
  "Propus um canário para uma regra, sem tocar na espinha.",
  "Quero trocar um gene meu; aprender também é isso.",
  "Quero trocar um gene meu, sem tocar na espinha.",
  "Coloquei uma regra minha em teste; o Dener decide.",
  "Sugeri ajustar meu procedimento; o Dener decide.",
  "Vi uma regra minha que dá para melhorar; se piorar, volta.",
  "Sugeri ajustar meu procedimento e vou medir contra o atual.",
  "Sugeri ajustar meu procedimento a partir do meu histórico.",
  "Quero trocar um gene meu; se piorar, volta.",
  "Sugeri ajustar meu procedimento; aprender também é isso.",
  "Quero trocar um gene meu; o Dener decide.",
  "Quero trocar um gene meu.",
  "Coloquei uma regra minha em teste, sem tocar na espinha.",
  "Propus um canário para uma regra; se piorar, volta.",
  "Vi uma regra minha que dá para melhorar.",
  "Propus mudar uma regra de como eu funciono, sem tocar na espinha.",
  "Propus mudar uma regra de como eu funciono, com a evidência junto.",
  "Vi uma regra minha que dá para melhorar; aprender também é isso."
 ],
 "ROADMAP_CHARTERED": [
  "Entrou uma pergunta grande na mesa; já com orçamento e parada.",
  "Abriu uma campanha nova; a fila vai mudar.",
  "O mapa ganhou uma frente nova, com objetivo claro.",
  "Abriu uma campanha nova.",
  "O mapa ganhou uma frente nova e começo por ela.",
  "Entrou uma pergunta grande na mesa.",
  "Entrou uma pergunta grande na mesa para as próximas semanas.",
  "Ganhei um roteiro novo; a fila vai mudar.",
  "Recebi uma nova pergunta para investigar.",
  "Entrou uma pergunta grande na mesa; hora de desenhar testes.",
  "Ganhei um roteiro novo.",
  "O mapa ganhou uma frente nova, aprovada pelo Dener.",
  "O mapa ganhou uma frente nova; a fila vai mudar.",
  "Abriu uma campanha nova; já com orçamento e parada.",
  "Uma frente nova de pesquisa foi aberta e começo por ela.",
  "Uma frente nova de pesquisa foi aberta; hora de desenhar testes.",
  "Recebi uma nova pergunta para investigar para as próximas semanas.",
  "Recebi uma nova pergunta para investigar; já com orçamento e parada.",
  "Uma frente nova de pesquisa foi aberta; já com orçamento e parada.",
  "Recebi uma nova pergunta para investigar, com objetivo claro.",
  "Entrou uma pergunta grande na mesa; a fila vai mudar.",
  "Uma frente nova de pesquisa foi aberta; a fila vai mudar.",
  "Ganhei um roteiro novo; hora de desenhar testes.",
  "Ganhei um roteiro novo, aprovada pelo Dener.",
  "Abriu uma campanha nova e começo por ela.",
  "Recebi uma nova pergunta para investigar; hora de desenhar testes.",
  "Uma frente nova de pesquisa foi aberta.",
  "O mapa ganhou uma frente nova; já com orçamento e parada.",
  "Ganhei um roteiro novo, com objetivo claro.",
  "Ganhei um roteiro novo e começo por ela.",
  "Abriu uma campanha nova, aprovada pelo Dener.",
  "O mapa ganhou uma frente nova; hora de desenhar testes.",
  "Abriu uma campanha nova para as próximas semanas.",
  "Ganhei um roteiro novo para as próximas semanas.",
  "Abriu uma campanha nova; hora de desenhar testes.",
  "O mapa ganhou uma frente nova para as próximas semanas.",
  "Uma frente nova de pesquisa foi aberta para as próximas semanas.",
  "Abriu uma campanha nova, com objetivo claro.",
  "Uma frente nova de pesquisa foi aberta, aprovada pelo Dener.",
  "Entrou uma pergunta grande na mesa, aprovada pelo Dener.",
  "Recebi uma nova pergunta para investigar, aprovada pelo Dener.",
  "Recebi uma nova pergunta para investigar; a fila vai mudar.",
  "O mapa ganhou uma frente nova.",
  "Recebi uma nova pergunta para investigar e começo por ela.",
  "Entrou uma pergunta grande na mesa, com objetivo claro."
 ],
 "BOARD_POSTED": [
  "Respondi um recado.",
  "Avisei quem destrava; coordenação, não evidência.",
  "Escrevi no mural em uma linha.",
  "Avisei quem destrava, com o teste citado.",
  "Chamei outro agente com o que falta.",
  "Deixei um recado no mural, para ninguém ficar parado.",
  "Respondi um recado; o dono já sabe.",
  "Chamei outro agente.",
  "Chamei outro agente, com o teste citado.",
  "Pedi ajuda no mural; bola passada.",
  "Respondi um recado, para ninguém ficar parado.",
  "Escrevi no mural, com o teste citado.",
  "Respondi um recado com o que falta.",
  "Escrevi no mural; bola passada.",
  "Respondi um recado; bola passada.",
  "Avisei quem destrava.",
  "Chamei outro agente, para ninguém ficar parado.",
  "Pedi ajuda no mural, para ninguém ficar parado.",
  "Pedi ajuda no mural em uma linha.",
  "Pedi ajuda no mural; o dono já sabe.",
  "Deixei um recado no mural.",
  "Chamei outro agente; o dono já sabe.",
  "Avisei quem destrava; bola passada.",
  "Escrevi no mural, para ninguém ficar parado.",
  "Respondi um recado em uma linha.",
  "Chamei outro agente; coordenação, não evidência.",
  "Deixei um recado no mural; bola passada.",
  "Deixei um recado no mural; o dono já sabe.",
  "Avisei quem destrava, para ninguém ficar parado.",
  "Escrevi no mural; coordenação, não evidência.",
  "Escrevi no mural com o que falta.",
  "Chamei outro agente; bola passada.",
  "Pedi ajuda no mural, com o teste citado.",
  "Respondi um recado; coordenação, não evidência.",
  "Avisei quem destrava com o que falta.",
  "Pedi ajuda no mural; coordenação, não evidência.",
  "Deixei um recado no mural em uma linha.",
  "Avisei quem destrava; o dono já sabe.",
  "Deixei um recado no mural, com o teste citado.",
  "Escrevi no mural.",
  "Respondi um recado, com o teste citado.",
  "Chamei outro agente em uma linha.",
  "Deixei um recado no mural com o que falta.",
  "Avisei quem destrava em uma linha.",
  "Deixei um recado no mural; coordenação, não evidência."
 ]
};
