export function operationsPage(nonce) {
  if(!/^[A-Za-z0-9+/=]+$/.test(nonce)) throw new Error('INVALID_NONCE');
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NEXO | Opera&#231;&#227;o privada</title><style nonce="${nonce}">
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#09131d;color:#e5eff8}*{box-sizing:border-box}body{margin:0;padding:32px;max-width:1480px;margin-inline:auto}header{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}h1{font-size:36px;font-weight:650;letter-spacing:-1px;margin:8px 0}small,.muted{color:#9bb0c2}a{color:#8ed4ef;text-decoration:none}button,select{font:inherit;color:inherit;background:#122432;border:1px solid #294756;border-radius:8px;padding:10px 14px;cursor:pointer}button:disabled{opacity:.4;cursor:default}nav{display:flex;gap:8px;margin:26px 0 18px;flex-wrap:wrap}.active{background:#174b60;border-color:#6abddd}.notice{border-left:3px solid #6abddd;padding:12px 16px;background:#10222d;margin:12px 0 20px;line-height:1.5}.summary{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.metric{padding:12px 16px;border:1px solid #243d4c;border-radius:8px;min-width:125px}.metric strong{display:block;font-size:26px}.metric span{font-size:12px;color:#adc1d1}table{width:100%;border-collapse:collapse;table-layout:fixed}th{text-align:left;color:#9bb0c2;font-size:12px;text-transform:uppercase;letter-spacing:1px}th,td{padding:15px 12px;vertical-align:top;border-bottom:1px solid #223847;overflow-wrap:anywhere}th:first-child{width:31%}th:nth-child(2){width:19%}th:nth-child(3){width:15%}td{font-size:14px;line-height:1.45}td small{display:block;margin-top:5px;font-size:11px}.paging{display:flex;gap:10px;align-items:center;justify-content:flex-end;margin-top:20px}.source{font-size:12px;overflow-wrap:anywhere;margin-top:8px}.error{border-color:#efad75;color:#ffcfab}.controls{display:flex;gap:8px;align-items:center}.empty{padding:32px;border:1px solid #294756;border-radius:8px}.scroll{overflow-x:auto}@media(max-width:700px){body{padding:18px}h1{font-size:30px}table{min-width:690px}.metric{min-width:105px}}
</style></head><body><header><div><small>NEXO / ATLAS PRIVADO</small><h1>Opera&#231;&#227;o</h1><div class="muted">Campanhas, trabalho e recibos da mesma Tower.</div></div><div class="controls"><a href="/#/privado">Voltar &#224; teia</a><button id="refresh">Atualizar</button><button id="logout">Sair</button></div></header>
<div id="source" class="source muted">Verificando sess&#227;o e fonte...</div>
<nav id="tabs"><button data-view="work" class="active">Trabalho</button><button data-view="campaigns">Campanhas</button><button data-view="receipts">Recibos</button></nav>
<div id="notice" class="notice" role="status">Esta tela n&#227;o dispara testes nem altera contratos. READY registrado n&#227;o substitui admiss&#227;o; recibo n&#227;o substitui resultado cient&#237;fico.</div>
<div id="summary" class="summary"></div><div class="scroll"><table><thead id="head"></thead><tbody id="rows"></tbody></table></div>
<div class="paging"><button id="previous" disabled>Anterior</button><span id="page" class="muted"></span><button id="next" disabled>Pr&#243;xima</button></div>
<script nonce="${nonce}">
const $=id=>document.getElementById(id), labels={PREPARATION:'Preparar',REPAIR:'Reparar',RUN_FOLLOWUP:'Execu\u00e7\u00e3o / checkpoint',REVIEW:'Resultado / revis\u00e3o',ADMISSION_CANDIDATE:'Conferir admiss\u00e3o',DECISION:'Decis\u00e3o expl\u00edcita',CLOSED_CAMPAIGN:'Campanha encerrada',TERMINAL:'Terminal',APPLIED:'Aplica\u00e7\u00e3o registrada',REJECTED_TERMINAL:'Rejei\u00e7\u00e3o terminal',DEFERRED_DEPENDENCY:'Depend\u00eancia registrada',ACTIVE:'Ativa',CLOSED:'Encerrada',PROPOSED:'Proposta'};
let view='work',cursors=[null],nextCursor=null,controller=null,generation=0,expiryTimer=null;
function clear(){ $('rows').replaceChildren();$('head').replaceChildren();$('summary').replaceChildren();$('page').textContent='';$('source').textContent='';$('next').disabled=true;$('previous').disabled=true; }
function message(text,bad=false){$('notice').textContent=text;$('notice').classList.toggle('error',bad);}
function cell(row,value,detail){const td=document.createElement('td');td.textContent=value||'N\u00e3o informado';if(detail){const small=document.createElement('small');small.textContent=detail;td.append(small);}row.append(td);}
async function session(){const r=await fetch('/api/atlas-session',{cache:'no-store',credentials:'same-origin'});const s=await r.json();if(!r.ok||!s.authenticated||!Number.isFinite(Date.parse(s.expiresAt)))throw Error('AUTH');clearTimeout(expiryTimer);const left=Date.parse(s.expiresAt)-Date.now();if(left<=0)throw Error('AUTH');expiryTimer=setTimeout(()=>{generation++;controller?.abort();clear();message('Sess\u00e3o expirada. Entre novamente pelo Atlas.',true);},left);}
async function load(){const mine=++generation;controller?.abort();controller=new AbortController();$('next').disabled=true;$('previous').disabled=true;message('Lendo a fonte can\u00f4nica...');
 try{await session();if(mine!==generation)return;const q=new URLSearchParams({view,limit:'30'});const cursor=cursors.at(-1);if(cursor)q.set('cursor',cursor);
 const r=await fetch('/api/atlas-operations?'+q,{cache:'no-store',credentials:'same-origin',signal:controller.signal});const data=await r.json();if(mine!==generation)return;
 if(r.status===401)throw Error('AUTH');if(r.status===409){clear();cursors=[null];message('A Tower mudou entre p\u00e1ginas. Use Atualizar para ler a nova revis\u00e3o.',true);return;}
 if(!r.ok||data.contract!=='NEXO_OPERATIONAL_FRONTIER_V1'||data.access!=='PRIVATE')throw Error('SOURCE');
 clear();$('source').textContent='Fonte: '+data.source_revision+' | atualizada: '+(data.source_updated_at||'n\u00e3o informada');
 const names=view==='work'?['Trabalho / fonte','Estado registrado / etapa','Respons\u00e1vel','Pr\u00f3ximo passo / impedimento']:view==='campaigns'?['Pergunta / fonte','Estado registrado','Contrato','Crit\u00e9rio de parada']:['Opera\u00e7\u00e3o / fonte','\u00daltimo recibo','Registrado em','Motivo / integridade'];
 const tr=document.createElement('tr');for(const name of names){const th=document.createElement('th');th.textContent=name;tr.append(th);}$('head').append(tr);
 for(const [key,count] of Object.entries(data.counts)){const box=document.createElement('div');box.className='metric';const strong=document.createElement('strong');strong.textContent=count;const label=document.createElement('span');label.textContent=labels[key]||key;box.append(strong,label);$('summary').append(box);}
 for(const item of data.items){const row=document.createElement('tr');
 if(view==='work'){cell(row,item.title||item.id,item.id+' | '+item.source_path);cell(row,labels[item.lane]||item.lane,item.canonical_status);cell(row,item.owner);cell(row,item.next_action,item.blocker);}
 else if(view==='campaigns'){cell(row,item.question||item.id,item.source_path);cell(row,labels[item.canonical_status]||item.canonical_status);cell(row,item.contract_ref);cell(row,Array.isArray(item.stop_criteria)?item.stop_criteria.join('; '):item.stop_criteria);}
 else{cell(row,item.id,item.source_path);cell(row,labels[item.outcome]||item.outcome);cell(row,item.updated_at);cell(row,item.reason||item.retry_condition,item.payload_sha256);}$('rows').append(row);}
 nextCursor=data.next_cursor;$('next').disabled=!data.has_more;$('previous').disabled=cursors.length===1;$('page').textContent='P\u00e1gina '+cursors.length+' | '+data.total_count+' registros';
 message(data.total_count?view==='receipts'?'\u00daltimo recibo por opera\u00e7\u00e3o. Este total inclui hist\u00f3rico e n\u00e3o mede sozinho a fila pendente.':'Proje\u00e7\u00e3o de leitura. Os estados originais s\u00e3o preservados; sugest\u00f5es de encaminhamento n\u00e3o concedem permiss\u00e3o de execu\u00e7\u00e3o.':'A cole\u00e7\u00e3o consultada est\u00e1 vazia nesta revis\u00e3o.');
 }catch(e){if(e.name==='AbortError'||mine!==generation)return;clear();message(e.message==='AUTH'?'Sess\u00e3o indispon\u00edvel. Entre pelo Atlas.':'Fonte indispon\u00edvel. Nenhuma contagem atual foi inferida.',true);}}
$('tabs').addEventListener('click',e=>{if(!e.target.dataset.view)return;view=e.target.dataset.view;cursors=[null];for(const b of $('tabs').children)b.classList.toggle('active',b.dataset.view===view);load();});
$('refresh').onclick=()=>{cursors=[null];load();};$('next').onclick=()=>{if(nextCursor){cursors.push(nextCursor);load();}};$('previous').onclick=()=>{if(cursors.length>1){cursors.pop();load();}};
$('logout').onclick=async()=>{generation++;controller?.abort();clearTimeout(expiryTimer);clear();try{const r=await fetch('/api/atlas-session',{method:'DELETE',credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error();message('Sess\u00e3o encerrada.');}catch{message('Dados removidos desta tela, mas a revoga\u00e7\u00e3o no servidor n\u00e3o foi confirmada. Tente sair novamente.',true);}};
window.addEventListener('pagehide',()=>{generation++;controller?.abort();clearTimeout(expiryTimer);clear();});window.addEventListener('pageshow',e=>{if(e.persisted){cursors=[null];load();}});load();
</script></body></html>`;
}
