import {AtlasEngine} from './graph/engine.mjs';
import {getGraph,getSnapshotHealth,clearSnapshotCache} from './lib/snapshot-loader.mjs';

function semanticLayerForZoom(zoom){const z=Number(zoom)||1;return z<.95?'macro':z<1.95?'scientific':'provenance'}
const escapeHtml=value=>String(value??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));
function createInspector(root,{onTrace,onFocus}={}){const api={current:null};const field=(l,v)=>v?`<div class="kv"><b>${escapeHtml(l)}</b><span>${escapeHtml(v)}</span></div>`:'';function hide(){root.classList.remove('open');root.setAttribute('aria-hidden','true')}function show(node,graph){if(!node)return;api.current=node;const refs=Array.isArray(node.sourceRefs)?node.sourceRefs:[],relations=(graph?.edges||[]).filter(e=>e.source===node.id||e.target===node.id);root.innerHTML=`<header class="inspector-head"><small>${escapeHtml(node.visualType||node.subtype||node.type||'ENTITY')}</small><h2>${escapeHtml(node.label||node.id)}</h2><p>${escapeHtml(node.id)}</p><button class="inspector-close" type="button" aria-label="Fechar">×</button></header><div class="inspector-body"><section class="inspector-section"><small>CONTEXTO</small>${field('status',node.status)}${field('authority',node.authority)}${field('domain',node.domain)}${field('atividade',node.activityAt)}</section>${node.summary?`<section class="inspector-section"><small>RESUMO</small><p>${escapeHtml(node.summary)}</p></section>`:''}<section class="inspector-section"><small>TOPOLOGIA</small>${field('relações',relations.length)}${field('sourceRefs',refs.length)}</section>${refs.length?`<section class="inspector-section"><small>PROVENANCE</small>${refs.slice(0,8).map(r=>`<div class="source-ref"><b>${escapeHtml(r.source||'SOURCE')}</b><span>${escapeHtml(r.sourceRef||r.sourceId||'')}</span></div>`).join('')}</section>`:''}<div class="inspector-actions"><button type="button" data-action="focus">Centralizar</button><button type="button" data-action="trace">Abrir lineage</button></div></div>`;root.querySelector('.inspector-close')?.addEventListener('click',hide);root.querySelector('[data-action="focus"]')?.addEventListener('click',()=>onFocus?.(node));root.querySelector('[data-action="trace"]')?.addEventListener('click',()=>onTrace?.(node));root.classList.add('open');root.setAttribute('aria-hidden','false')}Object.assign(api,{show,hide});hide();return api}

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={view:'macro',focus:'system:NEXO',history:['system:NEXO'],graph:null,rawGraph:null,auto:true,window:'all',loading:false};
const canvas=$('#cosmos');let zoomTimer=0,toastTimer=0;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function setLoading(on,label='Lendo snapshot do Drive…'){state.loading=on;$('#loading span').textContent=label;$('#loading').classList.toggle('hidden',!on)}
const engine=new AtlasEngine(canvas,{onSelect:node=>selectNode(node),onOpen:node=>openNode(node),onZoom:zoom=>{if(!state.auto)return;clearTimeout(zoomTimer);zoomTimer=setTimeout(()=>{const next=semanticLayerForZoom(zoom);if(next!==state.view)changeView(next,{fromZoom:true})},160)}});
const inspector=createInspector($('#inspector'),{onTrace:n=>changeView('provenance',{focus:n.id,manual:true}),onFocus:n=>{state.focus=n.id;engine.setSelected(n.id);engine.focusSelected()}});
function titleFor(){if(state.view==='macro')return['NEXO / EXPLORE · MACRO','Universo do NEXO','Domínios, campanhas e sistemas compilados diretamente do Google Drive.'];if(state.view==='scientific')return['NEXO / EXPLORE · SCIENTIFIC','Rede científica','Claims, hipóteses, testes e resultados em profundidade causal.'];return['NEXO / EXPLORE · PROVENANCE','Linhas de origem','Fontes, relações e rastreabilidade do objeto selecionado.']}
function syncChrome(){const[eye,title,sub]=titleFor();$('#eyebrow').textContent=eye;$('#title').textContent=title;$('#subtitle').textContent=sub;$('#depth-label').textContent=state.view.toUpperCase();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#auto-layer').classList.toggle('active',state.auto)}
function applyWindow(graph){if(state.window==='all')return graph;const days=Number(state.window),cut=Date.now()-days*86400000,focus=graph.focus,nodes=graph.nodes.filter(n=>n.id===focus||!n.activityAt||new Date(n.activityAt).getTime()>=cut),ids=new Set(nodes.map(n=>n.id));return{...graph,nodes,edges:graph.edges.filter(e=>ids.has(e.source)&&ids.has(e.target))}}
function renderGraph(){if(!state.rawGraph)return;state.graph=applyWindow(state.rawGraph);engine.setData(state.graph,{focus:state.focus});const n=state.graph.nodes,e=state.graph.edges;$('#node-count').textContent=n.length;$('#edge-count').textContent=e.length;$('#active-count').textContent=n.filter(x=>(x.temporalWeight||0)>.65).length;$('#focus-label').textContent=String(state.focus).replace(/^domain:/,'').slice(0,16);renderDeck();syncChrome()}
function renderDeck(){const g=state.graph;if(!g)return;const domains={};for(const n of g.nodes){const ds=n.domains?.length?n.domains:[n.domain].filter(Boolean);for(const d of ds)domains[d]=(domains[d]||0)+1}const max=Math.max(1,...Object.values(domains));$('#domain-strip').innerHTML=Object.entries(domains).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([d,c])=>`<div class="domain-row"><code>${escapeHtml(d)}</code><i style="--w:${Math.round(c/max*100)}%"></i><span>${c}</span></div>`).join('')||'<p class="trace-detail">Sem domínios explícitos neste nível.</p>';const rel={};for(const e of g.edges)rel[e.type]=(rel[e.type]||0)+1;$('#relation-strip').innerHTML=Object.entries(rel).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([t,c])=>`<div class="relation-chip"><b>${escapeHtml(t)}</b><span>${c}</span></div>`).join('')||'<p class="trace-detail">Nenhuma relação no recorte.</p>';const sourced=g.nodes.filter(n=>n.sourceRefs?.length).length,canonical=g.nodes.filter(n=>n.authority==='SCIENCE_CANONICAL').length,score=g.nodes.length?Math.round((sourced+canonical)/(g.nodes.length*2)*100):0;$('#provenance-health').innerHTML=`<div class="trace-score">${score}<small>/100</small></div><div class="trace-detail">${sourced} nós com sourceRefs<br>${canonical} nós canônicos<br>${escapeHtml(g.source||'GOOGLE_DRIVE')} · ${escapeHtml(g.freshness||'SNAPSHOT')}</div>`}
async function loadGraph({view=state.view,focus=state.focus,force=false}={}){setLoading(true,view==='provenance'?'Reconstruindo lineage…':'Lendo snapshot do Drive…');try{const graph=await getGraph({view,focus,depth:3,limit:240,force});state.view=view;state.focus=graph.focus||focus;state.rawGraph=graph;renderGraph();if(view==='macro')engine.setZoom(.72);else if(view==='scientific'&&engine.camera.zoom<.95)engine.setZoom(1.18);else if(view==='provenance'&&engine.camera.zoom<1.95)engine.setZoom(2.08);$('#source-version').textContent=`${graph.source||'GOOGLE_DRIVE'} · ${graph.freshness||'SNAPSHOT'} · ${String(graph.sourceVersion||'').slice(0,19)}`}catch(error){toast('Snapshot indisponível. Recorte anterior preservado.');console.error(error)}finally{setLoading(false)}}
async function changeView(view,{focus,manual=false,fromZoom=false}={}){if(manual)state.auto=false;syncChrome();let target=focus||state.focus;if(view==='macro')target='system:NEXO';if(view==='scientific'&&target==='system:NEXO')target='system:SCIENCE';if(view==='provenance'&&(target==='system:NEXO'||target==='system:SCIENCE')){const selected=inspector.current;if(selected)target=selected.id;else return toast('Selecione uma entidade científica para abrir provenance.')}await loadGraph({view,focus:target});if(!fromZoom&&view==='macro')state.history=['system:NEXO']}
function selectNode(node){engine.setSelected(node.id);inspector.show(node,state.graph)}
async function openNode(node){if(state.view==='macro'&&['DOMAIN','CAMPAIGN','SYSTEM','PROJECT'].includes(node.type)){state.history.push(node.id);await changeView('scientific',{focus:node.id});return}if(state.view==='scientific'&&!['SYSTEM','DOMAIN'].includes(node.type)){selectNode(node);await changeView('provenance',{focus:node.id});return}selectNode(node)}
async function health(){try{const h=await getSnapshotHealth();$('#health').textContent=h.ok?'DRIVE · LIVE SNAPSHOT':'DEGRADED';$('#health-dot').classList.toggle('bad',!h.ok);$('#source-version').textContent=`${h.semanticIndex.count.toLocaleString('pt-BR')} entidades · ${String(h.generatedAt||'').slice(0,19)}`}catch{$('#health').textContent='SNAPSHOT OFFLINE';$('#health-dot').classList.add('bad')}}
async function sync(){const b=$('#sync');b.disabled=true;b.querySelector('span').textContent='Atualizando…';try{const before=state.rawGraph?.fingerprint;clearSnapshotCache();await loadGraph({force:true});await health();const after=state.rawGraph?.fingerprint;toast(before===after?'SNAPSHOT · nenhuma alteração':'SNAPSHOT · projeção atualizada')}catch{toast('Atualização indisponível. Estado anterior preservado.')}finally{b.disabled=false;b.querySelector('span').textContent='Atualizar'}}
function searchLocal(q){const box=$('#search-results');q=q.trim().toLowerCase();if(!q){box.hidden=true;return}const hits=(state.graph?.nodes||[]).filter(n=>`${n.id} ${n.label} ${n.type} ${n.domain}`.toLowerCase().includes(q)).slice(0,12);box.innerHTML=hits.map(n=>`<button data-id="${escapeHtml(n.id)}"><small>${escapeHtml(n.visualType||n.type)}</small><b>${escapeHtml(n.label||n.id)}</b></button>`).join('')||'<p class="trace-detail">Sem resultado neste recorte.</p>';box.hidden=false;box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const n=state.graph.nodes.find(x=>x.id===b.dataset.id);if(n){box.hidden=true;$('#search').value='';selectNode(n);engine.focusSelected()}})}
$$('[data-view]').forEach(b=>b.onclick=()=>changeView(b.dataset.view,{manual:true}));$('#auto-layer').onclick=()=>{state.auto=!state.auto;syncChrome();toast(state.auto?'Semantic zoom automático ativo':'Camada fixada manualmente')};$$('[data-window]').forEach(b=>b.onclick=()=>{$$('[data-window]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.window=b.dataset.window;renderGraph()});$('#home').onclick=()=>{state.auto=true;state.history=['system:NEXO'];inspector.hide();changeView('macro')};$('#sync').onclick=sync;$('#orbit').onclick=()=>{$('#orbit').textContent=engine.toggleOrbit()?'Ⅱ':'▷'};$('#fit').onclick=()=>engine.reset();$('#center').onclick=()=>engine.focusSelected();$('#flat').onclick=()=>{$('#flat').textContent=engine.toggleFlat()?'3D':'2D'};$('#zoom-in').onclick=()=>engine.zoom(1.2);$('#zoom-out').onclick=()=>engine.zoom(.82);$('#back').onclick=()=>{if(state.view==='provenance')changeView('scientific',{focus:state.history.at(-1)||'system:SCIENCE'});else if(state.view==='scientific')changeView('macro');else history.back()};$('#search').addEventListener('input',e=>searchLocal(e.target.value));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#search-results').hidden=true;inspector.hide()}});syncChrome();await Promise.all([health(),loadGraph()]);
