import {useCallback,useEffect,useMemo,useState} from 'react';
import {AtlasCanvas} from '../scene/AtlasCanvas';
import type {AtlasGraph,AtlasNode} from '../scene/types';
import {loadAtlasV3Snapshot} from './projection-loader.mjs';
import {ATLAS_V3_PRESENTATION_ROOT,buildAtlasV3Scene} from './scene-adapter.mjs';
import type {AtlasV3Layer,AtlasV3Scene,AtlasV3Snapshot} from './types';
import {persistThemeMode, readThemeMode, resolveTheme} from './theme-mode.mjs';
import {buildHealthLayerModel} from './health-layer-model.mjs';
import './atlas-v3.css';
import './atlas-v3-theme.css';

type ThemeMode='system'|'light'|'dark';
const LAYERS:AtlasV3Layer[]=['NEXO','SCIENCE','OPERATIONS','HEALTH','AUTOMATIONS','EVIDENCES'];
const LAYER_LABELS:Record<string,string>={NEXO:'Nexo',SCIENCE:'Science',OPERATIONS:'Operations',HEALTH:'Health',AUTOMATIONS:'Automations',EVIDENCES:'Evidences'};
function useMedia(query:string){const [matches,setMatches]=useState(()=>typeof window!=='undefined'&&window.matchMedia(query).matches);useEffect(()=>{const media=window.matchMedia(query);const update=()=>setMatches(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[query]);return matches}
function short(value:unknown,max=52){const text=String(value??'');return text.length>max?`${text.slice(0,max-1)}…`:text}
function displayLabel(node?:AtlasNode|null){return short(node?.label||String(node?.id||'Sem seleção'),42)}
function layerForNode(node:AtlasNode):AtlasV3Layer{const type=String(node.type||'').toUpperCase();if(type==='FILAMENT'||type==='AUTOMATION')return'AUTOMATIONS';if(type==='WORK')return'OPERATIONS';if(type==='REFERENCE'||type==='EVIDENCE')return'EVIDENCES';return'SCIENCE'}
function connectedToTypes(graph:AtlasGraph,types:Set<string>){const seeds=new Set(graph.nodes.filter(node=>types.has(String(node.type||'').toUpperCase())).map(node=>node.id));const visible=new Set(seeds);for(const edge of graph.edges)if(seeds.has(edge.source)||seeds.has(edge.target)){visible.add(edge.source);visible.add(edge.target)}return visible}
function nodeVisibleForLayer(node:AtlasNode,layer:AtlasV3Layer,connected:Set<string>){if(node.presentationOnly)return true;const type=String(node.type||'').toUpperCase();const domain=String(node.domain||'').toUpperCase();if(layer==='NEXO')return true;if(layer==='SCIENCE')return !['WORK','REFERENCE','EVIDENCE','FILAMENT','AUTOMATION'].includes(type);if(layer==='AUTOMATIONS'||layer==='LEARNING')return connected.has(node.id)||type==='FILAMENT'||type==='AUTOMATION';if(layer==='OPERATIONS')return connected.has(node.id)||type==='WORK';if(layer==='EVIDENCES'||layer==='EVIDENCE'||layer==='PROVENANCE')return connected.has(node.id)||type==='REFERENCE'||type==='EVIDENCE';if(layer==='HEALTH')return domain.includes('OLYMPUS')||type==='SYSTEM'||type==='WORK';return true}
function graphForLayer(scene:AtlasV3Scene,layer:AtlasV3Layer):AtlasGraph{const types=layer==='AUTOMATIONS'||layer==='LEARNING'?new Set(['FILAMENT','AUTOMATION']):layer==='OPERATIONS'?new Set(['WORK']):layer==='EVIDENCES'||layer==='EVIDENCE'||layer==='PROVENANCE'?new Set(['REFERENCE','EVIDENCE']):layer==='HEALTH'?new Set(['WORK','SYSTEM']):new Set<string>();const connected=types.size?connectedToTypes(scene.graph,types):new Set(scene.graph.nodes.map(node=>node.id));const nodes=scene.graph.nodes.filter(node=>nodeVisibleForLayer(node,layer,connected));const ids=new Set(nodes.map(node=>node.id));const edges=scene.graph.edges.filter(edge=>ids.has(edge.source)&&ids.has(edge.target));return{...scene.graph,nodes,edges,visualTotal:nodes.length}}

function HealthLayerPanel({snapshot}:{snapshot:AtlasV3Snapshot}){const model=buildHealthLayerModel(snapshot);return <section className={`health-layer-panel health-layer-panel--${model.status.toLowerCase()}`} aria-label="Saúde sincronizada com Olympus"><div><span>HEALTH / OLYMPUS</span><h2>{model.label}</h2></div><strong>{model.status}</strong><dl><div><dt>Versão</dt><dd>{model.sourceVersion}</dd></div><div><dt>Registros públicos</dt><dd>{model.publicEntityCount}</dd></div><div><dt>Dados privados</dt><dd>{model.privateDataExcluded?'excluídos':'não confirmado'}</dd></div></dl><small>Leitura sanitizada autorizada pelo TOWER_V06. A aba não publica dados pessoais, clínicos ou de clientes.</small></section>}

function Inspector({node,snapshot,onClose,compact}:{node:AtlasNode|null;snapshot:AtlasV3Snapshot;onClose:()=>void;compact:boolean}){const entity=node&&!node.presentationOnly?snapshot.entities?.[node.id]:null;const kind=node?.presentationOnly?'APRESENTAÇÃO':'CANONICAL';const summary=typeof node?.summary==='string'?node.summary:typeof entity?.summary==='string'?String(entity.summary):typeof entity?.description==='string'?String(entity.description):'';const nextMove=typeof entity?.nextAction==='string'?String(entity.nextAction):typeof entity?.next_action==='string'?String(entity.next_action):'';return <aside id="atlas-v3-inspector" role={compact?'dialog':'complementary'} className="inspector-sheet is-open" aria-modal={compact?true:undefined} aria-label="Inspector do Atlas"><div className="inspector-grab" aria-hidden="true"/><header className="inspector-head"><div><span>{kind}</span><h2>{node?displayLabel(node):'Selecione um nó'}</h2></div><button className="icon-button inspector-close" type="button" onClick={onClose} aria-label="Fechar inspector">×</button></header><div className="inspector-body">{node?<><div className="inspector-grid"><span>tipo<b>{String(node.type||'—')}</b></span><span>status<b>{String(node.status||'—')}</b></span><span>domínio<b>{String(node.domain||'—')}</b></span><span>origem<b>{node.presentationOnly?'visual':'TOWER_V06'}</b></span></div>{summary&&<section className="inspector-context"><span>Resumo</span><p>{summary}</p></section>}{nextMove&&<section className="inspector-context inspector-context--next"><span>Próximo movimento</span><p>{nextMove}</p></section>}<p className="canonical-id">{node.id}</p>{entity&&<dl className="entity-fields">{Object.entries(entity).filter(([key])=>!['id','label','summary','description','nextAction','next_action'].includes(key)).slice(0,8).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{Array.isArray(value)?value.join(', '):String(value??'—')}</dd></div>)}</dl>}</>:<p className="inspector-empty">Toque ou clique em uma entidade. O painel mostra somente o que existe na projeção publicada.</p>}</div></aside>}

export type AtlasNeuralSurfaceProps={compact?:boolean;initialLayer?:AtlasV3Layer;embedded?:boolean;onOpenEntity?:(node:AtlasNode)=>void};

export function AtlasV3App({compact:compactProp,initialLayer='SCIENCE',embedded=false,onOpenEntity}:AtlasNeuralSurfaceProps={}){
  const compactMedia=useMedia('(max-width: 760px)');const compact=compactProp??compactMedia;const reducedMotion=useMedia('(prefers-reduced-motion: reduce)');const systemDark=useMedia('(prefers-color-scheme: dark)');
  const [themeMode,setThemeMode]=useState<ThemeMode>(()=>readThemeMode() as ThemeMode);const resolvedTheme:'dark'|'light'=resolveTheme(themeMode,systemDark) as 'dark'|'light';
  const [snapshot,setSnapshot]=useState<AtlasV3Snapshot|null>(null);const [scene,setScene]=useState<AtlasV3Scene|null>(null);const [layer,setLayer]=useState<AtlasV3Layer>(initialLayer);const [focusId,setFocusId]=useState(ATLAS_V3_PRESENTATION_ROOT);const [focusHistory,setFocusHistory]=useState<string[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [inspectorOpen,setInspectorOpen]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const result=await loadAtlasV3Snapshot(embedded?new URL('atlas-v3/',window.location.href).href:window.location.href);const nextScene=buildAtlasV3Scene(result.snapshot);setSnapshot(result.snapshot);setScene(nextScene);setFocusId(nextScene.focusId);setFocusHistory([]);setSelectedId(null);setInspectorOpen(false)}catch(reason){setSnapshot(null);setScene(null);setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[embedded]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{document.title='NEXO Atlas · Neural V3'},[]);useEffect(()=>{persistThemeMode(themeMode)},[themeMode]);
  const layerGraph=useMemo(()=>scene?graphForLayer(scene,layer):null,[layer,scene]);useEffect(()=>{if(layerGraph&&!layerGraph.nodes.some(node=>node.id===focusId)){setFocusId(ATLAS_V3_PRESENTATION_ROOT);setFocusHistory([])}},[focusId,layerGraph]);
  const canonicalIds=useMemo(()=>scene?.canonicalIds||new Set<string>(),[scene]);const selectedNode=useMemo(()=>scene?.graph.nodes.find(node=>node.id===selectedId)||null,[scene,selectedId]);
  const searchResults=useMemo(()=>{if(!scene||!query.trim())return[];const q=query.trim().toLocaleLowerCase('pt-BR');return scene.graph.nodes.filter(node=>canonicalIds.has(node.id)&&`${node.id} ${node.label||''} ${node.type||''} ${node.domain||''}`.toLocaleLowerCase('pt-BR').includes(q)).slice(0,8)},[canonicalIds,query,scene]);
  const focusEntity=useCallback((id:string)=>{if(!scene||!canonicalIds.has(id))return;const node=scene.graph.nodes.find(candidate=>candidate.id===id);if(!node)return;setLayer(layerForNode(node));setFocusHistory(history=>focusId===id?history:[...history,focusId].slice(-12));setFocusId(id);setSelectedId(id);setInspectorOpen(true);setSearchOpen(false);setQuery('')},[canonicalIds,focusId,scene]);
  const openNode=useCallback((node:AtlasNode)=>{if(onOpenEntity&&!node.presentationOnly)onOpenEntity(node);setFocusHistory(history=>focusId===node.id?history:[...history,focusId].slice(-12));setFocusId(node.id);setSelectedId(node.id);setInspectorOpen(compact)},[compact,focusId,onOpenEntity]);
  const selectNode=useCallback((node:AtlasNode)=>{setSelectedId(node.id);setInspectorOpen(true)},[]);const goHome=useCallback(()=>{setFocusId(ATLAS_V3_PRESENTATION_ROOT);setFocusHistory([]);setSelectedId(null);setInspectorOpen(false)},[]);const resetView=useCallback(()=>{goHome();window.dispatchEvent(new Event('atlas:reset-view'))},[goHome]);
  const goBack=useCallback(()=>{if(!focusHistory.length){setFocusId(ATLAS_V3_PRESENTATION_ROOT);setSelectedId(null);return}const previous=focusHistory[focusHistory.length-1];setFocusHistory(history=>history.slice(0,-1));setFocusId(previous);setSelectedId(previous===ATLAS_V3_PRESENTATION_ROOT?null:previous);setInspectorOpen(false)},[focusHistory]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(true);return}if(event.key==='Escape'){if(inspectorOpen){setInspectorOpen(false);return}if(searchOpen){setSearchOpen(false);setQuery('');return}if(focusId!==ATLAS_V3_PRESENTATION_ROOT)goBack()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[focusId,goBack,inspectorOpen,searchOpen]);
  const counts=snapshot?.universe?.counts||{};const statusText=error?'projeção indisponível':loading?'carregando projeção':`${snapshot?.manifest.completeness||'SNAPSHOT'} · ${snapshot?.manifest.freshness||'SNAPSHOT'}`;const liveState=loading?'SYNCING':error?'ATTENTION':'LIVE · LEARNING';
  return <main className={`atlas-v3-shell${embedded?' atlas-v3-shell--embedded spatial-knowledge-page':''}`} data-theme={resolvedTheme} data-theme-mode={themeMode} data-presentation="canvas" data-reduced-motion={reducedMotion?'true':'false'} aria-busy={loading}>
    <section className="cinematic-stage" data-testid="atlas-v3-stage" data-graph-language="neural" aria-label="Mapa neural em canvas 2.5D do NEXO" style={{touchAction:'none'}}>{layerGraph&&<AtlasCanvas graph={layerGraph} focusId={focusId} selectedId={selectedId} onSelect={selectNode} onOpen={openNode} reducedMotion={reducedMotion} compact={compact} loading={loading} theme={resolvedTheme} presentationMode="canvas"/>} {loading&&!layerGraph&&<div className="projection-state loading-state" role="status"><span className="loader-orbit"/><b>Materializando universo</b><small>TOWER_V06 → Projection V3 → Spatial Canvas</small></div>}{error&&<div className="projection-state error-state" role="alert"><b>Projeção indisponível</b><p>O Atlas não inventará um estado substituto.</p><small>{error}</small><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>}{!loading&&!error&&layerGraph&&layerGraph.nodes.length<=1&&<div className="projection-state empty-state"><b>Nenhuma entidade encontrada</b><small>Esta camada não possui entidades publicadas neste snapshot.</small></div>}{snapshot&&layer==='HEALTH'&&!loading&&!error&&<HealthLayerPanel snapshot={snapshot}/>}</section>
    <header className="top-hud glass-panel"><div className="brand-block"><span className="brand-orbit" aria-hidden="true">◎</span><div><strong>NEXO Atlas</strong><small>NEURAL V3 · SPATIAL CANVAS</small></div></div><div className="neural-state" aria-live="polite"><i className={liveState==='ATTENTION'?'attention':''}/><span><b>{liveState}</b><small>Sistema vivo em aprendizado</small></span></div><div className="theme-switch" role="group" aria-label="Tema do Atlas"><button type="button" className={themeMode==='system'?'active':''} aria-pressed={themeMode==='system'} aria-label="Usar tema do sistema" title="Automático" onClick={()=>setThemeMode('system')}>◐</button><button type="button" className={themeMode==='light'?'active':''} aria-pressed={themeMode==='light'} aria-label="Usar tema claro" title="Claro" onClick={()=>setThemeMode('light')}>☼</button><button type="button" className={themeMode==='dark'?'active':''} aria-pressed={themeMode==='dark'} aria-label="Usar tema escuro" title="Escuro" onClick={()=>setThemeMode('dark')}>☾</button></div><div className="tower-status"><i/><span><b>TOWER_V06</b><small>{statusText}</small></span></div></header>
    <div className="scene-caption" aria-live="polite"><span>{layer}</span><b>{focusId===ATLAS_V3_PRESENTATION_ROOT?'NEXO':displayLabel(scene?.graph.nodes.find(node=>node.id===focusId))}</b><small>{counts.nodes??0} nós · {counts.edges??0} relações · atividade neural em observação · fingerprint {short(snapshot?.manifest.fingerprint||'—',20)}</small></div>
    <nav className="neural-layer-bar glass-panel" role="toolbar" aria-label="Camadas neurais">{LAYERS.map(item=><button key={item} type="button" className={`layer-button layer-button--${item.toLowerCase()} ${layer===item?'active':''}`} aria-pressed={layer===item} onClick={()=>setLayer(item)}><i aria-hidden="true"/><span>{LAYER_LABELS[item]}</span></button>)}</nav>
    <div className="control-dock glass-panel" aria-label="Navegação do grafo"><button className="icon-button" type="button" onClick={goBack} disabled={!focusHistory.length&&focusId===ATLAS_V3_PRESENTATION_ROOT} aria-label="Voltar">←</button><button className="icon-button home-button" type="button" onClick={goHome} aria-label="Voltar ao NEXO">◎</button><button className="icon-button" data-testid="atlas-reset-view" type="button" onClick={resetView} aria-label="Reset view" title="Reset view">⌂</button><button className="icon-button search-trigger" type="button" onClick={()=>setSearchOpen(value=>!value)} aria-expanded={searchOpen} aria-controls="atlas-v3-search-panel" aria-label="Buscar entidade">⌕</button><button className="icon-button" type="button" onClick={()=>setInspectorOpen(value=>!value)} aria-expanded={inspectorOpen} aria-controls="atlas-v3-inspector" aria-label="Abrir inspector">◫</button></div>
    {searchOpen&&<section id="atlas-v3-search-panel" className="search-panel glass-panel is-open" aria-label="Busca no Atlas"><label htmlFor="atlas-v3-search">Buscar campanha, claim, teste ou work</label><div className="search-row"><span>⌕</span><input id="atlas-v3-search" autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar na projeção…" autoComplete="off"/><kbd>Esc</kbd></div>{query&&<div className="search-results">{searchResults.length?searchResults.map(node=><button className="search-result" type="button" key={node.id} onClick={()=>focusEntity(node.id)}><b>{displayLabel(node)}</b><small>{String(node.type||'—')} · {String(node.status||'—')}</small></button>):<p>Nenhuma entidade encontrada.</p>}</div>}</section>}
    {snapshot&&inspectorOpen&&<Inspector node={selectedNode} snapshot={snapshot} compact={compact} onClose={()=>setInspectorOpen(false)}/>} 
    <footer className="runtime-strip"><span>NAVEGAR: arrastar · ZOOM: roda/pinça · PAN: botão direito/dois dedos · PROFUNDIDADE: leve</span><span>{snapshot?.manifest.sourceVersion||'aguardando Tower'}</span></footer>
  </main>
}
