const ATLAS={schema:'nexo-atlas-snapshot/v1',repo:'byDenoso/Pantheon',branch:'main',root:'atlas-control-tower/data',tower:'1Y9YYAn2x0NDIBTbl1bvkwBbSEGz6kHLxzAl90SQ0-GA',learning:'1to_VBC5edy3kHbkn4CDjG2r33tr0jdtky2Ie80afbEI',ops:'1twRpSoZCOXv77YyCh_5V9nAS2PM2nqzex2A37eI2Zas',olympus:'1qj7VyA7wN3zr6ySZZ9kxHi4Szt99IV5Hf3jRWJAykLM',stateIndex:'1iBa4iFe2nNPtSLAhoMjy5a5WPNwm0hgJeoNmyexl0Qs'};

function syncAtlas(){const lock=LockService.getScriptLock();if(!lock.tryLock(5000))return{state:'LOCKED'};try{const compiled=compileAtlasProjection(),current=readGitHubSnapshot_('atlas.json');if(current&&current.fingerprint===compiled.fingerprint){PropertiesService.getScriptProperties().setProperty('LAST_ATLAS_FINGERPRINT',compiled.fingerprint);return{state:'NO_OP',fingerprint:compiled.fingerprint}}const out=syncAtlasToGitHub(compiled);PropertiesService.getScriptProperties().setProperties({LAST_ATLAS_FINGERPRINT:compiled.fingerprint,LAST_ATLAS_COMMIT:out.commitSha,LAST_ATLAS_SYNC_AT:new Date().toISOString()},false);return{state:'UPDATED',fingerprint:compiled.fingerprint,commitSha:out.commitSha}}finally{lock.releaseLock()}}

function compileAtlasProjection(){const tower=SpreadsheetApp.openById(ATLAS.tower),learning=SpreadsheetApp.openById(ATLAS.learning),ops=SpreadsheetApp.openById(ATLAS.ops);const nodes=[],edges=[],seen={};const add=n=>{if(n&&n.id&&!seen[n.id]){seen[n.id]=1;nodes.push(n)}};const edge=(s,t,type='CONTAINS',authority='DRIVE')=>{if(s&&t)edges.push({source:s,target:t,type,authority})};
add(node_('system:NEXO','SYSTEM','NEXO',null,null,'ACTIVE'));add(node_('system:SCIENCE','SYSTEM','Science','system:NEXO','SCIENCE','ACTIVE'));add(node_('system:LEARNING','SYSTEM','Learning','system:NEXO','LEARNING','ACTIVE'));add(node_('system:OPERATIONS','SYSTEM','Operations','system:NEXO','OPERATIONS','ACTIVE'));add(node_('system:OLYMPUS','PROJECT','Olympus','system:NEXO','OLYMPUS','ACTIVE'));['system:SCIENCE','system:LEARNING','system:OPERATIONS','system:OLYMPUS'].forEach(id=>edge('system:NEXO',id));
const campaignForTest={};readTable_(tower,'SCIENTIFIC_CAMPAIGNS').forEach(r=>{const raw=pick_(r,['campaign_id','Campaign ID']);if(!raw)return;const domain=pick_(r,['domain','Domain'])||'UNSCOPED',did='domain:'+token_(domain),cid='campaign:'+raw;add(node_(did,'DOMAIN',domain,'system:SCIENCE',domain,'ACTIVE'));edge('system:SCIENCE',did);const n=node_(cid,'CAMPAIGN',pick_(r,['campaign_name','Campaign Name'])||raw,did,domain,pick_(r,['status','State'])||'UNKNOWN');n.summary=pick_(r,['scientific_question','Scientific Question'])||'';n.scientificQuestion=n.summary;n.currentVerdict=pick_(r,['current_verdict'])||'';n.nextValidAction=pick_(r,['next_valid_action'])||'';n.activityAt=pick_(r,['updated_at'])||'';n.authority='DERIVED_NAVIGATION';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','SCIENTIFIC_CAMPAIGNS',raw)];add(n);edge(did,cid);split_(pick_(r,['test_ids[]','test_ids','Test IDs'])).forEach(t=>{if(!campaignForTest[t])campaignForTest[t]=cid})});
readTable_(tower,'CLAIMS').forEach(r=>{const raw=pick_(r,['claim_id','Claim ID']);if(!raw)return;const domain=pick_(r,['scope','Scope'])||'UNSCOPED',did='domain:'+token_(domain);add(node_(did,'DOMAIN',domain,'system:SCIENCE',domain,'ACTIVE'));edge('system:SCIENCE',did);const n=node_('claim:'+raw,'CLAIM',pick_(r,['statement','Statement'])||raw,did,domain,pick_(r,['status','Status'])||'UNKNOWN');n.summary=pick_(r,['statement','Statement'])||'';n.nextAction=pick_(r,['next_falsifier'])||'';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','CLAIMS',raw)];add(n);edge(did,n.id)});
const hypothesisForTest={};readTable_(tower,'Hypothesis Registry').forEach(r=>{const raw=pick_(r,['Hypothesis ID','hypothesis_id']);if(!raw)return;const test=pick_(r,['Primary Test ID','primary_test_id'])||'',domain=pick_(r,['Domain','domain'])||'UNSCOPED',parent=campaignForTest[test]||'domain:'+token_(domain);add(node_('domain:'+token_(domain),'DOMAIN',domain,'system:SCIENCE',domain,'ACTIVE'));edge('system:SCIENCE','domain:'+token_(domain));const n=node_('hypothesis:'+raw,'HYPOTHESIS',pick_(r,['Hypothesis','statement'])||raw,parent,domain,pick_(r,['State','status'])||'UNKNOWN');n.summary=pick_(r,['Hypothesis','statement'])||'';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','Hypothesis Registry',raw)];add(n);edge(parent,n.id);if(test){hypothesisForTest[test]=n.id;edge(n.id,'test:'+test,'PRIMARY_TEST','EXPLICIT_DRIVE_FIELD')}});
readTable_(tower,'Test Registry').forEach(r=>{const raw=pick_(r,['Test ID','test_id']);if(!raw)return;const domain=pick_(r,['Lane','Domain','domain'])||'UNSCOPED',parent=hypothesisForTest[raw]||campaignForTest[raw]||'domain:'+token_(domain);add(node_('domain:'+token_(domain),'DOMAIN',domain,'system:SCIENCE',domain,'ACTIVE'));const n=node_('test:'+raw,'TEST',pick_(r,['Test / Question','Test','Question'])||raw,parent,domain,pick_(r,['Status'])||'UNKNOWN');n.summary=pick_(r,['Result Summary'])||'';n.nextAction=pick_(r,['Next Gate'])||'';n.activityAt=pick_(r,['Last Verified'])||'';n.authority='SCIENCE_CANONICAL';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','Test Registry',raw),ref_('GOOGLE_DRIVE','Drive Source',pick_(r,['Drive Source']))].filter(x=>x.sourceId);add(n);edge(parent,n.id)});
const env={};readTable_(tower,'Result Envelopes').forEach(r=>{const eid=pick_(r,['Envelope ID']),tid=pick_(r,['Test ID']),f=pick_(r,['Field']),v=pick_(r,['Value']);if(!eid||!tid||!f)return;if(!env[eid])env[eid]={testId:tid,fields:{}};env[eid].fields[f]=v});Object.keys(env).forEach(eid=>{const e=env[eid],status=e.fields.STATUS||e.fields.status||e.fields.VERDICT||'RECORDED',summary=e.fields.RESULT_SUMMARY||e.fields.result_summary||e.fields.summary||e.fields.TEST_INTENT||'';const n=node_('result:'+eid,'RESULT',eid,'test:'+e.testId,null,status);n.summary=summary;n.fields=e.fields;n.authority='SCIENCE_CANONICAL';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','Result Envelopes',eid)];add(n);edge('test:'+e.testId,n.id,'PRODUCES_RESULT','SCIENCE_CANONICAL')});
readTable_(tower,'Sources').forEach((r,i)=>{const name=pick_(r,['Name','name']),url=pick_(r,['URL','url']);if(!name&&!url)return;const n=node_('source:'+token_(url||name),'SOURCE',name||url,'system:SCIENCE',null,pick_(r,['Trust / State'])||'KNOWN');n.url=url||'';n.summary=pick_(r,['Role'])||'';n.sourceRefs=[ref_('PEER_CONTROL_TOWER_CANONICAL','Sources',String(i+2))];add(n)});
const learningRows=[...readTable_(learning,'STRATEGY_REGISTRY').map(r=>({...r,_kind:'STRATEGY'})),...readTable_(learning,'PROCEDURAL_MEMORY').map(r=>({...r,_kind:'PROCEDURAL_MEMORY'})),...readTable_(learning,'ADAPTIVE_POLICY').map(r=>({...r,_kind:'ADAPTIVE_POLICY'}))];const operations=[...readTable_(ops,'ACTION_INDEX').map(r=>({...r,_kind:'ACTION'})),...readTable_(ops,'EXECUTION_RUNS').map(r=>({...r,_kind:'EXECUTION_RUN'}))];const atlas={nodes:nodes.sort((a,b)=>a.id.localeCompare(b.id)),edges:dedupeEdges_(edges),activity:[],learning:learningRows,operations,olympus:{sourceId:ATLAS.olympus,mode:'truth-owner-pointer'},systemState:{sourceId:ATLAS.stateIndex,mode:'truth-owner-pointer'}};const lineage=buildLineage_(atlas),presentation=buildPresentation_(atlas),fingerprint=sha256Hex_(canonicalJson_({atlas,lineage,presentation})),generatedAt=new Date().toISOString();return{fingerprint,generatedAt,atlas:envelope_(generatedAt,fingerprint,atlas),lineage:envelope_(generatedAt,fingerprint,lineage),presentation:envelope_(generatedAt,fingerprint,presentation)}}

function syncAtlasToGitHub(compiled){const p=PropertiesService.getScriptProperties(),token=p.getProperty('NEXO_GITHUB_TOKEN');if(!token)throw new Error('Missing Script Property NEXO_GITHUB_TOKEN');const branch=p.getProperty('ATLAS_GITHUB_BRANCH')||ATLAS.branch,ref=gh_('GET','/git/ref/heads/'+encodeURIComponent(branch),null,token),head=ref.object.sha,commit=gh_('GET','/git/commits/'+head,null,token),treeItems=[];[['atlas.json',compiled.atlas],['lineage.json',compiled.lineage],['presentation.json',compiled.presentation]].forEach(x=>{const blob=gh_('POST','/git/blobs',{content:JSON.stringify(x[1],null,2)+'\n',encoding:'utf-8'},token);treeItems.push({path:ATLAS.root+'/'+x[0],mode:'100644',type:'blob',sha:blob.sha})});const tree=gh_('POST','/git/trees',{base_tree:commit.tree.sha,tree:treeItems},token),next=gh_('POST','/git/commits',{message:'data(atlas): compile Drive snapshot '+compiled.fingerprint.slice(0,12),tree:tree.sha,parents:[head]},token);gh_('PATCH','/git/refs/heads/'+encodeURIComponent(branch),{sha:next.sha,force:false},token);const rb=readGitHubSnapshot_('atlas.json',next.sha);if(!rb||rb.fingerprint!==compiled.fingerprint)throw new Error('GitHub readback fingerprint mismatch');return{commitSha:next.sha,branch,fingerprint:compiled.fingerprint}}
function installAtlasTrigger(){ScriptApp.getProjectTriggers().forEach(t=>{if(t.getHandlerFunction()==='syncAtlas')ScriptApp.deleteTrigger(t)});ScriptApp.newTrigger('syncAtlas').timeBased().everyMinutes(15).create();return{state:'INSTALLED',everyMinutes:15}}
function readGitHubSnapshot_(name,refOverride){const p=PropertiesService.getScriptProperties(),token=p.getProperty('NEXO_GITHUB_TOKEN');if(!token)return null;const ref=refOverride||p.getProperty('ATLAS_GITHUB_BRANCH')||ATLAS.branch;try{const out=gh_('GET','/contents/'+ATLAS.root+'/'+name+'?ref='+encodeURIComponent(ref),null,token),raw=Utilities.newBlob(Utilities.base64Decode(String(out.content||'').replace(/\s/g,''))).getDataAsString('UTF-8'),parsed=JSON.parse(raw);return{fingerprint:parsed.fingerprint,envelope:parsed}}catch(e){return null}}
function gh_(method,path,payload,token){const r=UrlFetchApp.fetch('https://api.github.com/repos/'+ATLAS.repo+path,{method:method.toLowerCase(),muteHttpExceptions:true,contentType:'application/json',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'NEXO-Atlas-Compiler'},payload:payload==null?undefined:JSON.stringify(payload)}),code=r.getResponseCode(),txt=r.getContentText();if(code<200||code>=300)throw new Error('GitHub '+code+' '+path+' '+txt.slice(0,500));return txt?JSON.parse(txt):{}}
function readTable_(book,name){const s=book.getSheetByName(name);if(!s)return[];const rows=Math.min(s.getLastRow(),12000),cols=Math.min(s.getLastColumn(),64);if(rows<1||cols<1)return[];const v=s.getRange(1,1,rows,cols).getDisplayValues();let h=0;while(h<v.length&&v[h].filter(Boolean).length<2)h++;if(h>=v.length)return[];const heads=v[h].map((x,i)=>String(x||('COL_'+(i+1))).trim());return v.slice(h+1).filter(r=>r.some(x=>String(x).trim())).map(r=>{const o={};heads.forEach((k,i)=>o[k]=r[i]??'');return o})}
function buildLineage_(a){const parent={},children={},provenance={};a.nodes.forEach(n=>{if(n.parentId){parent[n.id]=n.parentId;(children[n.parentId]||(children[n.parentId]=[])).push(n.id)}if(n.sourceRefs&&n.sourceRefs.length)provenance[n.id]=n.sourceRefs});return{parent,children,relations:a.edges,provenance}}
function buildPresentation_(a){const by={};a.nodes.forEach(n=>{if(n.parentId)(by[n.parentId]||(by[n.parentId]=[])).push(n)});const stories={};a.nodes.filter(n=>n.type==='CAMPAIGN').forEach(c=>{const d=desc_(c.id,by);stories[c.id]={topic:c.label,question:c.scientificQuestion||c.summary||'',currentState:c.currentVerdict||c.status,hypotheses:d.filter(n=>['HYPOTHESIS','CLAIM'].includes(n.type)),tests:d.filter(n=>n.type==='TEST'),results:d.filter(n=>n.type==='RESULT'),changes:[],evidence:d.filter(n=>n.sourceRefs&&n.sourceRefs.length).map(n=>({id:n.id,sourceRefs:n.sourceRefs})),uncertainties:[],nextActions:[c.nextValidAction].filter(Boolean)}});return{stories}}
function desc_(id,by){const out=[],q=[...(by[id]||[])],seen={};while(q.length){const n=q.shift();if(seen[n.id])continue;seen[n.id]=1;out.push(n);q.push(...(by[n.id]||[]))}return out}
function node_(id,type,label,parentId,domain,status){return{id,type,visualType:type,label:String(label||id),parentId:parentId||null,domain:domain||null,status:status||'UNKNOWN',summary:'',sourceRefs:[]}}
function ref_(source,sourceRef,sourceId){return{source,sourceRef,sourceId:String(sourceId||'')}}function envelope_(generatedAt,fingerprint,data){return{schemaVersion:ATLAS.schema,generatedAt,source:'GOOGLE_DRIVE',fingerprint,data}}
function pick_(r,names){for(const n of names)if(Object.prototype.hasOwnProperty.call(r,n)&&String(r[n]).trim())return r[n];const map={};Object.keys(r).forEach(k=>map[norm_(k)]=r[k]);for(const n of names){const v=map[norm_(n)];if(v!=null&&String(v).trim())return v}return''}
function split_(v){return String(v||'').split(/\s*\|\s*|\s*,\s*|\n+/).map(x=>x.trim()).filter(Boolean)}function token_(v){return String(v||'').trim().replace(/^https?:\/\//i,'').replace(/[^A-Za-z0-9._:-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,120)||'UNKNOWN'}function norm_(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function dedupeEdges_(e){const s={};return e.filter(x=>{const k=x.source+'|'+x.target+'|'+x.type;if(s[k])return false;s[k]=1;return true}).sort((a,b)=>(a.source+'|'+a.target+'|'+a.type).localeCompare(b.source+'|'+b.target+'|'+b.type))}
function canonicalJson_(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonicalJson_).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonicalJson_(v[k])).join(',')+'}'}
function sha256Hex_(text){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8).map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('')}
