import {rows,mergeGraph,CANON,DERIVED,safeUrl,automationKind} from './model.mjs';
const PEER='1Y9YYAn2x0NDIBTbl1bvkwBbSEGz6kHLxzAl90SQ0-GA';
const names={D0:'Research OS',D1:'H₀ · Acoustic ruler',D2:'Growth · LSS',D3:'Dark energy',D4:'Dark matter · Galaxies',D5:'High-z galaxies',D6:'High-z SMBH',D7:'CMB · Systematics',D8:'Microphysics',D9:'Particle dark matter',D10:'AGN · Compact sources',CROSS:'Cross-probe'};
const ids=s=>String(s||'').match(/(?:T-[A-Za-z0-9_+≈.\-]+|DH-[A-Za-z0-9_.\-]+|H[A-Za-z0-9_\-]+)/g)||[];
function domainKey(v){const codes=[...new Set(String(v||'').match(/\bD(?:10|[0-9])\b/g)||[])];return codes.length>1?'CROSS':codes.length===1?codes[0]:v==='CROSS'?'CROSS':'UNMAPPED'}
export function adapt(raw={},ops=null){const nodes=new Map(),edges=[],campaignTests=new Map();
function add(n){if(n.id&&!n.id.includes('#REF!'))nodes.set(n.id,{authority:DERIVED,status:'',...n});return n.id}
function edge(source,target,type='CONTAINS',authority=DERIVED,extra={}){edges.push({id:`${source}:${type}:${target}`,source,target,type,authority,...extra})}
function ref(sheet,row,file=PEER){return{source:'GOOGLE_SHEETS',sourceId:file,sourceRef:`${sheet}!A${row}`,url:`https://docs.google.com/spreadsheets/d/${file}/edit`,row}}
function domain(d='UNMAPPED'){d=domainKey(d);const id='domain:'+d;if(!nodes.has(id)){add({id,type:'DOMAIN',label:names[d]||d,domain:d,summary:d==='UNMAPPED'?'Domínio não resolvido na fonte.':'Agrupamento de navegação; o estado pertence às entidades.'});edge('system:SCIENCE',id)}return id}
add({id:'system:NEXO',type:'SYSTEM',label:'NEXO',summary:'Unified Cognitive Infrastructure · Atlas é uma projeção de navegação.'});for(const [id,label]of [['SCIENCE','Science'],['ENGINEERING','Engineering'],['OLYMPUS','Olympus'],['AUTOMATION','Black Box'],['LEARNING','Learning'],['ARTIFACTS','Arquivos']]){add({id:'system:'+id,type:'SYSTEM',label});edge('system:NEXO','system:'+id)}
for(const r of rows(raw['Test-Registry']||[],0,'Test ID')){const d=domainKey(r.Lane),id='test:'+r['Test ID'];add({id,type:'TEST',label:r['Test ID'],summary:r['Test / Question'],domain:d,status:r.Status,authority:CANON,updatedAt:r['Last Verified'],sourceRefs:[ref('Test Registry',r._row)],metadata:r});edge(domain(d),id);}
for(const r of rows(raw.SCIENTIFIC_CAMPAIGNS||[],0,'campaign_id')){const id='campaign:'+r.campaign_id,d=domainKey(r.domain),ts=String(r['test_ids[]']||'').split(/\s*\|\s*/);add({id,type:'CAMPAIGN',label:r.campaign_name||r.campaign_id,domain:d,status:r.status,summary:r.scientific_question,updatedAt:r.updated_at,sourceRefs:[ref('SCIENTIFIC_CAMPAIGNS',r._row)],metadata:r});edge(domain(d),id);for(const t of ts){edge(id,'test:'+t);if(!campaignTests.has(t))campaignTests.set(t,[]);campaignTests.get(t).push(id)}}
for(const [sheet,key,kind]of [['Hypothesis-Registry','Hypothesis ID','HYPOTHESIS'],['Decision-Hypotheses','Hypothesis ID','DECISION_CLAIM']])for(const r of rows(raw[sheet]||[],0,key)){const id='claim:'+r[key],d=domainKey(r.Domain||r['Domínio']);add({id,type:'CLAIM',subtype:kind,label:r[key],domain:d,status:r.State||r['Scientific State'],summary:r.Hypothesis||r['Hipótese decisória'],authority:CANON,updatedAt:r['Last Updated']||r['Última revisão'],sourceRefs:[ref(sheet.replaceAll('-',' '),r._row)],metadata:r});edge(domain(d),id);const ts=kind==='HYPOTHESIS'?[r['Primary Test ID']]:ids(r['Evidência pró']);for(const t of ts.filter(Boolean)){if(nodes.has('test:'+t)){edge(id,'test:'+t,'TESTS',CANON,{sourceRefs:[ref(sheet.replaceAll('-',' '),r._row)]});for(const c of campaignTests.get(t)||[])edge(c,id,'CONTAINS',DERIVED)}}}
const envelopes=new Map();for(const r of rows(raw['Result-Envelopes']||[],0,'Envelope ID')){if(!envelopes.has(r['Envelope ID']))envelopes.set(r['Envelope ID'],{test:r['Test ID'],fields:{},row:r._row});envelopes.get(r['Envelope ID']).fields[r.Field]=r.Value}for(const[id,e]of envelopes){add({id:'result:'+id,type:'RESULT',label:id,authority:CANON,status:e.fields.status||e.fields.outcome||'',summary:e.fields.TEST_INTENT||e.fields.result_summary||'',sourceRefs:[ref('Result Envelopes',e.row)],metadata:e.fields});edge('test:'+e.test,'result:'+id,'PRODUCES',CANON)}
for(const r of rows(raw['Campaign-Runs']||[],0,'Campaign ID')){const id='run:'+r['Campaign ID'];add({id,type:'RUN',label:r['Campaign ID'],status:r.State,summary:r.Notes,authority:'OPERATIONAL_CANONICAL',updatedAt:r['Last Verified'],sourceRefs:[ref('Campaign Runs',r._row)],metadata:r});for(const t of ids(r['Active Test IDs']))edge('test:'+t,id,'EXECUTED_AS',CANON)}
for(const r of rows(raw['Input-Catalog']||[],0,'Asset ID')){const id='asset:'+r['Asset ID'];add({id,type:/DATASET/.test(r['Asset Class'])?'DATASET':'ARTIFACT',label:r.Name||r['Asset ID'],summary:r['Asset Class'],authority:CANON,sourceRefs:[ref('Input Catalog',r._row)],metadata:r});edge('system:ARTIFACTS',id)}
// File entities come only from explicit HTTPS URLs or labelled artifact IDs.
for(const n of [...nodes.values()]){const txt=JSON.stringify(n.metadata||{}),links=[...txt.matchAll(/https:\/\/[^\s"<>\\]+/g)].map(x=>safeUrl(x[0].replace(/[),.;]+$/,''))).filter(Boolean);const labelled=[...txt.matchAll(/(?:artifact=|Drive (?:ID|file)[:=]\s*)([A-Za-z0-9_-]{25,})/gi)].map(x=>`https://drive.google.com/file/d/${x[1]}/view`);for(const url of new Set([...links,...labelled])){const id='file:'+url;if(!nodes.has(id))add({id,type:'FILE',label:decodeURIComponent(new URL(url).pathname.split('/').filter(Boolean).slice(-2).join('/')).slice(0,100)||new URL(url).hostname,url,authority:n.authority,sourceRefs:n.sourceRefs});edge(n.id,id,'PRODUCES',n.authority)}}
for(const r of rows(raw.Learning||[],0,'relation_id')){const id='learning:'+r.relation_id;add({id,type:'LEARNING_RELATION',label:r.relation_type,summary:r.notes,status:r.status,domain:r.domain_a,authority:DERIVED,confidence:Number(String(r.confidence).replace(',','.')),updatedAt:r.last_seen,sourceRefs:[ref('RELATION_LEDGER',r._row,'1to_VBC5edy3kHbkn4CDjG2r33tr0jdtky2Ie80afbEI')],metadata:r});edge('system:LEARNING',id);for(const field of ['node_a','node_b']){const target='concept:'+r[field];add({id:target,type:'CONCEPT',label:r[field],authority:DERIVED,summary:'Conceito explicitamente registrado no learning; não é um claim científico.'});edge(id,target,r.relation_type,DERIVED,{confidence:Number(String(r.confidence).replace(',','.')),reason:r.notes})}}
for(const name of ['NEXO Continuity','NEXO Scientific Core','NEXO Executor']){add({id:'automation:'+name,type:'AUTOMATION',label:name,summary:'Arquitetura registrada no STATE_INDEX; ativação atual depende do provider.',authority:'OPERATIONAL_CANONICAL'});edge('system:AUTOMATION','automation:'+name)}
for(const e of ops?.model?.events||[]){const kind=automationKind(e.actor||''),name=/continuity/i.test(e.actor)?'NEXO Continuity':/scientific core/i.test(e.actor)?'NEXO Scientific Core':/executor/i.test(e.actor)?'NEXO Executor':e.actor||'Outro';const aid='automation:'+name;if(!nodes.has(aid)){add({id:aid,type:'AUTOMATION',label:name,status:kind==='LEGACY'?'LEGACY':'',authority:DERIVED});edge('system:AUTOMATION',aid)}const id='event:'+e.id;add({id,type:'AUTOMATION_RUN',label:e.runId||e.id,status:e.rawStatus||e.status,domain:e.domain,summary:e.outcome||e.blocker,updatedAt:e.timestamp,authority:DERIVED,sourceRefs:e.provenance?[e.provenance]:[],metadata:e});edge(aid,id,'EXECUTED_AS');if(['ENGINEERING','OLYMPUS'].includes(e.domain))edge('system:'+e.domain,id)}
return mergeGraph({nodes:[...nodes.values()],edges})}
