export const CANON='SCIENCE_CANONICAL', DERIVED='DERIVED_NOT_EVIDENCE';
export function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null}catch{return null}}
export function rows(values,header=0,key){const names=values[header]||[];return values.slice(header+1).map((r,i)=>({r,row:i+header+2})).filter(({r})=>r.some(Boolean)&&(!key||(r[names.indexOf(key)]&&!String(r[names.indexOf(key)]).startsWith('#')))).map(({r,row})=>Object.assign(Object.fromEntries(names.map((n,j)=>[n,r[j]??''])),{_row:row}))}
export function automationKind(name){return /journal|guardian/i.test(name)?'LEGACY':/continuity|scientific core|executor/i.test(name)?'CURRENT':'OTHER'}
export function state(status=''){const s=String(status).toUpperCase();if(/NEGATIVE|KILLED|CONTRADICT/.test(s))return'negative';if(/SUPERSEDED|RETIRED|LEGACY/.test(s))return'legacy';if(/BLOCKED|FAIL|ERROR/.test(s))return'blocked';if(/PARTIAL|CONDITIONAL|CHECKPOINT|DEFERRED/.test(s))return'partial';if(/PASS|COMPLETE|SUPPORTED|SURVIVES/.test(s))return'supported';if(/ACTIVE|RUNNING|READY|OPEN/.test(s))return'active';return'unknown'}
export function matches(n,f={}){if(f.type&&n.type!==f.type)return false;if(f.domain&&n.domain!==f.domain&&!n.domains?.includes(f.domain))return false;if(f.authority&&n.authority!==f.authority)return false;if(f.status&&state(n.status)!==f.status)return false;if(f.since&&(!n.updatedAt||n.updatedAt<f.since))return false;return String(f.query||'').toLowerCase().split(/\s+/).filter(Boolean).every(q=>`${n.id} ${n.label} ${n.domain||''} ${n.summary||''} ${n.status||''}`.toLowerCase().includes(q))}
export function mergeGraph(...graphs){const nodes=new Map(),edges=new Map(),issues=[];const rank=x=>x===CANON?3:x==='OPERATIONAL_CANONICAL'?2:1;for(const g of graphs){for(const n of g.nodes||[]){const old=nodes.get(n.id);if(!old||rank(n.authority)>rank(old.authority)||rank(n.authority)===rank(old.authority))nodes.set(n.id,old?.authority===CANON&&n.authority!==CANON?old:n)}for(const e of g.edges||[])edges.set(e.id||`${e.source}:${e.type}:${e.target}`,e)}for(const [id,e]of edges)if(!nodes.has(e.source)||!nodes.has(e.target)){issues.push({id,reason:'UNRESOLVED_ENDPOINT'});edges.delete(id)}return{nodes:[...nodes.values()],edges:[...edges.values()],issues}}
export function traverse(g,id,direction='neighbors',limit=20000,types){const seen=new Set([id]),queue=[id],adj=new Map();for(const e of g.edges){if(types&&!types.includes(e.type))continue;const pairs=direction==='ancestors'?[[e.target,e.source]]:direction==='descendants'?[[e.source,e.target]]:[[e.source,e.target],[e.target,e.source]];for(const[a,b]of pairs){if(!adj.has(a))adj.set(a,[]);adj.get(a).push(b)}}while(queue.length&&seen.size<limit){for(const n of adj.get(queue.shift())||[])if(!seen.has(n)){seen.add(n);if(direction!=='neighbors')queue.push(n)}}return[...seen]}
export function critical(g,id){const allowed=['DEPENDS_ON','BLOCKS','CONTAINS','TESTS','EXECUTED_AS','PRODUCES'];const reachable=traverse(g,id,'neighbors',20000,allowed),keep=new Set([id]);const all=traverse(g,id,'descendants',20000,allowed);for(const n of g.nodes)if((all.includes(n.id)||reachable.includes(n.id))&&state(n.status)==='blocked'){keep.add(n.id);for(const p of traverse(g,n.id,'ancestors',20000,allowed))if(all.includes(p))keep.add(p)}return[...keep]}
function stable(x){if(Array.isArray(x))return x.map(stable);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])]));return x}
export function fingerprint(g){let h=2166136261;const s=JSON.stringify(stable({nodes:[...(g.nodes||[])].sort((a,b)=>a.id.localeCompare(b.id)),edges:[...(g.edges||[])].sort((a,b)=>String(a.id).localeCompare(String(b.id)))}));for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(16)}
export function subgraph(g,{focus='system:NEXO',mode='children',limit=160,offset=0,depth=1,...filters}={}){if(mode==='children'&&Number(depth)>1)return layeredSubgraph(g,{focus,depth,limit,filters});let ids;if(mode==='critical')ids=new Set(critical(g,focus));else if(['ancestors','descendants','neighbors','lineage'].includes(mode))ids=new Set(traverse(g,focus,mode==='lineage'?'neighbors':mode));else ids=new Set([focus,...g.edges.filter(e=>e.source===focus&&['CONTAINS','TESTS','PRODUCES','EXECUTED_AS','DERIVED_FROM'].includes(e.type)).map(e=>e.target)]);let all=g.nodes.filter(n=>(mode==='search'||ids.has(n.id))&&matches(n,filters));const ft=g.nodes.find(n=>n.id===focus)?.type;if(mode==='children'&&ft==='DOMAIN'&&!filters.type&&all.some(n=>n.type==='CAMPAIGN'))all=all.filter(n=>n.id===focus||n.type==='CAMPAIGN');const order={SYSTEM:0,DOMAIN:1,CAMPAIGN:2,CLAIM:3,TEST:4,RUN:5,RESULT:6};all.sort((a,b)=>(a.id===focus?-1:b.id===focus?1:(order[a.type]??7)-(order[b.type]??7)));const total=all.length;let nodes=all.slice(Number(offset),Number(offset)+Math.min(Number(limit)||160,250));const focal=g.nodes.find(n=>n.id===focus);if(focal&&!nodes.some(n=>n.id===focus)&&mode!=='search')nodes.unshift(focal);const selected=new Set(nodes.map(n=>n.id));return{nodes:nodes.map(({metadata,...n})=>({...n,summary:n.summary?.slice(0,280)})),edges:g.edges.filter(e=>selected.has(e.source)&&selected.has(e.target)),total,hasMore:Number(offset)+nodes.length<total}}

/** Bounded Tower-edge expansion; breadth-balanced previews preserve every displayed parent. */
export function layeredSubgraph(g,{focus,depth=3,limit=120,filters={}}){
 const maxDepth=Math.max(1,Math.min(3,Math.floor(Number(depth)||1))),cap=Math.max(1,Math.min(250,Number(limit)||120));
 const byId=new Map(g.nodes.map(n=>[n.id,n])),adj=new Map(),allowed=new Set(['CONTAINS','TESTS','PRODUCES','EXECUTED_AS','DERIVED_FROM']);
 for(const e of g.edges)if(allowed.has(e.type)&&byId.has(e.target)){if(!adj.has(e.source))adj.set(e.source,[]);adj.get(e.source).push(e.target)}
 if(!byId.has(focus))return{nodes:[],edges:[],total:0,hasMore:false,depth:maxDepth};
 const levels=new Map([[focus,0]]),parents=new Map();let frontier=[focus],truncated=false;
 for(let layer=1;layer<=maxDepth&&frontier.length;layer++){
  const next=[];const lists=frontier.map(id=>[id,[...new Set(adj.get(id)||[])].filter(n=>!levels.has(n)&&matches(byId.get(n),filters))]);
  // Round-robin across parents avoids one large registry consuming the whole view.
  for(let i=0;i<8;i++)for(const [parent,children]of lists){const id=children[i];if(!id||levels.has(id))continue;if(levels.size>=cap){truncated=true;continue}levels.set(id,layer);parents.set(id,parent);next.push(id)}
  if(lists.some(([,list])=>list.length>8))truncated=true;frontier=next;
 }
 return{nodes:[...levels].map(([id,layer])=>{const{metadata,...n}=byId.get(id);return{...n,summary:n.summary?.slice(0,280),layer,layoutParent:parents.get(id)}}),edges:g.edges.filter(e=>levels.has(e.source)&&levels.has(e.target)),total:levels.size,hasMore:false,depth:maxDepth,truncated};
}
