import {createHash} from 'node:crypto';

export const TOOL_NAME='nexo_submit_scientific_tests_v1';
export const BOOTSTRAP_TOOL_NAME='nexo.get_bootstrap';
export const CAPABILITIES_TOOL_NAME='nexo.get_capabilities';
const PUBLIC_DISCOVERY_TOOLS=new Set([BOOTSTRAP_TOOL_NAME,CAPABILITIES_TOOL_NAME]);
const PRIVATE_SEMANTIC_TOOLS=Object.freeze([
  'nexo.status','nexo.get_state','nexo.get_work','nexo.get_next_work','nexo.get_mutation',
  'nexo.get_hypotheses','nexo.get_hypothesis','nexo.get_hypothesis_frontier','nexo.validate_hypothesis_contract','nexo.ingest_hypothesis',
  'nexo.create_work','nexo.ingest_request','nexo.ingest_objective','nexo.handoff_work','nexo.start_work','nexo.submit_result','nexo.block_work','nexo.complete_work',
  'nexo.prepare_campaign','nexo.prepare_batteries','nexo.compose_scientific_battery','nexo.submit_scientific_tests','nexo.run_work','nexo.run_campaign','nexo.run_batteries','nexo.reconcile_work','nexo.readback','nexo.get_evidence','nexo.get_campaigns','nexo.get_campaign','nexo.get_request_readback','nexo.get_roadmaps','nexo.get_roadmap','nexo.get_next_roadmap_test','nexo.get_interdomain',
  'nexo.observe_health_issue','nexo.start_health_repair','nexo.resolve_health_issue','nexo.cleanup_repository_branches'
]);
const PRIVATE_SEMANTIC_SET=new Set(PRIVATE_SEMANTIC_TOOLS);
const DEFAULT_GROUP='TEST_GROUP::ADHOC::CHAT-SCIENCE';
const TERMINAL=new Set(['VERIFIED','DONE','FAILED','INCONCLUSIVE','SUPERSEDED']);
const ACTIVE=new Set(['READY','QUEUED','DISPATCHED','RUNNING','CHECKPOINTED','RESULT_AVAILABLE','VERIFYING']);
const EXECUTION_RE=/^\s*(?:teste|testar|rode|rodar|execute|executar|fa[cç]a\s+o\s+teste)\s+(.+?)\s*$/i;
const REPEATED_COMMAND_COMMA=/,\s*(?=(?:teste|testar|rode|rodar|execute|executar|fa[cç]a\s+o\s+teste)\b)/gi;

function fold(value){return String(value??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').replace(/\s+/g,' ').trim();}
function canonScalar(value){return value===undefined||value===null||value===''?null:fold(value);}
function canonList(values){return [...new Set((Array.isArray(values)?values:[]).map(fold).filter(Boolean))].sort();}
function canonicalJson(value){if(Array.isArray(value))return `[${value.map(canonicalJson).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;return JSON.stringify(value);}
function digest(value){return createHash('sha256').update(value).digest('hex');}
function identityFromFingerprint(fingerprint){const hex=String(fingerprint).replace(/^sha256:/,'');return {testId:`T-CHAT-${hex.slice(0,12).toUpperCase()}`,correlationId:`CORR-${hex.slice(0,16).toUpperCase()}`};}
function defaultValue(defaults,...keys){for(const key of keys)if(defaults?.[key]!==undefined)return defaults[key];return undefined;}

export function toolDescriptor(){return {name:TOOL_NAME,description:'Submit explicit user-directed scientific tests through the canonical Tower-first NEXO intake path.',inputSchema:{type:'object',additionalProperties:false,required:['utterance'],properties:{utterance:{type:'string',minLength:1},source:{type:'string',default:'chat'},defaults:{type:'object',additionalProperties:false,properties:{test_group_id:{type:'string'},claim_boundary:{type:'string'},decision_rule:{type:'string'},execution_capability:{type:'string'},datasets:{type:'array',items:{type:'string'}},rival:{type:'string'},null:{type:'string'},method:{type:'string'},model_constraints:{type:'array',items:{type:'string'}}}}}}};}
export function bootstrapToolDescriptor(){return {name:BOOTSTRAP_TOOL_NAME,description:'Discover the canonical NEXO truth owner, Hypothesis Registry/Frontier routes, objective ingress and execution ownership without relying on chat memory.',inputSchema:{type:'object',additionalProperties:false,properties:{}}};}
export function capabilitiesToolDescriptor(){return {name:CAPABILITIES_TOOL_NAME,description:'List the hosted NEXO MCP discovery surface and canonical capability routes without exposing credentials.',inputSchema:{type:'object',additionalProperties:false,properties:{}}};}
function privateDescriptor(name){const descriptions={
  'nexo.status':'Read canonical NEXO health and control state.','nexo.get_state':'Read canonical TOWER_V06 control state.','nexo.get_work':'Read one canonical work entity.','nexo.get_next_work':'Read the next work item from a canonical role view.','nexo.get_mutation':'Read mutation receipt status.',
  'nexo.get_hypotheses':'Read the canonical hypothesis registry derived directly from Tower entities.','nexo.get_hypothesis':'Read one canonical hypothesis entity by id.','nexo.get_hypothesis_frontier':'Derive the current hypothesis frontier from canonical Tower entities.','nexo.validate_hypothesis_contract':'Validate a hypothesis payload against HYPOTHESIS_LIFECYCLE_V1 without mutation.','nexo.ingest_hypothesis':'Create or deduplicate one user-directed scientific hypothesis through the canonical mutation/readback path.',
  'nexo.create_work':'Create work through the canonical Tower mutation/CAS path.','nexo.ingest_request':'Admit or merge one actionable compact intent into canonical WORK.','nexo.ingest_objective':'Admit one ENGINEERING/OLYMPUS/SYSTEM objective through REQUEST_INGRESS_V1.','nexo.handoff_work':'Handoff canonical work to another role.','nexo.start_work':'Start canonical READY/CHECKPOINTED work.','nexo.submit_result':'Submit a bounded work result transition.','nexo.block_work':'Block nonterminal work with a reason.','nexo.complete_work':'Complete eligible canonical work.',
  'nexo.prepare_campaign':'Prepare 1-50 related work items under one deterministic campaign.','nexo.prepare_batteries':'Prepare primary and optional parallel batteries as deterministic campaigns.','nexo.compose_scientific_battery':'Compose a frozen battery only from canonical hypothesis/contracts/capabilities; optionally submit the READY plan through scientific intake v2.','nexo.run_batteries':'Run primary and optional parallel prepared battery campaigns.','nexo.reconcile_work':'Apply only machine-verifiable dependency/closure transitions with canonical readback.','nexo.submit_scientific_tests':'Submit 1-50 structured scientific TEST contracts using canonical fingerprint v2, TEST->WORK persistence and optional dispatch.','nexo.run_work':'Dispatch one canonical work item through its declared PASS capability.','nexo.run_campaign':'Dispatch multiple canonical work items independently.','nexo.readback':'Read one canonical runtime report.','nexo.get_evidence':'Read one canonical runtime evidence object.','nexo.get_campaigns':'Read the canonical campaign index.','nexo.get_campaign':'Read one canonical campaign and its active WORK grouping.','nexo.get_request_readback':'Read canonical mutation receipt plus WORK readback when available.','nexo.get_roadmaps':'Read the canonical scientific roadmap index.','nexo.get_roadmap':'Read and validate one canonical scientific roadmap.','nexo.get_next_roadmap_test':'Resolve the dependency-satisfied canonical roadmap frontier without mutation.','nexo.materialize_roadmap_test':'Materialize one dependency-satisfied frozen roadmap TEST through scientific fingerprint v2 and TEST->WORK persistence, optionally dispatching it.','nexo.get_interdomain':'Read the canonical interdomain-active index.',
  'nexo.observe_health_issue':'Observe/dedupe one canonical health incident fingerprint.','nexo.start_health_repair':'Move one canonical health incident into REPAIRING.','nexo.resolve_health_issue':'Resolve one canonical health incident with evidence.','nexo.cleanup_repository_branches':'Delete only stale Atlas/NEXO branches that are already fully merged into Pantheon main; never create deployment branches.'
  };const required={
    'nexo.get_work':['work_id'],'nexo.get_mutation':['request_id'],'nexo.get_hypothesis':['hypothesis_id'],'nexo.validate_hypothesis_contract':['hypothesis'],'nexo.ingest_hypothesis':['proposition'],'nexo.create_work':['title','correlation_id'],'nexo.ingest_request':['thread_id','action','subject','domain','owner_role'],'nexo.ingest_objective':['goal'],'nexo.handoff_work':['work_id','expected_version','writer_role','correlation_id','target_role'],'nexo.start_work':['work_id','expected_version','writer_role','correlation_id'],'nexo.submit_result':['work_id','expected_version','writer_role','correlation_id','outcome'],'nexo.block_work':['work_id','expected_version','writer_role','correlation_id','reason'],'nexo.complete_work':['work_id','expected_version','writer_role','correlation_id'],'nexo.prepare_campaign':['objective','correlation_id','tests'],'nexo.prepare_batteries':['correlation_id','primary'],'nexo.compose_scientific_battery':['hypothesis_id'],'nexo.run_batteries':['correlation_id','primary'],'nexo.reconcile_work':['work_id','correlation_id'],'nexo.submit_scientific_tests':['correlation_id','tests'],'nexo.run_work':['work_id','correlation_id'],'nexo.run_campaign':['work_ids','correlation_id'],'nexo.readback':['run_id'],'nexo.get_evidence':['evidence_id'],'nexo.get_campaign':['campaign_id'],'nexo.get_request_readback':['request_id'],'nexo.get_roadmap':['roadmap_id'],'nexo.materialize_roadmap_test':['roadmap_id','roadmap_test_id','correlation_id'],'nexo.observe_health_issue':['invariant_or_defect_code','affected_entity_kind','affected_entity_id','root_cause_code'],'nexo.start_health_repair':['work_id','repair_action'],'nexo.resolve_health_issue':['work_id','resolution_summary','resolution_evidence_refs']
  }[name]||[];const properties=Object.fromEntries(required.map(key=>[key,key==='hypothesis'?{type:'object'}:key==='tests'||key==='work_ids'||key==='resolution_evidence_refs'?{type:'array'}:key==='expected_version'?{type:'integer',minimum:0}:{type:'string'}]));return {name,description:descriptions[name]||'Canonical NEXO semantic operation.',inputSchema:{type:'object',additionalProperties:true,required,properties}};}
export function toolDescriptors({authenticated=false}={}){const base=[bootstrapToolDescriptor(),capabilitiesToolDescriptor(),toolDescriptor()];return authenticated?[...base,...PRIVATE_SEMANTIC_TOOLS.map(privateDescriptor)]:base;}
export function isPublicDiscoveryTool(name){return PUBLIC_DISCOVERY_TOOLS.has(String(name||''));}
export function isPrivateSemanticTool(name){return PRIVATE_SEMANTIC_SET.has(String(name||''));}
export function isExecutionUtterance(text){return EXECUTION_RE.test(String(text??''));}
export function parseExecutionClauses(text){const chunks=String(text??'').split(/[;\n]+/).flatMap(part=>part.split(REPEATED_COMMAND_COMMA));return chunks.map(part=>part.trim()).filter(part=>part&&isExecutionUtterance(part));}
export function executionSubject(clause){const match=String(clause??'').match(EXECUTION_RE);if(!match)throw new Error('NOT_EXPLICIT_EXECUTION_COMMAND');const subject=match[1].replace(/\s+/g,' ').trim();if(!subject)throw new Error('EXECUTION_SUBJECT_REQUIRED');return subject;}
export function buildScientificTestSpec(clause,defaults={}){if(!defaults||typeof defaults!=='object'||Array.isArray(defaults))throw new Error('DEFAULTS_MUST_BE_OBJECT');return {question:executionSubject(clause),datasets:Array.isArray(defaultValue(defaults,'datasets'))?[...defaultValue(defaults,'datasets')]:[],rival:defaultValue(defaults,'rival')??null,null:defaultValue(defaults,'null')??null,method:defaultValue(defaults,'method')??null,decision_rule:defaultValue(defaults,'decision_rule','decisionRule')??null,model_constraints:Array.isArray(defaultValue(defaults,'model_constraints','modelConstraints'))?[...defaultValue(defaults,'model_constraints','modelConstraints')]:[],test_group_id:defaultValue(defaults,'test_group_id','testGroupId')??DEFAULT_GROUP,claim_boundary:defaultValue(defaults,'claim_boundary','claimBoundary')??null,execution_capability:defaultValue(defaults,'execution_capability','executionCapability')??null};}
export function scientificFingerprint(spec){const payload={question:canonScalar(spec?.question),datasets:canonList(spec?.datasets),rival:canonScalar(spec?.rival),null:canonScalar(spec?.null),method:canonScalar(spec?.method),decision_rule:canonScalar(spec?.decision_rule),model_constraints:canonList(spec?.model_constraints)};return `sha256:${digest(canonicalJson(payload))}`;}
export function buildTowerMutationRequest(spec,{requestId}={}){const fingerprint=scientificFingerprint(spec);const {testId,correlationId}=identityFromFingerprint(fingerprint);const safeRequestId=requestId||`REQ-MCP-${testId.replace(/[^A-Za-z0-9_.:-]/g,'-')}`;return {request_id:safeRequestId,entity_kind:'test',entity_name:testId,expected_version:0,writer_role:'EXECUTOR',event_type:'TEST_CREATED',material:true,changes:{id:testId,kind:'TEST',label:String(spec.question||testId),question:String(spec.question||''),status:'READY',test_group_id:spec.test_group_id||DEFAULT_GROUP,writer_role:'EXECUTOR',scientific_fingerprint:fingerprint,claim_boundary:spec.claim_boundary??null,decision_rule:spec.decision_rule??null,provenance_refs:[],execution_capability:spec.execution_capability??null,correlation_id:correlationId,datasets:Array.isArray(spec.datasets)?spec.datasets:[],rival:spec.rival??null,null:spec.null??null,method:spec.method??null,model_constraints:Array.isArray(spec.model_constraints)?spec.model_constraints:[]}};}
function existingReceipt(existing,fingerprint){const status=String(existing?.status||'').toUpperCase();const testId=existing?.test_id||existing?.id;const {correlationId}=identityFromFingerprint(fingerprint);if(TERMINAL.has(status))return {test_id:testId,fingerprint,state:'DUPLICATE_TERMINAL',correlation_id:existing?.correlation_id||correlationId,dispatch_ref:null,canonical_readback:true,result_ref:existing?.result_ref||existing?.last_result_id||null};if(ACTIVE.has(status))return {test_id:testId,fingerprint,state:'ATTACH_EXISTING',correlation_id:existing?.correlation_id||correlationId,dispatch_ref:existing?.dispatch_ref||null,canonical_readback:true,result_ref:existing?.result_ref||existing?.last_result_id||null};return null;}
function canonicalBootstrap(configured={}){const towerRepo=String(configured.towerRepo||'byDenoso/NEXO-Obsidian-Vault');const towerRef=String(configured.towerRef||'main');const towerStore=String(configured.towerStore||'GITHUB').toUpperCase();const drivePrimary=towerStore==='GOOGLE_DRIVE'||towerStore==='DRIVE_PRIMARY';const canonical=drivePrimary?{authority:'TOWER_V06',storage:'GOOGLE_DRIVE_PRIVATE',root:'TOWER_V06',pointer:'CURRENT.json',snapshot_root:'SNAPSHOTS',truth_owner:'TOWER_V06'}:{authority:'TOWER_V06',storage:'GITHUB',repository:towerRepo,ref:towerRef,root:'TOWER_V06',truth_owner:`${towerRepo}@${towerRef}:TOWER_V06`};return {contract:'NEXO_CAPABILITY_BOOTSTRAP_V1',canonical,memory_dependency:false,repository_policy:{scope:'CODE_ONLY',production_branch:'main',deploy_branch_creation:'FORBIDDEN',experimental_branch_rule:'ONLY_ISOLATED_WORK',merged_branch_retention:'DELETE_AFTER_MERGE',rollback_source:'COMMIT_OR_TAG',cleanup_tool:'nexo.cleanup_repository_branches',cleanup_scope:['atlas-*','feat/atlas-*','chatgpt/nexo-*','claude/nexo-*','backup/nexo-one-*','feat/nexo-atlas-*']},science:{registry:'nexo.get_hypotheses',entity:'nexo.get_hypothesis',frontier:'nexo.get_hypothesis_frontier',ingress:'nexo.ingest_hypothesis',contract_validator:'nexo.validate_hypothesis_contract',execution_owner:'NEXO Autoconsistente v1.3',terminal_rule:'RESULT -> HYPOTHESIS_RECONCILIATION -> CLAIM_UPDATE_OR_NO_CHANGE -> NEXT_TEST_OR_TERMINALIZE -> READBACK'},objectives:{ingress:'nexo.ingest_objective',canonical_route:'REQUEST_INGRESS_V1 -> WORK',types:['ENGINEERING','OLYMPUS','SYSTEM']},hosted:{endpoint_role:'DISCOVERY_PLUS_SEMANTIC_EXECUTION',tower_storage:canonical.storage,tower_write_configured:Boolean(configured.towerWrite),mutation_policy:Boolean(configured.towerWrite)?'AUTHORIZED_SERVER_CREDENTIAL':'FAIL_CLOSED_NO_RUNTIME_CREDENTIAL'},rule:'MCP is capability/discovery; Tower remains canonical truth.'};}
export function createScientificMcpService({gateway}){if(!gateway)throw new Error('TOWER_GATEWAY_REQUIRED');return {async getBootstrap(){return canonicalBootstrap(gateway.configured||{});},async getCapabilities(){const bootstrap=canonicalBootstrap(gateway.configured||{});return {contract:'NEXO_HOSTED_CAPABILITY_SURFACE_V1',hosted_tools:toolDescriptors().map(item=>item.name),authenticated_semantic_tool_count:PRIVATE_SEMANTIC_TOOLS.length,canonical_routes:{...bootstrap.science,objective_ingress:bootstrap.objectives.ingress},tower_write_configured:bootstrap.hosted.tower_write_configured,memory_dependency:false};},async submitUtterance(utterance,{source='chat',defaults={}}={}){if(typeof utterance!=='string'||!utterance.trim())throw new Error('UTTERANCE_REQUIRED');const clauses=parseExecutionClauses(utterance);if(!clauses.length)throw new Error('NOT_EXPLICIT_SCIENTIFIC_EXECUTION_COMMAND');const tests=[];for(const clause of clauses){const spec=buildScientificTestSpec(clause,defaults);const fingerprint=scientificFingerprint(spec);const {testId,correlationId}=identityFromFingerprint(fingerprint);const existing=await gateway.findByFingerprint(fingerprint,{spec,testId,source});const reused=existing&&existingReceipt(existing,fingerprint);if(reused){tests.push(reused);continue;}const mutation=buildTowerMutationRequest(spec);const persisted=await gateway.persistTest(mutation,{spec,source});if(persisted?.accepted===false)throw new Error(`TOWER_MUTATION_REJECTED:${persisted?.issue?.code||'UNKNOWN'}`);const readback=await gateway.readbackTest(testId,{fingerprint,source});if(!readback||String(readback.id||readback.test_id||'')!==testId)throw new Error('TOWER_READBACK_MISMATCH');if(readback.scientific_fingerprint&&readback.scientific_fingerprint!==fingerprint)throw new Error('TOWER_FINGERPRINT_MISMATCH');const capability=await gateway.resolveCapability(spec,{testId,fingerprint,readback,source});if(!capability){if(typeof gateway.markCapabilityGap==='function')await gateway.markCapabilityGap({testId,fingerprint,correlationId,spec,readback,source});tests.push({test_id:testId,fingerprint,state:'CAPABILITY_GAP',correlation_id:correlationId,dispatch_ref:null,canonical_readback:true});continue;}const dispatchRef=await gateway.dispatchTest({testId,fingerprint,correlationId,spec,readback,capability,source});tests.push({test_id:testId,fingerprint,state:'DISPATCHED',correlation_id:correlationId,dispatch_ref:dispatchRef||null,canonical_readback:true});}return {accepted:true,tests};}};}
function rpcResult(id,result){return {jsonrpc:'2.0',id:id??null,result};}
function rpcError(id,code,message,data){return {jsonrpc:'2.0',id:id??null,error:{code,message,...(data===undefined?{}:{data})}};}
function toolCallResult(result){return {content:[{type:'text',text:JSON.stringify(result)}],structuredContent:result,isError:false};}
export async function handleMcpRpc(message,{service,semantic=null,authenticated=false}={}){if(!message||message.jsonrpc!=='2.0'||typeof message.method!=='string')return rpcError(message?.id,-32600,'Invalid Request');const {id,method,params={}}=message;if(method==='initialize')return rpcResult(id,{protocolVersion:params.protocolVersion||'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'nexo-capability-bootstrap',version:'1.2.0'}});if(method==='notifications/initialized')return null;if(method==='ping')return rpcResult(id,{});if(method==='tools/list')return rpcResult(id,{tools:toolDescriptors({authenticated})});if(method==='tools/call'){const args=params?.arguments;if(!args||typeof args!=='object'||Array.isArray(args))return rpcError(id,-32602,'Tool arguments must be an object');try{if(params?.name===BOOTSTRAP_TOOL_NAME)return rpcResult(id,toolCallResult(await service.getBootstrap()));if(params?.name===CAPABILITIES_TOOL_NAME)return rpcResult(id,toolCallResult(await service.getCapabilities()));if(params?.name===TOOL_NAME){const result=await service.submitUtterance(args.utterance,{source:args.source||'chat',defaults:args.defaults||{}});return rpcResult(id,toolCallResult(result));}if(isPrivateSemanticTool(params?.name)){if(!authenticated)return rpcError(id,-32001,'Unauthorized');if(!semantic||typeof semantic.call!=='function')throw new Error('SEMANTIC_GATEWAY_UNAVAILABLE');return rpcResult(id,toolCallResult(await semantic.call(params.name,args)));}return rpcError(id,-32602,'Unknown tool');}catch(error){const messageText=String(error?.message||error);return rpcResult(id,{content:[{type:'text',text:messageText}],structuredContent:{accepted:false,error:messageText},isError:true});}}return rpcError(id,-32601,'Method not found');}
export const _internal={fold,canonicalJson,identityFromFingerprint,DEFAULT_GROUP,canonicalBootstrap,PRIVATE_SEMANTIC_TOOLS};
