import {useEffect,useRef,useState} from 'react';
import type {CockpitItem,WorldState,LoopStatus} from '../contracts/world';
import {stateLabel,providerLabel,dateTime,time,dayItems,localDate,overlap,type Tab} from '../app/model';
export function ItemRow({item,onSelect,index}:{item:CockpitItem;onSelect:(i:CockpitItem)=>void;index?:number}){return <button className="item-row" onClick={()=>onSelect(item)}><span className={`item-marker ${item.attention.toLowerCase()}`}>{index===undefined?({FILE:'↗',ENTITY:'◇',ISSUE:'○',MESSAGE:'↗',EVENT:'◷',DEPLOYMENT:'↗',ACTION:'→'}[item.kind]):String(index+1).padStart(2,'0')}</span><span className="item-copy"><strong>{item.title}</strong><span>{item.contextId||'PERSONAL'} <b> / </b> {providerLabel[item.source]}{item.dueAt&&<> <b> / </b> {item.allDay?item.dueAt:dateTime(item.dueAt)}</>}{item.freshness.state!=='LIVE'&&<> <b> / </b> Leitura anterior</>}</span>{item.attentionReason&&<small>{item.attentionReason}</small>}</span><span className="row-end">{item.status&&<span className={`status ${item.attention.toLowerCase()}`}>{stateLabel[item.status]}</span>}<span className="row-arrow">↗</span></span></button>;}
export function Empty({title,description}:{title:string;description:string}){return <div className="empty-state"><span className="empty-mark" aria-hidden="true">◇</span><h3>{title}</h3><p>{description}</p></div>;}
export function Workspace({tab,world,onSelect,context,setContext,query,onQuery,loading}:{tab:Tab;world:WorldState|null;onSelect:(i:CockpitItem)=>void;context:string;setContext:(s:string)=>void;query:string;onQuery:(s:string)=>void;loading:boolean}){
  const items=world?.items||[],unavailable=!world||world.providers.some(p=>p.status!=='AVAILABLE'||p.partial);
  const [loop,setLoop]=useState<LoopStatus|'ALL'>('ALL'),[day,setDay]=useState(localDate()),[draft,setDraft]=useState(query),[search,setSearch]=useState<WorldState|null>(null),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
  const searchSeq=useRef(0);
  useEffect(()=>setDraft(query),[query]);
  useEffect(()=>{if(!query){setSearch(null);return;}const ctrl=new AbortController(),seq=++searchSeq.current;setSearching(true);setSearch(null);setSearchError('');fetch(`/api/recall?q=${encodeURIComponent(query)}`,{signal:ctrl.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(value=>{if(seq===searchSeq.current&&!ctrl.signal.aborted)setSearch(value);}).catch(()=>{if(!ctrl.signal.aborted)setSearchError('Busca indisponível. Tente novamente.');}).finally(()=>{if(!ctrl.signal.aborted)setSearching(false);});return()=>ctrl.abort();},[query]);
  if(tab==='NOW'){
    const attention=items.filter(i=>['ACT','ESCALATE'].includes(i.attention)),others=items.filter(i=>i.attention==='NOTICE');
    return <><div className="section-head"><h2>Precisa de você <span>{attention.length||'—'}</span></h2><span className="eyebrow">ATÉ 3 PRIORIDADES</span></div>{attention.length?attention.slice(0,3).map((i,n)=><ItemRow key={i.id} item={i} onSelect={onSelect} index={n}/>):<Empty title={loading?'Consultando suas fontes…':unavailable?'Sua visão ainda está incompleta.':'Nenhuma ação prioritária nesta leitura.'} description={unavailable?'Conecte as fontes privadas para trazer prazos, compromissos e próximos passos.':'Os itens consultados não têm bloqueios ou prazos que exijam atenção agora.'}/>}{attention.length>3&&<p className="small-note">Mais {attention.length-3} itens exigem atenção. Consulte LOOPS.</p>}<div className="section-head secondary"><h2>No radar <span>{others.length||'—'}</span></h2><span className="eyebrow">CONTEXTO RECENTE</span></div>{others.slice(0,6).map(i=><ItemRow key={i.id} item={i} onSelect={onSelect}/>)}{!others.length&&<p className="small-note">Os registros aparecem aqui assim que uma fonte responde.</p>}</>;
  }
  if(tab==='LOOPS'){
    const rows=items.filter(i=>i.status&&(loop==='ALL'||i.status===loop));
    return <><div className="filter-row" role="group" aria-label="Filtrar compromissos">{(['ALL','NEEDS_ME','WAITING_OTHER','SCHEDULED','BLOCKED','DONE'] as const).map(s=><button key={s} className={loop===s?'filter active':'filter'} onClick={()=>setLoop(s)} aria-pressed={loop===s}>{s==='ALL'?'Todos':stateLabel[s]}</button>)}</div><div className="section-head"><h2>Loops registrados</h2><span className="eyebrow">ESTADO NA FONTE</span></div>{rows.length?rows.map(i=><ItemRow key={i.id} item={i} onSelect={onSelect}/>):<Empty title="Nenhum compromisso disponível neste filtro." description={unavailable?'Há fontes pendentes de conexão. O estado dos compromissos dessas fontes ainda é desconhecido.':'Nenhum registro consultado corresponde a este estado.'}/>}<p className="small-note">E-mails e arquivos entram como contexto. Compromissos exigem um estado explícito na fonte.</p></>;
  }
  if(tab==='DAY'){
    const events=dayItems(items,day),cal=world?.providers.find(p=>p.id==='calendar'),flex=items.filter(i=>i.status==='NEEDS_ME').slice(0,4);
    return <><div className="section-head"><h2>Agenda e espaço de trabalho</h2><label className="date-label">Data <input aria-label="Data da agenda" type="date" value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label></div>{cal?.status!=='AVAILABLE'&&<div className="notice-box">Calendar: {stateLabel[cal?.status||'UNAVAILABLE']}. A disponibilidade do dia ainda não pode ser confirmada.</div>}<div className="day-timeline">{events.map(i=><div className="time-slot" key={i.id}><div className="time-label">{i.allDay?'Dia todo':time(i.dueAt)}<small>{!i.allDay&&time(i.endAt)}</small></div><div><ItemRow item={i} onSelect={onSelect}/>{events.some(e=>e.id!==i.id&&overlap(i,e))&&<span className="overlap">Horário sobreposto a outro evento.</span>}</div></div>)}{!events.length&&<Empty title={cal?.status==='AVAILABLE'?'Nenhum evento retornado para este dia.':'Agenda aguardando conexão.'} description="Os horários fixos vêm do Calendar. Propostas de trabalho não alteram eventos reais."/>}</div><div className="section-head secondary"><h2>Trabalho flexível</h2><span className="eyebrow">SEM HORÁRIO RESERVADO</span></div>{flex.map(i=><ItemRow key={i.id} item={i} onSelect={onSelect}/>)}{!flex.length&&<p className="small-note">Próximas ações serão exibidas quando houver loops atribuídos a você.</p>}</>;
  }
  if(tab==='CONTEXT'){
    const current=world?.contexts.find(c=>c.id===context),rows=items.filter(i=>i.contextId===context);
    return <><div className="context-grid">{(world?.contexts||[]).map(c=><button key={c.id} className={`context-option ${context===c.id?'selected':''}`} onClick={()=>setContext(c.id)}><span className="context-symbol">{({NEXO:'⌘',COSMOLOGY:'✧',OLYMPUS:'△',ENGINEERING:'⌥',PERSONAL:'○'} as Record<string,string>)[c.id]}</span><strong>{c.title}</strong><small>{c.itemIds.length?`${c.itemIds.length} registros`:'Sem leitura disponível'}</small></button>)}</div><div className="context-heading"><span className="eyebrow">CONTEXTO ATIVO</span><h2>{current?.title||'NEXO'}</h2><p>{current?.description||'Selecione uma área para continuar.'}</p></div>{context==='COSMOLOGY'&&<a className="atlas-launch" href="https://nexo-atlas-control-tower.vercel.app" target="_blank" rel="noopener noreferrer"><span><span className="eyebrow">OBSERVATÓRIO</span><strong>Atlas</strong><small>Explorar o mapa e suas fontes</small></span><span className="atlas-orbit" aria-hidden="true">✧</span><span>↗</span></a>}{rows.length?rows.map(i=><ItemRow key={i.id} item={i} onSelect={onSelect}/>):<Empty title="Este contexto aguarda fontes." description="Objetivos, arquivos e ações aparecem quando os providers retornam registros com origem verificável."/>}</>;
  }
  const found=search?.items||[],groups=new Map<string,CockpitItem[]>(); for(const row of found){const key=row.contextId||'PERSONAL';groups.set(key,[...(groups.get(key)||[]),row]);}
  return <><form className="recall-form" onSubmit={e=>{e.preventDefault();onQuery(draft.trim());}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Nome, documento, assunto ou projeto" aria-label="Buscar nas fontes"/><button className="primary-button" disabled={!draft.trim()||searching}>Buscar ↗</button></form><p className="small-note">Busca lexical em Drive, Gmail e GitHub; consulta aos registros de NEXO e Atlas disponíveis. Resultados preservam a origem.</p>{searching&&<div className="notice-box" role="status">Consultando as fontes…</div>}{searchError&&<div role="alert" className="notice-box">{searchError}</div>}{search&&<div className="search-coverage">{search.providers.map(p=><span key={p.id} className={`provider-pill ${p.status==='AVAILABLE'?'available':''}`}>{p.label} · {p.status==='AVAILABLE'?`${p.count}${p.partial?'+':''}`:stateLabel[p.status]}</span>)}</div>}{[...groups].map(([group,rows])=><section key={group}><div className="section-head"><h2>{group}</h2><span className="eyebrow">{rows.length} RESULTADOS</span></div>{rows.map(i=><ItemRow key={i.id} item={i} onSelect={onSelect}/>)}</section>)}{!found.length&&!searching&&<Empty title={query?'Nenhum resultado disponível.':'Retome de onde parou.'} description={query?'Confira a cobertura das fontes acima. Uma fonte desconectada não confirma ausência de resultados.':'Procure por CAMB, um plano do Olympus ou uma decisão registrada.'}/>}</>;
}
