import {state} from './lib/model.mjs';
export function project([x,y,z],c,w,h){if(c.flat)z=0;const cy=Math.cos(c.yaw),sy=Math.sin(c.yaw),cp=Math.cos(c.pitch),sp=Math.sin(c.pitch);const xx=x*cy+z*sy,zz=z*cy-x*sy,yy=y*cp-zz*sp,depth=y*sp+zz*cp;const scale=750/(750-depth)*(c.zoom||1)*Math.min(w/1000,h/660);return{x:w/2+xx*scale+(c.panX||0),y:h/2+yy*scale+(c.panY||0),z:depth,scale}}
export function layout(nodes,focus){const count=Math.max(1,nodes.length-1);let k=0;return nodes.map(n=>{if(n.id===focus)return[0,0,0];const i=k++,r=count<10?235:count<30?270:320,angle=i*2.399963229728653,yy=1-2*(i+.5)/count,rad=Math.sqrt(1-yy*yy);return[Math.cos(angle)*rad*r,yy*r*.8,Math.sin(angle)*rad*r*.75]})}
export const colors={supported:'#69dec0',partial:'#efc379',negative:'#f38999',blocked:'#ff687c',active:'#6bceff',legacy:'#73819b',unknown:'#a2b3ce'};
export class Graph3D{constructor(canvas,{select,open,edge}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.callbacks={select,open,edge};this.camera={yaw:.2,pitch:-.2,zoom:1,panX:0,panY:0};this.data={nodes:[],edges:[]};this.points=[];this.selected=null;this.hover=null;this.pointers=new Map();this.draw=this.draw.bind(this);new ResizeObserver(()=>this.draw()).observe(canvas);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(Math.exp(-e.deltaY*.001))},{passive:false});canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});this.down={x:e.offsetX,y:e.offsetY,node:this.hit(e.offsetX,e.offsetY),button:e.button,moved:0};this.distance=this.pinch()});canvas.addEventListener('pointermove',e=>{const p=this.pointers.get(e.pointerId);if(p){if(!this.down)this.down={x:p.x,y:p.y,node:null,button:0,moved:10};const dx=e.offsetX-p.x,dy=e.offsetY-p.y;this.pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});this.down.moved+=Math.abs(dx)+Math.abs(dy);if(this.pointers.size===2){const d=this.pinch();if(this.distance)this.camera.zoom=Math.max(.3,Math.min(4,this.camera.zoom*d/this.distance));this.distance=d}else if(e.shiftKey||this.down.button===2){this.camera.panX+=dx;this.camera.panY+=dy}else if(this.down.node&&e.altKey){const i=this.data.nodes.findIndex(n=>n.id===this.down.node.id);this.positions[i][0]+=dx;this.positions[i][1]+=dy}else{this.camera.yaw+=dx*.006;this.camera.pitch=Math.max(-1.4,Math.min(1.4,this.camera.pitch+dy*.006))}this.draw()}else{const n=this.hit(e.offsetX,e.offsetY);if(n?.id!==this.hover?.id){this.hover=n;canvas.style.cursor=n?'pointer':'grab';this.draw()}}});canvas.addEventListener('pointerup',e=>{this.pointers.delete(e.pointerId);if(this.down&&this.down.moved<6){const n=this.hit(e.offsetX,e.offsetY);if(n){this.selected=n.id;this.callbacks.select(n);this.draw()}else{const edge=this.hitEdge(e.offsetX,e.offsetY);if(edge)this.callbacks.edge?.(edge)}}this.down=null});canvas.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.down=null});canvas.addEventListener('dblclick',e=>{const n=this.hit(e.offsetX,e.offsetY);if(n)this.callbacks.open(n)});canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')this.camera.yaw-=.15;if(e.key==='ArrowRight')this.camera.yaw+=.15;if(e.key==='ArrowUp')this.camera.pitch-=.15;if(e.key==='ArrowDown')this.camera.pitch+=.15;if(e.key==='+')this.zoom(1.15);if(e.key==='-')this.zoom(.85);this.draw()})}
pinch(){const p=[...this.pointers.values()];return p.length===2?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}
set(data,focus){this.data=data;this.focus=focus;this.positions=layout(data.nodes,focus);this.reset()}
reset(){Object.assign(this.camera,{yaw:.2,pitch:-.2,zoom:1,panX:0,panY:0});this.draw()}
zoom(f){this.camera.zoom=Math.max(.3,Math.min(4,this.camera.zoom*f));this.draw()}
center(){const p=this.points.find(p=>p.node.id===this.selected);if(p){this.camera.panX+=this.w/2-p.x;this.camera.panY+=this.h/2-p.y;this.draw()}}
hit(x,y){return [...this.points].sort((a,b)=>b.z-a.z).find(p=>Math.hypot(p.x-x,p.y-y)<p.r+9)?.node}
hitEdge(x,y){for(const e of this.data.edges){const a=this.points.find(p=>p.node.id===e.source),b=this.points.find(p=>p.node.id===e.target);if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy)));if(Math.hypot(x-a.x-t*dx,y-a.y-t*dy)<5)return e}return null}
draw(){const c=this.ctx,w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.w=w;this.h=h;const dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=w*dpr;this.canvas.height=h*dpr;c.scale(dpr,dpr);c.clearRect(0,0,w,h);const neb=c.createRadialGradient(w*.52,h*.48,0,w*.52,h*.48,w*.5);neb.addColorStop(0,'#10223b88');neb.addColorStop(.6,'#08132244');neb.addColorStop(1,'#060c1600');c.fillStyle=neb;c.fillRect(0,0,w,h);
// Deterministic stars are decorative; node positions encode navigation only.
for(let i=0;i<120;i++){const x=(Math.sin(i*12.9898)*43758.5453%1+1)%1*w,y=(Math.sin(i*7.23)*14321.33%1+1)%1*h;c.fillStyle=i%7===0?'#a8bdda55':'#7086a329';c.fillRect(x,y,i%7===0?1.5:1,i%7===0?1.5:1)}
for(const radius of [120,240,345]){c.beginPath();for(let i=0;i<=100;i++){const a=i/100*Math.PI*2,p=project([Math.cos(a)*radius,70,Math.sin(a)*radius],this.camera,w,h);if(i)c.lineTo(p.x,p.y);else c.moveTo(p.x,p.y)}c.strokeStyle='#56769c1f';c.lineWidth=1;c.stroke()}
this.points=this.data.nodes.map((node,i)=>{const p=project(this.positions[i],this.camera,w,h);return{...p,node,r:Math.max(4,(node.id===this.focus?25:node.type==='SYSTEM'?16:node.type==='DOMAIN'?13:node.type==='CAMPAIGN'?10:6)*p.scale)}});const map=new Map(this.points.map(p=>[p.node.id,p])),neighbors=new Set([this.selected]);for(const e of this.data.edges)if(e.source===this.selected||e.target===this.selected){neighbors.add(e.source);neighbors.add(e.target)}
for(const e of this.data.edges){const a=map.get(e.source),b=map.get(e.target);if(!a||!b)continue;const selected=!this.selected||neighbors.has(a.node.id)&&neighbors.has(b.node.id);c.globalAlpha=selected?.65:.12;c.strokeStyle=e.type==='BLOCKS'?'#ff687c':e.authority==='SCIENCE_CANONICAL'?'#8ab9d6':/ASSOC|BRIDGE|DERIVED/.test(e.type)?'#af97ec':'#58779e';c.setLineDash(e.authority==='SCIENCE_CANONICAL'?[]:[4,6]);c.lineWidth=selected?1.1:.7;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.setLineDash([]);const t=.72,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t,angle=Math.atan2(b.y-a.y,b.x-a.x);c.beginPath();c.moveTo(x,y);c.lineTo(x-5*Math.cos(angle-.5),y-5*Math.sin(angle-.5));c.lineTo(x-5*Math.cos(angle+.5),y-5*Math.sin(angle+.5));c.fillStyle=c.strokeStyle;c.fill()}
c.globalAlpha=1;const boxes=[];for(const p of [...this.points].sort((a,b)=>a.z-b.z)){const n=p.node,active=n.id===this.selected||n.id===this.hover?.id,col=n.type==='LEARNING_RELATION'?'#bc9aff':n.type==='SYSTEM'?'#8bd5e7':colors[state(n.status)];c.globalAlpha=this.selected&&!neighbors.has(n.id)?.28:1;const glow=c.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*(active?4:2.8));glow.addColorStop(0,col+'55');glow.addColorStop(1,col+'00');c.fillStyle=glow;c.beginPath();c.arc(p.x,p.y,p.r*3.5,0,Math.PI*2);c.fill();const sphere=c.createRadialGradient(p.x-p.r*.35,p.y-p.r*.4,0,p.x,p.y,p.r);sphere.addColorStop(0,'#e2f3ff');sphere.addColorStop(.3,col);sphere.addColorStop(1,'#16273b');c.fillStyle=sphere;c.strokeStyle=col;c.lineWidth=active?2:1;c.beginPath();if(['FILE','ARTIFACT','DATASET'].includes(n.type))c.rect(p.x-p.r,p.y-p.r,p.r*2,p.r*2);else if(n.type==='CLAIM'){c.moveTo(p.x,p.y-p.r*1.3);c.lineTo(p.x+p.r,p.y);c.lineTo(p.x,p.y+p.r*1.3);c.lineTo(p.x-p.r,p.y);c.closePath()}else c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill();c.stroke();if(active||n.id===this.focus){c.beginPath();c.ellipse(p.x,p.y,p.r+8,p.r+5,-.3,0,Math.PI*2);c.strokeStyle=col+'99';c.stroke()}
const label=(n.label||n.id).slice(0,this.data.nodes.length>30?28:38),size=n.id===this.focus?19:12;c.font=`${n.id===this.focus?'bold':'normal'} ${size}px sans-serif`;const bw=c.measureText(label).width+16,bh=37,bx=p.x-bw/2,by=p.y+p.r+10;const overlap=boxes.some(b=>bx<b.x+b.w&&bx+bw>b.x&&by<b.y+b.h&&by+bh>b.y);if(active||n.id===this.focus||!overlap&&(this.data.nodes.length<40||p.z>0)){boxes.push({x:bx,y:by,w:bw,h:bh});c.fillStyle='#07101dde';c.fillRect(bx,by-4,bw,bh);c.fillStyle='#d4e4f6';c.textAlign='center';c.fillText(label,p.x,by+size);c.font='9px sans-serif';c.fillStyle=col;c.fillText(n.type.replaceAll('_',' '),p.x,by+size+15)}}c.globalAlpha=1}
}
