import './install.ts';
import {createRoot} from 'react-dom/client';
import Host from './Host.tsx';
import '../styles/product-foundation.css';
import '../styles/tokens.css';
import '../styles/layout.css';
import '../styles/components.css';
import '../styles/system.css';
import '../styles/command-os.css';
import '../styles/nexo-prime.css';
import '../styles/product-shell.css';
import '@fontsource/big-shoulders-display/600';
import '@fontsource/big-shoulders-display/900';
import '@fontsource/ibm-plex-sans/300';
import '@fontsource/ibm-plex-sans/400';
import '@fontsource/ibm-plex-sans/500';
import '@fontsource/ibm-plex-mono/400';
import '@fontsource/ibm-plex-mono/500';
import '../styles/observatory.css';
import '../styles/signature.css';
import '../styles/mission-control.css';
import '../styles/editorial.css';
import '../styles/deco.css';
createRoot(document.getElementById('root')!).render(<Host/>);
