import {useEffect,useMemo,useRef,useState} from 'react';
import '../design/graph-v2.css';
import {loadGraphRuntime} from './runtime';
import {clampGraphZoom,graphDpr,graphNodeBudget,selectVisibleGraphNodes} from './viewport.mjs';
import {layoutCanvasOrbit,nodeVisual,placeCanvasLabels,projectCanvasNode} from './canvas-layout.mjs';
import type {GraphEdge,GraphNode,GraphProjection} from './types';

type Props={projection:GraphProjection;learningEdges?:GraphEdge[];learning:boolean;selectedId?:string|null;selectedEdgeId?:string|null;onSelect:(id:string|null)=>void;onSelectEdge?:(id:string|null)=>void;onToggleLearning?:(value:boolean)=>void};
type Viewport={scale:number;x:number;y:number;tiltX:number;tiltY:number};
type Point={x:number;y:number};
const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
const midpoint=(a:Point,b:Point)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
const clampTilt=(v:number,l:number)=>Math.max(-l,Math.min(l,v));
const displayValue=(v:unknown)=>v===null||v===undefined||v===''?'—':typeof v==='object'?JSON.stringify(v):String(v);
const colorFor=(type:string)=>{const t=type.toUpperCase();if(t==='ROOT')return 0x55dfff;if(t==='DOMAIN')return 0x4fb8ff;if(t==='SUBGRAPH')return 0x7e76ff;if(t==='TEST')return 0xffc65d;if(t==='CLAIM')return 0xd782ff;if(t==='RESULT'||t==='EVIDENCE')return 0x55e7a4;return 0x8ca8ff};

export function GraphExplorer({projection,learningEdges=[],learning,selectedId=null,selectedEdgeId=null,onSelect,onSelectEdge,onToggleLearning}:Props){
 const hostRef=useRef<HTMLDivElement|null>(null);const appRef=useRef<any>(null);const worldRef=useRef<any>(null);const redrawRef=useRef<(()=>void)|null>(null);
 const viewportRef=useRef<Viewport>({scale:1,x:0,y:0,tiltX:0,tiltY:0});const pointersRef=useRef(new Map<number,Point>());const dragRef=useRef<any>(null);const pinchRef=useRef<any>(null);const tiltRef=useRef<any>(null);const movedRef=useRef(false);const reducedRef=useRef(false);
 const callbacksRef=useRef({onSelect,onSelectEdge});const latestRef=useRef({projection,learningEdges,learning,selectedId,selectedEdgeId});const [runtimeError,setRuntimeError]=useState(false);const [contextLost,setContextLost]=useState(false);const [inspectorOpen,setInspectorOpen]=useState(false);
 callbacksRef.current={onSelect,onSelectEdge};latestRef.current={projection,learningEdges,learning,selectedId,selectedEdgeId};
 const selected=useMemo(()=>projection.nodes.find(n=>n.id===selectedId)||null,[projection.nodes,selectedId]);const selectedEdge=useMemo(()=>learningEdges.find(e=>e.id===selectedEdgeId)||projection.edges.find(e=>e.id===selectedEdgeId)||null,[learningEdges,projection.edges,selectedEdgeId]);
 const a11yNodes=useMemo(()=>selectVisibleGraphNodes(projection.nodes,{focusId:projection.focusId,selectedId,budget:graphNodeBudget({width:typeof window==='undefined'?1280:window.innerWidth,nodeCount:projection.nodes.length})}) as GraphNode[],[projection,selectedId]);
 useEffect(()=>{if(selectedId||selectedEdgeId)setInspectorOpen(true)},[selectedId,selectedEdgeId]);
 useEffect(()=>{
  let disposed=false;let cleanup=()=>{};
  void loadGraphRuntime().then(async({PIXI,gsap})=>{
   const host=hostRef.current;if(disposed||!host)return;setRuntimeError(false);const app=new PIXI.Application();
   await app.init({resizeTo:host,background:0x02050c,antialias:true,resolution:graphDpr({devicePixelRatio:window.devicePixelRatio||1,width:host.clientWidth,nodeCount:projection.nodes.length}),autoDensity:true});if(disposed){app.destroy(true);return}
   const canvas=app.canvas as HTMLCanvasElement;canvas.style.touchAction='none';host.replaceChildren(canvas);const world=new PIXI.Container();app.stage.addChild(world);appRef.current=app;worldRef.current=world;
   const media=window.matchMedia('(prefers-reduced-motion: reduce)');reducedRef.current=media.matches;const motion=(e:MediaQueryListEvent)=>{reducedRef.current=e.matches};media.addEventListener?.('change',motion);
   const applyViewport=()=>{const w=worldRef.current;if(!w)return;const v=viewportRef.current;w.scale.set(v.scale);w.position.set(v.x,v.y)};
   const emit=(detail:Record<string,unknown>)=>window.dispatchEvent(new CustomEvent('atlas:graph-metrics',{detail:{engine:'pixi-canvas-only',...detail}}));
   const curve=(g:any,a:any,b:any,bend=30)=>g.moveTo(a.x,a.y).bezierCurveTo((a.x+b.x)/2,a.y-bend,(a.x+b.x)/2,b.y+bend,b.x,b.y);
   const draw=()=>{
    const current=latestRef.current;if(!worldRef.current||!hostRef.current)return;worldRef.current.removeChildren().forEach((c:any)=>c.destroy?.({children:true}));
    const width=Math.max(host.clientWidth,320),height=Math.max(host.clientHeight,420),view=viewportRef.current;const starLayer=new PIXI.Graphics();
    for(let i=0;i<70;i++){const x=(i*97%997)/997*width,y=(i*193%991)/991*height,r=i%11===0?1.4:.55;starLayer.circle(x,y,r).fill({color:0xb8e9ff,alpha:i%7===0?.65:.24})}worldRef.current.addChild(starLayer);
    const visible=selectVisibleGraphNodes(current.projection.nodes,{focusId:current.projection.focusId,selectedId:current.selectedId,budget:graphNodeBudget({width,nodeCount:current.projection.nodes.length})}) as GraphNode[];
    const layout=layoutCanvasOrbit(visible,{focusId:current.projection.focusId,width,height});const projected=new Map<string,any>();for(const n of visible)projected.set(n.id,projectCanvasNode(layout.get(n.id),view));
    const ids=new Set(visible.map(n=>n.id));const edgeLayer=new PIXI.Container();const orbitLayer=new PIXI.Graphics();const nodeLayer=new PIXI.Container();worldRef.current.addChild(orbitLayer,edgeLayer,nodeLayer);
    const focusPos=projected.get(current.projection.focusId||'');if(focusPos){for(const rr of [.23,.36,.49])orbitLayer.ellipse(focusPos.x,focusPos.y,width*rr,height*rr*.55).stroke({width:1,color:0x5aaeff,alpha:.1})}
    for(const e of current.projection.edges){if(!ids.has(e.source)||!ids.has(e.target))continue;const a=projected.get(e.source),b=projected.get(e.target);if(!a||!b)continue;const g=new PIXI.Graphics();const dim=current.selectedId&&e.source!==current.selectedId&&e.target!==current.selectedId;curve(g,a,b,20).stroke({width:1.4,color:0x419cff,alpha:dim?.06:.25});edgeLayer.addChild(g)}
    if(current.learning)for(const e of current.learningEdges){if(!ids.has(e.source)||!ids.has(e.target))continue;const a=projected.get(e.source),b=projected.get(e.target);if(!a||!b)continue;const wrap=new PIXI.Container(),g=new PIXI.Graphics();curve(g,a,b,45).stroke({width:current.selectedEdgeId===e.id?3:1.7,color:0xc477ff,alpha:.66});wrap.addChild(g);wrap.eventMode='static';wrap.cursor='pointer';wrap.on('pointertap',(ev:any)=>{ev.stopPropagation?.();callbacksRef.current.onSelectEdge?.(e.id)});edgeLayer.addChild(wrap)}
    const labelCandidates=visible.map(n=>{const p=projected.get(n.id);const priority=n.id===current.projection.focusId?100:n.id===current.selectedId?95:n.type==='DOMAIN'?75:n.type==='SUBGRAPH'?55:20;return{id:n.id,label:n.label,x:p.x,y:p.y+nodeVisual(n.type).radius*p.depthScale+8,priority}});
    const labels=placeCanvasLabels(labelCandidates,{focusId:current.projection.focusId,selectedId:current.selectedId,measureText:(t:string)=>{const probe=new PIXI.Text({text:t,style:{fontFamily:'Recursive,system-ui',fontSize:12,fontWeight:'600'}});const w=probe.width;probe.destroy();return w},fontHeight:15});const labelIds=new Set(labels.map((l:any)=>l.id));
    for(const n of visible){const p=projected.get(n.id),visual=nodeVisual(n.type,n.id===current.selectedId),wrap=new PIXI.Container();wrap.x=p.x;wrap.y=p.y;wrap.scale.set(p.depthScale);wrap.alpha=p.depthAlpha*(current.selectedId&&current.selectedId!==n.id?.58:1);wrap.eventMode='static';wrap.cursor='pointer';
      const glow=new PIXI.Graphics();glow.circle(0,0,visual.radius+visual.glow).fill({color:colorFor(n.type),alpha:.08});glow.circle(0,0,visual.radius+7).fill({color:colorFor(n.type),alpha:.13});const body=new PIXI.Graphics();body.circle(0,0,visual.radius).fill({color:colorFor(n.type),alpha:.94}).stroke({width:n.id===current.selectedId?3:1.2,color:0xdffaff,alpha:.85});wrap.addChild(glow,body);
      if(labelIds.has(n.id)){const label=new PIXI.Text({text:n.label,style:{fontFamily:'Recursive,system-ui',fontSize:n.type==='ROOT'?16:n.type==='DOMAIN'?14:12,fill:0xf0f9ff,fontWeight:n.type==='ROOT'||n.type==='DOMAIN'?'700':'600',align:'center',dropShadow:{alpha:.8,blur:3,distance:1,color:0x000000}}});label.anchor.set(.5,0);label.y=visual.radius+14;wrap.addChild(label)}
      wrap.on('pointerover',()=>{wrap.scale.set(p.depthScale*1.06)});wrap.on('pointerout',()=>{wrap.scale.set(p.depthScale)});wrap.on('pointertap',()=>{if(movedRef.current){movedRef.current=false;return}callbacksRef.current.onSelect(n.id)});nodeLayer.addChild(wrap)}
    applyViewport();emit({phase:'draw',nodes:current.projection.nodes.length,visibleNodes:visible.length,visibleLabels:labelIds.size,zoom:view.scale,tiltX:view.tiltX,tiltY:view.tiltY});
   };
   redrawRef.current=draw;
   const zoomAround=(next:number,cx:number,cy:number)=>{const rect=canvas.getBoundingClientRect(),v=viewportRef.current,s=clampGraphZoom(next),x=cx-rect.left,y=cy-rect.top,wx=(x-v.x)/v.scale,wy=(y-v.y)/v.scale;viewportRef.current={...v,scale:s,x:x-wx*s,y:y-wy*s};draw()};
   const beginPinch=()=>{const ps=[...pointersRef.current.values()];if(ps.length<2)return;const mid=midpoint(ps[0],ps[1]),r=canvas.getBoundingClientRect(),v=viewportRef.current;pinchRef.current={distance:distance(ps[0],ps[1]),scale:v.scale,x:mid.x-r.left,y:mid.y-r.top}};
   const down=(e:PointerEvent)=>{canvas.setPointerCapture?.(e.pointerId);pointersRef.current.set(e.pointerId,{x:e.clientX,y:e.clientY});movedRef.current=false;const v=viewportRef.current;if(e.shiftKey&&pointersRef.current.size===1&&!reducedRef.current)tiltRef.current={x:e.clientX,y:e.clientY,tx:v.tiltX,ty:v.tiltY};else dragRef.current={x:e.clientX,y:e.clientY,ox:v.x,oy:v.y};if(pointersRef.current.size===2)beginPinch()};
   const move=(e:PointerEvent)=>{if(!pointersRef.current.has(e.pointerId))return;const prev=pointersRef.current.get(e.pointerId)!;if(distance(prev,{x:e.clientX,y:e.clientY})>2)movedRef.current=true;pointersRef.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const v=viewportRef.current;if(tiltRef.current){viewportRef.current={...v,tiltX:clampTilt(tiltRef.current.tx+(e.clientY-tiltRef.current.y)*.08,14),tiltY:clampTilt(tiltRef.current.ty+(e.clientX-tiltRef.current.x)*.1,18)};draw();return}if(pointersRef.current.size>=2&&pinchRef.current){const ps=[...pointersRef.current.values()],mid=midpoint(ps[0],ps[1]),ratio=distance(ps[0],ps[1])/Math.max(1,pinchRef.current.distance);zoomAround(pinchRef.current.scale*ratio,mid.x,mid.y);return}if(dragRef.current){viewportRef.current={...v,x:dragRef.current.ox+(e.clientX-dragRef.current.x),y:dragRef.current.oy+(e.clientY-dragRef.current.y)};applyViewport()}};
   const up=(e:PointerEvent)=>{pointersRef.current.delete(e.pointerId);tiltRef.current=null;if(pointersRef.current.size<2)pinchRef.current=null;if(!pointersRef.current.size)dragRef.current=null};const wheel=(e:WheelEvent)=>{e.preventDefault();zoomAround(viewportRef.current.scale*Math.exp(-e.deltaY*.0012),e.clientX,e.clientY)};const lost=(e:Event)=>{e.preventDefault();setContextLost(true)};const restored=()=>{setContextLost(false);draw()};
   canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('webglcontextlost',lost);canvas.addEventListener('webglcontextrestored',restored);const resize=new ResizeObserver(draw);resize.observe(host);draw();if(!reducedRef.current){world.alpha=0;gsap.to(world,{alpha:1,duration:.4,ease:'power2.out'})}
   cleanup=()=>{resize.disconnect();media.removeEventListener?.('change',motion);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);app.destroy(true);appRef.current=null;worldRef.current=null;redrawRef.current=null};
  }).catch(()=>setRuntimeError(true));return()=>{disposed=true;cleanup()}
 },[]);
 useEffect(()=>{redrawRef.current?.()},[projection,learningEdges,learning,selectedId,selectedEdgeId]);
 const zoom=(f:number)=>{const v=viewportRef.current;viewportRef.current={...v,scale:clampGraphZoom(v.scale*f)};redrawRef.current?.()};const center=()=>{viewportRef.current={scale:1,x:0,y:0,tiltX:0,tiltY:0};redrawRef.current?.()};
 return <section className="graph-v2-shell"><div className="graph-v2-toolbar"><div><strong>{projection.nodes.length} nós · {projection.edges.length} relações</strong><span>Canvas orbital · {projection.level}</span></div><div className="graph-v2-controls"><button className={!learning?'active':''} onClick={()=>onToggleLearning?.(false)}>Estrutura</button><button className={learning?'active':''} onClick={()=>onToggleLearning?.(!learning)}>Learning</button><button aria-label="Diminuir zoom" onClick={()=>zoom(.88)}>−</button><button aria-label="Aumentar zoom" onClick={()=>zoom(1.14)}>+</button><button aria-label="Centralizar grafo" onClick={center}>◎</button></div></div><div className="graph-v2-main"><div className="graph-v2-canvas-frame"><div ref={hostRef} className="graph-v2-canvas"/>{runtimeError||contextLost?<div className="graph-v2-runtime-state"><strong>{contextLost?'Contexto gráfico interrompido':'Renderer indisponível'}</strong><span>O Atlas preservou a projeção; recarregue o contexto gráfico.</span></div>:null}</div><aside className={`graph-v2-inspector ${inspectorOpen?'is-open':''}`}><button className="graph-v2-inspector-toggle" onClick={()=>setInspectorOpen(v=>!v)}>{inspectorOpen?'Fechar detalhes':'Detalhes'}</button><div className="graph-v2-inspector-body">{selected?<><span className="panel-kicker">{selected.type}</span><h3>{selected.label}</h3><p>{selected.summary||'Sem descrição publicada.'}</p><dl><div><dt>Status</dt><dd>{displayValue(selected.status)}</dd></div>{Object.entries(selected.metrics||{}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{displayValue(v)}</dd></div>)}</dl></>:selectedEdge?<><span className="panel-kicker">RELAÇÃO LEARNING</span><h3>{selectedEdge.type}</h3><dl><div><dt>Origem</dt><dd>{selectedEdge.source}</dd></div><div><dt>Destino</dt><dd>{selectedEdge.target}</dd></div></dl></>:<><span className="panel-kicker">CANVAS</span><h3>{projection.level}</h3><p>Selecione um nó para inspecionar. O mapa continua livre por trás.</p></>}</div></aside><div className="graph-v2-a11y"><span>Navegação acessível</span>{a11yNodes.map(n=><button key={n.id} aria-label={`Selecionar ${n.label}`} onClick={()=>onSelect(n.id)}>{n.label}</button>)}</div><div className="graph-v2-hint">arraste · zoom · Shift+arraste inclina</div></div></section>
}
