import type {Lang} from '../i18n/state-language.ts';
const pt = {
  decisionFlow: 'Abrir fluxo de decisões', returnWeb: 'Voltar à teia', private: 'Área privada', web: 'Teia', domains: 'Domínios', tests: 'Testes', operations: 'Operação', legacy: 'Outras visões',
  partial: 'Esta leitura está incompleta. As listas mostram apenas os registros disponíveis.', collectionUnavailable: 'Esta coleção não está disponível na leitura atual.',
  loading: 'Carregando a visão…', sourceAt: 'Leitura de', unknown: 'Não registrado nesta leitura.',
  domainsLead: 'Escolha um domínio para acompanhar seus testes, resultados e pendências.',
  domainsEmpty: 'Nenhum domínio foi registrado nesta leitura.', allDomains: 'Todos os domínios',
  all: 'Todos os testes', results: 'Com resultado', pending: 'Com pendências',
  researchLead: 'Resultados e pendências podem se sobrepor quando um teste ainda aguarda revisão.',
  search: 'Buscar teste', searchPlaceholder: 'Pergunta, nome ou identificador', none: 'Nenhum teste neste filtro.',
  openTest: 'Abrir teste', openDomain: 'Ver testes do domínio', more: 'Mostrar mais',
  question: 'Pergunta', result: 'Resultado', limits: 'Limites', progress: 'Execução', review: 'Revisão',
  data: 'Dados', recipe: 'Receita', execution: 'Execução', method: 'Método', prereg: 'Critérios registrados',
  datasets: 'Dados usados', artifacts: 'Artefatos', rawRecipe: 'Receita registrada', recipeRef: 'Referência da receita',
  run: 'Registro da execução', statistics: 'Estatísticas', reviewHistory: 'Histórico de revisão', robustness: 'Verificações de robustez',
  unavailableRecipe: 'A receita não foi registrada nesta leitura. O método e os critérios disponíveis aparecem abaixo.',
  technical: 'Identificadores e fonte', id: 'Identificador', source: 'Fonte', status: 'Estado registrado',
  noResult: 'O resultado ainda não foi registrado nesta leitura.', noTest: 'Este teste não está presente na leitura atual.',
  missing: 'Esta visão não foi encontrada.', back: 'Voltar aos testes', original: 'Abrir visão anterior deste teste',
  operationsLead: 'Esta visão acompanha o estado registrado. As decisões e execuções continuam nos fluxos existentes.',
  running: 'Em execução', blocked: 'Bloqueados', waiting: 'Aguardando', human: 'Precisam de você',
  emptyOperation: 'Nenhum item neste filtro na leitura atual.', reason: 'Motivo', next: 'Próximo passo',
  decision: 'Decisão necessária', executionUnknown: 'Estado de execução não informado', operationEmpty: 'Sem pendências operacionais registradas nesta leitura.',
  viewList: 'Ver lista de testes', instruction: 'Selecione um domínio ou teste na teia para abrir seus detalhes.',
  science: 'Ciência', engineering: 'Engenharia', olympus: 'Olympus', clipped: 'Conteúdo abreviado nesta visão.',
  unavailable: 'Não foi possível abrir esta visão com a leitura atual.', reload: 'Atualizar leitura', refreshing: 'Atualizando…', refreshed: 'Leitura verificada.', refreshError: 'Não foi possível atualizar a leitura.',
};
export type WorkspaceCopy = typeof pt;
export const WORKSPACE_COPY: Record<Lang, WorkspaceCopy> = {'pt-BR': pt, en: {
  decisionFlow: 'Open decision workflow', returnWeb: 'Back to the web', private: 'Private area', web: 'Web', domains: 'Domains', tests: 'Tests', operations: 'Operations', legacy: 'Other views',
  partial: 'This snapshot is incomplete. Lists show only the available records.', collectionUnavailable: 'This collection is unavailable in the current snapshot.',
  loading: 'Loading the view…', sourceAt: 'Snapshot from', unknown: 'Not recorded in this snapshot.',
  domainsLead: 'Choose a domain to follow its tests, results and pending work.', domainsEmpty: 'No domain was recorded in this snapshot.', allDomains: 'All domains',
  all: 'All tests', results: 'With results', pending: 'With pending work', researchLead: 'Results and pending work can overlap when a test is still waiting for review.',
  search: 'Find a test', searchPlaceholder: 'Question, name or identifier', none: 'No tests match this filter.',
  openTest: 'Open test', openDomain: 'View tests in this domain', more: 'Show more',
  question: 'Question', result: 'Result', limits: 'Limits', progress: 'Execution', review: 'Review',
  data: 'Data', recipe: 'Recipe', execution: 'Execution', method: 'Method', prereg: 'Recorded criteria',
  datasets: 'Data used', artifacts: 'Artifacts', rawRecipe: 'Recorded recipe', recipeRef: 'Recipe reference',
  run: 'Execution record', statistics: 'Statistics', reviewHistory: 'Review history', robustness: 'Robustness checks',
  unavailableRecipe: 'The recipe was not recorded in this snapshot. The available method and criteria are shown below.',
  technical: 'Identifiers and source', id: 'Identifier', source: 'Source', status: 'Recorded state',
  noResult: 'The result has not been recorded in this snapshot.', noTest: 'This test is not present in the current snapshot.',
  missing: 'This view was not found.', back: 'Back to tests', original: 'Open the previous view of this test',
  operationsLead: 'This view follows the recorded state. Decisions and execution remain in the existing workflows.',
  running: 'Running', blocked: 'Blocked', waiting: 'Waiting', human: 'Needs you',
  emptyOperation: 'No items match this filter in the current snapshot.', reason: 'Reason', next: 'Next step',
  decision: 'Decision needed', executionUnknown: 'Execution state not informed', operationEmpty: 'No operational work is pending in this snapshot.',
  viewList: 'View test list', instruction: 'Select a domain or test in the web to open its details.',
  science: 'Science', engineering: 'Engineering', olympus: 'Olympus', clipped: 'Content shortened in this view.',
  unavailable: 'This view could not be opened with the current snapshot.', reload: 'Refresh snapshot', refreshing: 'Refreshing…', refreshed: 'Snapshot verified.', refreshError: 'The snapshot could not be refreshed.',
}};
export function domainName(domain: string, lang: Lang) { const m = WORKSPACE_COPY[lang]; return ({SCIENCE:m.science,ENGINEERING:m.engineering,OLYMPUS:m.olympus} as Record<string,string>)[domain] ?? domain; }
