import{useEffect,useMemo,useRef,useState}from'react';
import{ACESFilmicToneMapping,AdditiveBlending,BufferGeometry,Color,ConeGeometry,CylinderGeometry,Float32BufferAttribute,Group,LineBasicMaterial,LineSegments,Mesh,MeshBasicMaterial,PerspectiveCamera,Points,Scene,ShaderMaterial,SphereGeometry,SRGBColorSpace,Vector2,Vector3,WebGLRenderer}from'three';
import{EffectComposer}from'three/examples/jsm/postprocessing/EffectComposer.js';
import{RenderPass}from'three/examples/jsm/postprocessing/RenderPass.js';
import{UnrealBloomPass}from'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import{OrbitControls}from'three/examples/jsm/controls/OrbitControls.js';
import type{AtlasGraphLayer,AtlasMetroModel}from'./atlasAdapter.ts';
import{visibleAtlasIds}from'./atlasAdapter.ts';
// @ts-ignore shared plain JS physics module
import{CONNECTOME_PALETTE,connectomeDomain,layoutNodes,readingDistance,transportedMass}from'./connectomePhysics.mjs';
import'./ConnectomeThree3D.css';
type D='NEXO'|'SCIENCE'|'ENGINEERING'|'OLYMPUS';
type Props={model:AtlasMetroModel;expanded:ReadonlySet<string>;visibleLayers:ReadonlySet<AtlasGraphLayer>;selectedId:string|null;showRelations:boolean;fitNonce:number;onActivate:(id:string)=>void;onReady?:()=>void};
const V=(p:{x:number;y:number;z:number})=>new Vector3(p.x,p.y,p.z),C=(d:D)=>new Color(CONNECTOME_PALETTE[d]);
const done=(s:string)=>/RESULT|DONE|COMPLETE|COMPLETED|CONFIRMED|SUPPORTED|VERIFIED/i.test(s),ready=(s:string)=>/READY/i.test(s),blocked=(s:string)=>/BLOCKED|FAIL|ERROR|MISSING/i.test(s);
const growV=`uniform float uHalo,uNetwork;uniform vec3 uBary;void main(){vec4 w=modelMatrix*vec4(position*uHalo,1.);w.xyz=uBary+(w.xyz-uBary)*uNetwork;gl_Position=projectionMatrix*viewMatrix*w;}`;
const growF=`uniform vec3 uColor;uniform float uOpacity;void main(){gl_FragColor=vec4(uColor,uOpacity);}`;
const grow=(color:Color,opacity:number,halo:number,network:number,bary:Vector3)=>new ShaderMaterial({uniforms:{uColor:{value:color},uOpacity:{value:opacity},uHalo:{value:halo},uNetwork:{value:network},uBary:{value:bary}},vertexShader:growV,fragmentShader:growF,transparent:true,depthWrite:false,blending:AdditiveBlending});
const pulseV=`uniform float uTime;attribute float phase;attribute float speed;varying float a;void main(){vec3 p=position+normal*fract(uTime*speed+phase);a=.5+.5*sin(fract(uTime*speed+phase)*3.14159);gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);gl_PointSize=5.;}`;
const pulseF=`varying float a;void main(){vec2 q=gl_PointCoord-.5;gl_FragColor=vec4(1.,1.,1.,smoothstep(.5,.05,length(q))*a);}`;
function branch(a:Vector3,b:Vector3,r0:number,r1:number,color:Color,opacity:number){const d=new Vector3().subVectors(b,a),g=new CylinderGeometry(r1,r0,Math.max(.01,d.length()),6);const m=new Mesh(g,new MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new Vector3(0,1,0),d.normalize());return m}
export function ConnectomeThree3D({model,expanded,visibleLayers,selectedId,showRelations,fitNonce,onActivate,onReady}:Props){
 const host=useRef<HTMLDivElement|null>(null),[distance,setDistance]=useState<'panorama'|'estrutura'|'detalhe'>('panorama');
 const visible=useMemo(()=>new Set(visibleAtlasIds(model,expanded,visibleLayers)),[model.revision,expanded,visibleLayers]),layout=useMemo(()=>layoutNodes(model),[model.revision]);
 useEffect(()=>{const mount=host.current;if(!mount)return;let renderer:WebGLRenderer|undefined,composer:EffectComposer|undefined,frame=0;const clean:Array<()=>void>=[];
 try{renderer=new WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.outputColorSpace=SRGBColorSpace;renderer.toneMapping=ACESFilmicToneMapping;renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(Math.max(1,mount.clientWidth),Math.max(1,mount.clientHeight),false);renderer.domElement.className='connectome-three-canvas';renderer.domElement.setAttribute('aria-label','Conectoma 3D do NEXO');mount.replaceChildren(renderer.domElement);
 const scene=new Scene(),camera=new PerspectiveCamera(42,mount.clientWidth/Math.max(1,mount.clientHeight),.1,1800);camera.position.set(0,44,410);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=55;controls.maxDistance=650;const root=new Group();scene.add(root);
 const domains=['NEXO','SCIENCE','ENGINEERING','OLYMPUS']as D[],centers=domains.map(d=>V(layout.centers[d])),bary=centers.reduce((s,p)=>s.add(p),new Vector3()).multiplyScalar(.25),tests=model.nodes.filter(n=>String(n.entityType)==='TEST'),completedAll=tests.filter(n=>done(n.status)).length,network=1+Math.min(.16,completedAll/Math.max(1,tests.length)*.16),guardianWait=model.nodes.some(n=>/GUARDIAN/i.test(`${n.id} ${n.name} ${n.summary}`)&&/WATCH|YELLOW|FAIL|BLOCKED/i.test(n.status));
 for(const d of domains){const p=V(layout.centers[d]),mass=Math.max(1,layout.masses[d]||1),r=4.5+Math.cbrt(mass)*1.9,dt=tests.filter(n=>connectomeDomain(n)===d),completed=dt.filter(n=>done(n.status)).length,rd=dt.filter(n=>ready(n.status)).length,wait=(dt.length>0&&completed===0&&rd===0)||(d==='NEXO'&&guardianWait);const soma=new Mesh(new SphereGeometry(r,24,18),grow(C(d),.93,1,network,bary));soma.position.copy(p);root.add(soma);
  if(completed){const halo=new Mesh(new SphereGeometry(r,20,14),grow(C(d),.1,1.12+Math.min(.5,completed/Math.max(1,dt.length)*.5),network,bary));halo.position.copy(p);root.add(halo)}
  if(wait){const burst=new Mesh(new SphereGeometry(r*1.58,20,14),new MeshBasicMaterial({color:C(d),transparent:true,opacity:.18,blending:AdditiveBlending,depthWrite:false}));burst.position.copy(p);burst.userData.sustained=true;root.add(burst)}}
 for(const n of model.nodes){if(!n.parentId||!visible.has(n.id)||!visible.has(n.parentId))continue;const a=layout.positions.get(n.parentId),b=layout.positions.get(n.id);if(!a||!b)continue;const m=transportedMass(n.id,model.childrenMap),r0=Math.min(1.45,.12+Math.sqrt(m)*.105),bad=blocked(n.status),x=branch(V(a),V(b),r0,Math.max(.045,r0*.34),bad?new Color('#777b80'):C(connectomeDomain(n)as D),bad ? .28 : .68);x.userData={nodeId:n.id,kind:'OWNS'};root.add(x)}
 for(const n of model.nodes){if(!visible.has(n.id))continue;const p=layout.positions.get(n.id);if(!p)continue;const d=connectomeDomain(n)as D,bad=blocked(n.status),isTest=String(n.entityType)==='TEST',r=Math.max(.8,2.5-Math.min(1.4,n.depth*.35)),body=new Mesh(new SphereGeometry(r,10,8),new MeshBasicMaterial({color:bad?new Color('#73777b'):C(d),transparent:true,opacity:n.id===selectedId?1:bad ? .38 : .78,depthWrite:false}));body.position.copy(V(p));body.userData.nodeId=n.id;root.add(body);
  if(isTest&&done(n.status)){const myelin=new Mesh(new SphereGeometry(r*1.75,12,9),new MeshBasicMaterial({color:C(d),transparent:true,opacity:.2,blending:AdditiveBlending,depthWrite:false}));myelin.position.copy(V(p));root.add(myelin)}
  if(isTest&&ready(n.status)){const cone=new Mesh(new ConeGeometry(r*1.7,r*3.5,7),new MeshBasicMaterial({color:C(d),transparent:true,opacity:.9}));cone.position.copy(V(p)).add(new Vector3(0,r*2.3,0));root.add(cone);const g=new BufferGeometry(),vs:number[]=[];for(let i=0;i<6;i++){const q=V(p).add(new Vector3(0,r*4,0)),e=q.clone().add(new Vector3(Math.cos(i*Math.PI/3)*r*3,r*2,Math.sin(i*Math.PI/3)*r*3));vs.push(q.x,q.y,q.z,e.x,e.y,e.z)}g.setAttribute('position',new Float32BufferAttribute(vs,3));root.add(new LineSegments(g,new LineBasicMaterial({color:C(d),transparent:true,opacity:.55})))}}
 const pp:number[]=[],pn:number[]=[],ph:number[]=[],ps:number[]=[];
 for(const link of model.crossLinks){if(!showRelations||!visible.has(link.source)||!visible.has(link.target))continue;const a=layout.positions.get(link.source),b=layout.positions.get(link.target);if(!a||!b)continue;const sd=connectomeDomain(model.nodeMap.get(link.source))as D,td=connectomeDomain(model.nodeMap.get(link.target))as D,g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute([a.x,a.y,a.z,b.x,b.y,b.z],3));const supports=/SUPPORTS/i.test(link.kind),learning=link.isLearning,color=learning?C(sd):supports?new Color('#b6bdc4'):new Color('#7d858d');root.add(new LineSegments(g,grow(color,learning ? .58 : supports ? .34 : .18,1,network,bary)));
  if(learning&&sd!==td){const conduction=/ESTABLISHED/i.test(link.label)?1:/TESTING/i.test(link.label) ? .24 : .5,cadence=Math.max(.025,Math.min(.46,(Number(link.weight)||.5)*conduction*.19));for(let k=0;k<Math.max(1,Math.round(1+(Number(link.weight)||0)*2));k++){pp.push(a.x,a.y,a.z);pn.push(b.x-a.x,b.y-a.y,b.z-a.z);ph.push(k/3);ps.push(cadence)}}}
 const pg=new BufferGeometry();pg.setAttribute('position',new Float32BufferAttribute(pp,3));pg.setAttribute('normal',new Float32BufferAttribute(pn,3));pg.setAttribute('phase',new Float32BufferAttribute(ph,1));pg.setAttribute('speed',new Float32BufferAttribute(ps,1));const pm=new ShaderMaterial({uniforms:{uTime:{value:0}},vertexShader:pulseV,fragmentShader:pulseF,transparent:true,depthWrite:false,blending:AdditiveBlending});root.add(new Points(pg,pm));
 composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new Vector2(mount.clientWidth,mount.clientHeight),.64,.5,.18));
 const targets=root.children.filter(x=>x.userData?.nodeId),projected=new Vector3(),click=(e:MouseEvent)=>{const rect=renderer!.domElement.getBoundingClientRect();let best:{id:string;d:number}|null=null;for(const o of targets){projected.copy(o.position).project(camera);const x=rect.left+(projected.x*.5+.5)*rect.width,y=rect.top+(-projected.y*.5+.5)*rect.height,d=Math.hypot(e.clientX-x,e.clientY-y);if(d<18&&(!best||d<best.d))best={id:o.userData.nodeId,d}}if(best)onActivate(best.id)};renderer.domElement.addEventListener('click',click);clean.push(()=>renderer?.domElement.removeEventListener('click',click));
 const resize=()=>{if(!renderer)return;const w=Math.max(1,mount.clientWidth),h=Math.max(1,mount.clientHeight);renderer.setSize(w,h,false);composer?.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()},ro=new ResizeObserver(resize);ro.observe(mount);clean.push(()=>ro.disconnect());
 const render=(t:number)=>{frame=requestAnimationFrame(render);controls.update();pm.uniforms.uTime.value=t/1000;const rd=readingDistance(camera.position.distanceTo(controls.target));setDistance(x=>x===rd?x:rd);composer?.render()};frame=requestAnimationFrame(render);onReady?.();return()=>{cancelAnimationFrame(frame);clean.forEach(f=>f());controls.dispose();composer?.dispose();renderer?.dispose();mount.replaceChildren()}}
 catch(e){console.error('[connectome-3d]',e);onReady?.();return()=>{cancelAnimationFrame(frame);clean.forEach(f=>f());composer?.dispose();renderer?.dispose();mount.replaceChildren()}}},[model.revision,visible,selectedId,showRelations,fitNonce,onActivate,onReady,layout]);
 const m=layout.masses as Record<D,number>;return <div className="connectome-shell" data-reading-distance={distance}><div ref={host} className="connectome-host"/><aside className="connectome-reading-card" aria-label="Carta de leitura do conectoma"><strong>Conectoma · como ler</strong><span><b>Soma</b> domínio; tamanho = massa OWNS.</span><span><b>Dendrite</b> OWNS; espessura = √ massa transportada.</span><span><b>Mielina</b> concluído. <b>Cone</b> READY. <b>Podado</b> BLOCKED.</span><span><b>Axónio</b> filamento; pulsos = cadência × condução. <b>Colateral</b> SUPPORTS.</span><span><b>Rajada contínua</b> espera decisão/zero elegíveis; não expira.</span><span><b>Crescimento</b> halo = concluídos; rede dilata desde o baricentro, sem herdar halo.</span><small>Leitura: {distance} · N {m.NEXO||0} · C {m.SCIENCE||0} · E {m.ENGINEERING||0} · O {m.OLYMPUS||0}</small></aside></div>
}