import test from 'node:test';
import assert from 'node:assert/strict';
import {drive,gmail,calendar} from '../server/adapters/google.mjs';
import {github} from '../server/adapters/github.mjs';
import {vercel} from '../server/adapters/vercel.mjs';
import {nexo} from '../server/adapters/nexo.mjs';
import {validateItem} from '../src/contracts/validate.mjs';
const now=Date.parse('2026-09-09T12:00:00Z');
const env={GOOGLE_CLIENT_ID:'fixture',GOOGLE_CLIENT_SECRET:'fixture',GOOGLE_REFRESH_TOKEN:'fixture',VERCEL_READ_TOKEN:'fixture',VERCEL_PROJECT_ID:'prj_fixture',NEXO_SOURCE_URL:'https://source.example/export'};
async function mock(routes,fn){const original=globalThis.fetch;globalThis.fetch=async(url,options)=>{const found=routes.find(([match])=>String(url).includes(match));assert.ok(found,`Unexpected outbound request: ${url}`);const value=typeof found[1]==='function'?found[1](url,options):found[1];return new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});};try{return await fn();}finally{globalThis.fetch=original;}}
const oauth=['oauth2.googleapis.com',{access_token:'fixture-access',expires_in:3600}];
test('Drive normalizes paginated files and safely escapes search query',async()=>mock([oauth,['drive/v3/files',(url)=>{assert.match(new URL(url).searchParams.get('q'),/name contains/);return {nextPageToken:'next',files:[{id:'f1',name:'CAMB input',modifiedTime:'2026-09-08T10:00:00Z',version:'1'}]};}]],async()=>{const x=await drive({env,now,query:"O'Hara"});assert.equal(x.partial,true);assert.equal(x.items[0].contextId,'COSMOLOGY');assert.equal(validateItem(x.items[0],'drive'),true);}));
test('Gmail metadata does not invent actionable commitments',async()=>mock([oauth,['/messages/m1',{id:'m1',threadId:'t1',payload:{headers:[{name:'Subject',value:'Revisão CAMB'},{name:'From',value:'Fixture sender'}]}}],['/messages?',{messages:[{id:'m1'}]}]],async()=>{const x=await gmail({env,now});assert.equal(x.items[0].status,undefined);assert.equal(validateItem(x.items[0],'gmail'),true);}));
test('Calendar excludes canceled and self-declined events, retains all-day exclusive end',async()=>mock([oauth,['/events?',{items:[{id:'a',summary:'Appointment',htmlLink:'https://calendar.google.com/event?eid=a',start:{date:'2026-09-09'},end:{date:'2026-09-10'}},{id:'b',status:'cancelled'},{id:'c',attendees:[{self:true,responseStatus:'declined'}]}]}]],async()=>{const x=await calendar({env,now});assert.equal(x.items.length,1);assert.equal(x.items[0].allDay,true);assert.equal(validateItem(x.items[0],'calendar'),true);}));
test('GitHub derives assignment only from explicit assignees and blockers from labels',async()=>mock([['/issues?', [{number:1,title:'Fix',html_url:'https://github.com/byDenoso/Pantheon/issues/1',state:'open',assignees:[{login:'byDenoso'}],labels:[]},{number:2,title:'Blocked',html_url:'https://github.com/byDenoso/Pantheon/issues/2',state:'open',labels:[{name:'blocked'}]}]],['/repos/',{full_name:'byDenoso/Pantheon',html_url:'https://github.com/byDenoso/Pantheon',pushed_at:'2026-09-09T10:00:00Z'}]],async()=>{const x=await github({env:{},now});assert.equal(x.items[1].status,'NEEDS_ME');assert.equal(x.items[2].status,'BLOCKED');assert.ok(x.items.every(i=>validateItem(i,'github')));}));
test('Vercel failure history is contextual, not an invented current blocker',async()=>mock([['/deployments?',{deployments:[{uid:'dpl_fixture',name:'nexo-one',state:'ERROR',created:now}],pagination:{next:null}}]],async()=>{const x=await vercel({env,now});assert.equal(x.items[0].status,undefined);assert.equal(validateItem(x.items[0],'vercel'),true);}));
test('NEXO requires versioned owner export and never re-stamps it',async()=>mock([['source.example',{version:'1',revision:'r1',items:[{id:'nexo:a',observedAt:'2026-01-01T00:00:00Z'}]}]],async()=>{const x=await nexo({env});assert.equal(x.items[0].observedAt,'2026-01-01T00:00:00Z');assert.equal(x.revision,'r1');}));
