import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../server/handler.mjs';
import {makeSession} from '../server/auth/session.mjs';
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(value){this.body=JSON.parse(value);}};}
const routes=['world','system','atlas-private','atlas-public-ssot','mcp','mcp/status','projection-sync','google-drive-consent','inbox-drop','projections'];
test('real handler denies anonymous and forged legacy sessions before upstream reads',async()=>{const oldFetch=globalThis.fetch;let reads=0;globalThis.fetch=async()=>{reads++;throw Error('unexpected upstream');};try{for(const route of routes){const res=response();await handler({url:`/api/index?route=${route}`,method:'GET',headers:{cookie:'nexo_session=forged'}},res);assert.ok([401,403].includes(res.statusCode),`${route}: ${res.statusCode}`);assert.deepEqual(Object.keys(res.body),['error']);assert.equal(res.headers['Cache-Control'],'private, no-store');}assert.equal(reads,0);}finally{globalThis.fetch=oldFetch;}});
test('valid legacy cookie alone cannot access consent metadata',async()=>{const previous={secret:process.env.NEXO_SESSION_SECRET,hash:process.env.NEXO_PASSWORD_HASH};process.env.NEXO_SESSION_SECRET='synthetic-secret-at-least-32-characters';process.env.NEXO_PASSWORD_HASH='synthetic-test-hash';try{const token=makeSession(process.env);for(const route of ['google-drive-consent']){const res=response();await handler({url:`/api/${route}`,method:'GET',headers:{cookie:`nexo_session=${token}`}},res);assert.equal(res.statusCode,401);assert.deepEqual(res.body,{error:'AUTH_REQUIRED'});}}finally{if(previous.secret===undefined)delete process.env.NEXO_SESSION_SECRET;else process.env.NEXO_SESSION_SECRET=previous.secret;if(previous.hash===undefined)delete process.env.NEXO_PASSWORD_HASH;else process.env.NEXO_PASSWORD_HASH=previous.hash;}});
test('public route never calls adapters or returns a previous private cache',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected upstream');};try{for(const cookie of ['', 'nexo_session=forged','__Host-atlas_session='+'a'.repeat(64)]){const res=response();await handler({url:'/api/atlas-public',method:'GET',headers:{cookie}},res);assert.equal(res.statusCode,200);assert.deepEqual(res.body,{contract:'ATLAS_PUBLIC_V1',items:[],links:[]});assert.equal(res.headers['Cache-Control'],'private, no-store');assert.match(res.headers.Vary,/Cookie/);}}finally{globalThis.fetch=oldFetch;}});
test('missing configured shared store returns 503 without private reads',async()=>{const res=response();await handler({url:'/api/atlas-session',method:'POST',headers:{origin:'https://atlas.example','content-type':'application/json'},body:{pin:'synthetic-only-passphrase'}},res);assert.equal(res.statusCode,503);assert.deepEqual(res.body,{error:'AUTH_NOT_CONFIGURED'});});
