// Synthetic-only UI regression: compact reading never rewrites the source record.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { labVisualFixture } from './lab-visual-fixture.mjs';
import { buildPagesProjection } from '../scripts/build-pages-system.mjs';
const base = process.env.NEXO_BASE_URL || 'http://127.0.0.1:4178';
const output = 'test-output/compact-reading';
await mkdir(output, { recursive: true });
const projection = labVisualFixture();
const title = 'Título original completo da verificação com entradas congeladas e resultado independente para preservar todas as palavras do registro publicado';
const question = 'Pergunta original literal: este resultado atende ao contrato previamente publicado?';
projection.tests.find(t => t.id === 'VISUAL-CONFIRMED').semantic = { display_name: title, question_plain: question };
projection.tests.find(t => t.id === 'VISUAL-BLOCKED-0').readiness = { eligible: false, reasons: ['FIXTURE_ONLY'] };
const { system } = buildPagesProjection({ projection, manifestFile: projection.manifest });
const op = { policy: 'INCIDENT_OPERATIONS_V1', state: 'OPEN', work_ids: ['WORK-UX'], items: [{ work_id: 'WORK-UX', test_id: null, current_owner: 'GUARDIAO', assigned_to: 'EXECUTOR', ownership_state: 'ASSIGNED_UNACCEPTED', accepted: false, validation_state: 'EVIDENCE_REQUIRED' }], suggested_owner: 'EXECUTOR', reason_code: 'READY_INPUTS_NOT_MATERIALIZED', next_action_code: 'COMPLETE_RECOVERY', resolution_scope: null, scientific_effect: 'NONE' };
const incident = { incident_id: 'INC-UX-OPEN', summary_plain: 'Entradas da fixture ainda não materializadas; preservar a descrição original e todas as evidências publicadas.', state: 'CONFIRMED', next_owner: 'LEARNER', evidence_count: 3, public_ids: { tests: ['VISUAL-BLOCKED-0'], hypotheses: [], lessons: [] }, operational: op };
system.evolution.incidents = [incident, { ...incident, incident_id: 'INC-UX-RESOLVED', summary_plain: 'Recuperação concluída na fixture.', operational: { ...op, state: 'RESOLVED', resolution_scope: 'EXECUTION_PREREQUISITES' } }];
const browser = await chromium.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const reports = [];
try {
 for (const theme of ['dark','light']) for (const width of [1440,390]) {
  const context = await browser.newContext({ viewport: { width, height: 900 }, reducedMotion: 'reduce', deviceScaleFactor: 1 });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.clock.install({ time: Date.parse(projection.manifest.generated_at) + 60_000 });
  await page.addInitScript(theme => { localStorage.setItem('nexo-theme', theme); localStorage.setItem('nexo.intro.seen','1'); localStorage.setItem('nexo.legend.seen','1'); localStorage.setItem('nexo.quality','low'); }, theme);
  let fail = false, fingerprint = system.bus.fingerprint;
  await page.route('**/api/session', r => r.fulfill({ json: { configured:false, authenticated:false } }));
  await page.route('**/api/system*', r => fail ? r.fulfill({ status:503, json:{ error:'FIXTURE_UNAVAILABLE' } }) : r.fulfill({ json:system }));
  await page.route('**/build-meta.json*', r => r.fulfill({ json:{ projection_fingerprint:fingerprint } }));
  const go = async route => { await page.evaluate(route => { location.hash = '#/' + route; }, route); await page.locator('.observatory .hud').waitFor(); };
  await page.goto(base + '/#/evidencia?v=READY');
  await page.locator('.queue-empty').waitFor();
  assert.match(await page.locator('.queue-empty').innerText(), /Nenhum teste pronto nesta leitura/);
  await page.getByLabel('Buscar testes', { exact:true }).fill('ausente-fixture');
  await page.getByRole('button', { name:'Limpar busca', exact:true }).click();
  assert.equal(await page.getByLabel('Buscar testes', { exact:true }).inputValue(),'');
  await page.locator('.queue-empty').getByRole('link', { name:'Ver bloqueados', exact:true }).click();
  await page.locator('.ev-group[aria-label="Bloqueado"]').waitFor();
  await go('e/VISUAL-CONFIRMED');
  await page.locator('.h1-entity').waitFor();
  assert.ok((await page.locator('.h1-entity').innerText()).length < title.length);
  assert.match(await page.locator('#en-mean').locator('..').innerText(), /confirmad/i);
  const story = page.locator('.entity-story'), summary = story.locator(':scope > summary');
  assert.equal(await story.getAttribute('open'), null);
  await summary.focus(); await page.keyboard.press('Enter');
  assert.notEqual(await story.getAttribute('open'), null);
  assert.equal(await story.locator('.original-test-title').textContent(), title);
  assert.equal(await story.locator('.original-test-question').textContent(), question);
  await summary.focus(); await page.keyboard.press('Enter');
  assert.equal(await story.getAttribute('open'), null);
  await go('saude');
  await page.locator('.incident-owner').first().waitFor();
  const pending = page.locator('#he-inc').locator('..').locator(':scope > .incidents > .incident');
  assert.equal(await pending.count(),1, 'learning confirmation does not resolve an open operation');
  assert.match(await pending.locator('.incident-owner').innerText(), /aceite ainda não registrado/);
  assert.doesNotMatch(await pending.locator('.incident-owner').innerText(), /com aceite registrado:/);
  await pending.locator('.incident-ownership > summary').click();
  assert.match(await pending.locator('.incident-ownership').innerText(), /Papel sugerido: Executor · sugestão, sem atribuição/);
  await pending.locator('.incident-evidence > summary').click();
  assert.equal(await pending.locator('.incident-original').textContent(), incident.summary_plain);
  assert.equal(await pending.locator('.incident-links a').getAttribute('href'), '#/e/VISUAL-BLOCKED-0');
  const history = page.locator('.incident-history');
  assert.equal(await history.getAttribute('open'),null);
  await history.locator(':scope > summary').click();
  assert.equal(await history.locator('.incident-state').textContent(), 'Resolvido operacionalmente');
  await go('ciclo');
  await page.locator('.cycle-flow').waitFor();
  assert.deepEqual(await page.locator('.cycle-flow strong').allTextContents(), ['PREPARO','EXECUÇÃO','CONTESTAÇÃO','CONSOLIDAÇÃO']);
  assert.equal(await page.locator('.cycle-flow .is-blocked').count(),0, 'readiness=false alone does not establish the blocked cycle stage');
  assert.match(await page.locator('.hud').innerText(), /etapa do bloqueio não foi publicada/);
  assert.equal(await page.locator('.cycle-role-details').getAttribute('open'),null);
  await page.locator('.cycle-role-details > summary').click();
  await page.locator('.crew').waitFor();
  await go('agora');
  await page.locator('.now-overview').waitFor();
  assert.equal(await page.locator('.now-overview a').count(),1);
  // A failed heartbeat refresh must preserve the last valid source, with an explicit warning.
  fail = true; fingerprint = 'sha256:' + '8'.repeat(64);
  const failedRead = page.waitForResponse(r => r.url().includes('/api/system') && r.status() === 503);
  await page.clock.fastForward(21_000); await failedRead;
  await page.locator('.lab-reading-warning').waitFor();
  await go('e/VISUAL-CONFIRMED');
  await page.locator('.h1-entity').waitFor();
  await page.locator('.entity-story > summary').click();
  assert.equal(await page.locator('.original-test-title').textContent(), title, 'last good source survives refresh failure');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1),false);
  assert.deepEqual(errors,[]);
  await page.screenshot({ path:output + '/' + theme + '-' + width + '.png' });
  reports.push({ input:'synthetic-test-only',theme,width,originalPreserved:true,ownership:true,history:true,keyboard:true,readyEmpty:true,lastGood:true,errors });
  await context.close();
 }
} finally { await browser.close(); }
await writeFile(output + '/report.json', JSON.stringify(reports,null,2));
console.log('COMPACT_READING ' + JSON.stringify(reports));
