import { projects as seedProjects, dependencies as seedDependencies, statusMeta, domainColors } from './data.js';
import { createRepository, filterProjects, summarizeProjects, validateManifest } from './store.js';
import { AtlasRenderer } from './atlas.js';

const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let storage=null; try{storage=localStorage}catch{}
const repo=createRepository(seedProjects,seedDependencies,storage);
const state={view:'atlas',selectedId:repo.list()[0]?.id||null,search:'',domains:new Set(),statuses:new Set(),priorities:new Set()};
const el={summary:$('#summaryBar'),canvas:$('#atlasCanvas'),detail:$('#projectDetail'),domain:$('#domainFilters'),status:$('#statusFilters'),priority:$('#priorityFilters'),global:$('#globalSearch'),side:$('#sideSearch'),title:$('#atlasTitle'),subtitle:$('#atlasSubtitle'),empty:$('#emptyAtlas'),legend:$('#atlasLegend'),list:$('#listView'),timeline:$('#timelineView'),artifacts:$('#artifactsView'),dependencies:$('#dependenciesView'),insights:$('#insightsView'),dialog:$('#projectDialog'),form:$('#projectForm'),file:$('#manifestFile'),toast:$('#toast'),drawer:$('.detail-sidebar')};
const atlas=new AtlasRenderer(el.canvas,{onSelect:id=>select(id,true)}); let toastTimer;
const all=()=>repo.list(), visible=()=>filterProjects(all(),state), selected=()=>repo.get(state.selectedId)||all()[0]||null;
const label=s=>statusMeta[s]?.label||s, color=p=>domainColors[p.domain]||'#4f9dff';
function notify(msg){clearTimeout(toastTimer);el.toast.textContent=msg;el.toast.classList.add('visible');toastTimer=setTimeout(()=>el.toast.classList.remove('visible'),1800)}
function formatDate(v){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:String(v).includes('T')?'short':undefined}).format(new Date(v))}catch{return v}}
function setView(view){state.view=view;$$('.nav-tab,.side-view').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view-panel').forEach(p=>p.classList.toggle('active',p.id===`${view}View`));renderView()}
function select(id,open=false){state.selectedId=id;atlas.setSelected(id);renderDetail();if(open&&innerWidth<1180)el.drawer.classList.add('open')}
function header(title,sub,actions=''){return `<div class="content-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="content-actions">${actions}</div></div>`}
function renderSummary(){const s=summarizeProjects(all());const cards=[['Projetos',s.projects,'#59f08a'],['Artefatos',s.artifacts,'#43a6ff'],['Repositórios',s.repositories,'#ffbd3d'],['Documentos',s.documents,'#b25cff'],['Runs / Testes',s.runs,'#28d7c0'],['Datasets',s.datasets,'#ff5ebc']];el.summary.innerHTML=cards.map(([k,v,c])=>`<div class="summary-card" style="--accent:${c}"><strong>${v}</strong><span>${k.toUpperCase()}</span></div>`).join('')}
function renderFilters(){const items=all(),domains=[...new Set(items.map(p=>p.domain))].sort(),count=(k,v)=>items.filter(p=>p[k]===v).length;el.domain.innerHTML=`<div class="filter-heading"><span>DOMÍNIO</span><span>${domains.length}</span></div>`+domains.map(d=>`<label class="filter-item"><input type="checkbox" data-filter="domain" value="${esc(d)}" ${state.domains.has(d)?'checked':''}><span class="filter-dot" style="background:${domainColors[d]||'#789'}"></span><span>${esc(d)}</span><span class="filter-count">${count('domain',d)}</span></label>`).join('');el.status.innerHTML=`<div class="filter-heading"><span>STATUS</span><span>5</span></div>`+Object.entries(statusMeta).map(([s,m])=>`<label class="filter-item"><input type="checkbox" data-filter="status" value="${s}" ${state.statuses.has(s)?'checked':''}><span class="filter-dot" style="background:${m.color}"></span><span>${m.label}</span><span class="filter-count">${count('status',s)}</span></label>`).join('');el.priority.innerHTML=`<div class="filter-heading"><span>PRIORIDADE</span><span>5</span></div>`+[5,4,3,2,1].map(p=>`<label class="filter-item"><input type="checkbox" data-filter="priority" value="${p}" ${state.priorities.has(p)?'checked':''}><span class="filter-dot" style="background:#ffbd3d"></span><span>${p}</span><span class="filter-count">${count('priority',p)}</span></label>`).join('');$$('[data-filter]').forEach(i=>i.onchange=()=>{const set=i.dataset.filter==='domain'?state.domains:i.dataset.filter==='status'?state.statuses:state.priorities,v=i.dataset.filter==='priority'?+i.value:i.value;i.checked?set.add(v):set.delete(v);renderAll(false)})}
function renderAtlas(){const items=visible(),ids=new Set(items.map(p=>p.id)),deps=repo.dependencies().filter(([a,b])=>ids.has(a)&&ids.has(b));if(!ids.has(state.selectedId)&&items[0])state.selectedId=items[0].id;atlas.setData(items,deps,state.selectedId);el.title.textContent=items.length===all().length?'Ecossistema completo':'Visão filtrada';el.subtitle.textContent=`${items.length} de ${all().length} projetos · ${deps.length} conexões`;el.empty.classList.toggle('hidden',items.length>0)}
function renderDetail(){const p=selected();if(!p){el.detail.innerHTML='<div class="empty-state">Nenhum projeto.</div>';return}const metrics=[['Artefatos',p.metrics.artifacts],['Repos',p.metrics.repositories],['Docs',p.metrics.documents],['Runs',p.metrics.runs],['Datasets',p.metrics.datasets],['Complex.',p.metrics.complexity]];el.detail.innerHTML=`<div class="project-identity" style="color:${color(p)}"><div class="project-color"></div><div><h2>${esc(p.name)}</h2><p>${esc(p.domain)}</p></div><span class="status-badge" style="color:${statusMeta[p.status]?.color}">${label(p.status)}</span></div><div class="detail-section"><div class="detail-meta"><div class="meta-item"><span>PRIORIDADE</span><b class="priority-stars">${'★'.repeat(p.priority)}${'☆'.repeat(5-p.priority)}</b></div><div class="meta-item"><span>ATUALIZAÇÃO</span><b>${formatDate(p.updatedAt)}</b></div></div></div><div class="detail-section"><h3>RESUMO</h3><p>${esc(p.summary)}</p></div><div class="detail-section"><h3>CLAIM CENTRAL</h3><p>${esc(p.claim||'Claim ainda não definida.')}</p></div><div class="detail-section"><h3>PRÓXIMA AÇÃO</h3><p class="next-action">${esc(p.nextAction)}</p></div><div class="detail-section"><h3>RESUMO RÁPIDO</h3><div class="metric-mini-grid">${metrics.map(([k,v])=>`<div class="metric-mini"><strong>${v}</strong><span>${k}</span></div>`).join('')}</div></div><div class="detail-section"><h3>FONTES CANÔNICAS</h3><div class="source-list">${p.sources.length?p.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noreferrer"><span>${esc(s.type)} · ${esc(s.label)}</span><b>ABRIR</b></a>`).join(''):'<p>Nenhuma URL registrada.</p>'}</div></div><div class="detail-section"><h3>ATIVIDADE RECENTE</h3><div class="activity-list">${(p.activity||[]).map(a=>`<div class="activity-item"><b>${esc(a.date)}</b>${esc(a.text)}</div>`).join('')}</div></div><div class="detail-actions"><button class="secondary-button" id="editSelected">EDITAR</button><button class="primary-button" id="openPrimarySource" ${p.sources.length?'':'disabled'}>ABRIR FONTE</button></div>`;$('#editSelected').onclick=()=>openDialog(p);$('#openPrimarySource').onclick=()=>p.sources[0]&&open(p.sources[0].url,'_blank','noopener')}
function bindRows(root){$$('[data-project-id]',root).forEach(r=>r.onclick=()=>select(r.dataset.projectId,true))}
function bindRepoActions(root){$$('[data-action="export"]',root).forEach(b=>b.onclick=exportManifest);$$('[data-action="import"]',root).forEach(b=>b.onclick=()=>el.file.click())}
function renderList(){const items=visible();el.list.innerHTML=`<div class="content-card">${header('Lista Operacional',`${items.length} projetos visíveis`,`<button class="secondary-button" data-action="import">IMPORTAR JSON</button><button class="primary-button" data-action="export">EXPORTAR MANIFESTO</button>`)}<div style="overflow:auto"><table class="data-table"><thead><tr><th>Projeto</th><th>Domínio</th><th>Status</th><th>P</th><th>Artefatos</th><th>Runs</th><th>Atualização</th><th>Próxima ação</th></tr></thead><tbody>${items.map(p=>`<tr data-project-id="${p.id}"><td><span class="table-project">${esc(p.name)}</span></td><td>${esc(p.domain)}</td><td><span class="table-status" style="color:${statusMeta[p.status]?.color}">${label(p.status)}</span></td><td>${p.priority}</td><td>${p.metrics.artifacts}</td><td>${p.metrics.runs}</td><td>${formatDate(p.updatedAt)}</td><td>${esc(p.nextAction)}</td></tr>`).join('')}</tbody></table></div></div>`;bindRows(el.list);bindRepoActions(el.list)}
function renderTimeline(){const events=visible().flatMap(p=>(p.activity||[]).map(a=>({...a,project:p}))).sort((a,b)=>String(b.date).localeCompare(String(a.date)));el.timeline.innerHTML=`<div class="content-card">${header('Linha do Tempo','Eventos registrados no manifesto canônico')}<div class="timeline-list">${events.map(e=>`<div class="timeline-row" data-project-id="${e.project.id}"><time>${esc(e.date)}</time><b>${esc(e.project.name)}</b><p>${esc(e.text)}</p><span class="tag">${esc(e.kind)}</span></div>`).join('')}</div></div>`;bindRows(el.timeline)}
function renderArtifacts(){const cards=visible().flatMap(project=>project.sources.map(source=>({project,source})));el.artifacts.innerHTML=`<div class="content-card">${header('Registro de Artefatos e Fontes',`${cards.length} fontes canônicas visíveis`,`<button class="primary-button" data-action="export">EXPORTAR MANIFESTO</button>`)}<div class="artifact-grid">${cards.map(({project,source})=>`<article class="artifact-card"><span class="tag">${esc(source.type)}</span><h3>${esc(source.label)}</h3><p>${esc(project.name)} · ${esc(project.domain)}</p><a href="${esc(source.url)}" target="_blank" rel="noreferrer">Abrir fonte canônica</a></article>`).join('')}</div></div>`;bindRepoActions(el.artifacts)}
function renderDependencies(){const map=new Map(all().map(p=>[p.id,p])),ids=new Set(visible().map(p=>p.id)),deps=repo.dependencies().filter(([a,b])=>ids.has(a)&&ids.has(b));el.dependencies.innerHTML=`<div class="content-card">${header('Mapa de Dependências',`${deps.length} relações visíveis`)}${deps.map(([a,b,t])=>`<div class="dependency-row"><div class="dependency-node" data-project-id="${a}">${esc(map.get(a)?.name||a)}</div><div class="dependency-type">${esc(t.toUpperCase())}</div><div class="dependency-node" data-project-id="${b}">${esc(map.get(b)?.name||b)}</div></div>`).join('')}</div>`;bindRows(el.dependencies)}
function renderInsights(){const items=visible(),s=summarizeProjects(items),by=Object.entries(items.reduce((m,p)=>(m[p.domain]=(m[p.domain]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...by.map(([,n])=>n)),attention=items.find(p=>['attention','blocked'].includes(p.status)),stale=items.filter(p=>Date.now()-new Date(p.updatedAt)>2592e6);el.insights.innerHTML=`<div class="content-card">${header('Insights Operacionais','Sinais derivados do manifesto atual')}<div class="insight-grid"><article class="insight-card"><h3>Saúde do portfólio</h3><p>${s.status.active||0} ativos, ${s.status.attention||0} em atenção e ${s.status.archived||0} arquivados.</p></article><article class="insight-card"><h3>Maior risco barato</h3><p>${attention?`${attention.name}: ${attention.nextAction}`:'Nenhum projeto em atenção.'}</p></article><article class="insight-card"><h3>Estado envelhecido</h3><p>${stale.length} projetos sem atualização nos últimos 30 dias.</p></article></div><div class="bar-chart">${by.map(([d,n])=>`<div class="bar-row"><span>${esc(d)}</span><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><b>${n}</b></div>`).join('')}</div></div>`}
function renderView(){({atlas:renderAtlas,list:renderList,timeline:renderTimeline,artifacts:renderArtifacts,dependencies:renderDependencies,insights:renderInsights}[state.view]||renderAtlas)()}
function renderAll(filters=true){renderSummary();if(filters)renderFilters();el.legend.innerHTML=`<div class="section-title">LEGENDA</div>`+Object.values(statusMeta).map(m=>`<div class="legend-line"><span class="legend-swatch" style="background:${m.color}"></span>${m.label}</div>`).join('');renderDetail();renderView()}
function download(name,content){const u=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportManifest(){download(`dener-project-atlas-${new Date().toISOString().slice(0,10)}.json`,repo.exportManifest());notify('Manifesto exportado.')}
async function importManifest(file){const manifest=JSON.parse(await file.text()),check=validateManifest(manifest);if(!check.ok)throw Error(check.errors.join('\n'));repo.replace(manifest);state.selectedId=all()[0]?.id||null;renderAll();notify('Manifesto importado.')}
function openDialog(p=null){$('#dialogTitle').textContent=p?'Editar projeto':'Novo projeto';$('#formProjectId').value=p?.id||'';$('#formName').value=p?.name||'';$('#formDomain').value=p?.domain||'IA / Automação';$('#formStatus').value=p?.status||'exploratory';$('#formPriority').value=p?.priority||3;$('#formSummary').value=p?.summary||'';$('#formClaim').value=p?.claim||'';$('#formNextAction').value=p?.nextAction||'';$('#formSourceUrl').value=p?.sources?.[0]?.url||'';$('#deleteProject').classList.toggle('hidden',!p);el.dialog.showModal()}
function saveForm(){const id=$('#formProjectId').value,current=id?repo.get(id):null,url=$('#formSourceUrl').value.trim(),angle=all().length*.78,value={name:$('#formName').value.trim(),domain:$('#formDomain').value,status:$('#formStatus').value,priority:+$('#formPriority').value,summary:$('#formSummary').value.trim(),claim:$('#formClaim').value.trim(),nextAction:$('#formNextAction').value.trim(),updatedAt:new Date().toISOString(),metrics:current?.metrics||{artifacts:0,repositories:url.includes('github.com')?1:0,documents:url?1:0,runs:0,datasets:0,complexity:3},sources:url?[{type:url.includes('github.com')?'GitHub':'Drive / Web',label:'Fonte principal',url}]:[],position:current?.position||{x:Math.cos(angle)*4,z:Math.sin(angle)*4},size:current?.size||.7,tags:current?.tags||[],activity:[{date:new Date().toLocaleString('pt-BR'),text:current?'Projeto atualizado':'Projeto criado',kind:'update'},...(current?.activity||[])]};if(current)repo.update(id,value);else{const created=repo.add({...value,id:value.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')});state.selectedId=created.id}el.dialog.close();renderAll();notify(current?'Projeto atualizado.':'Projeto criado.')}
function init(){const domains=[...new Set(seedProjects.map(p=>p.domain))];$('#formDomain').innerHTML=domains.map(d=>`<option>${esc(d)}</option>`).join('');$('#formStatus').innerHTML=Object.entries(statusMeta).map(([k,m])=>`<option value="${k}">${m.label}</option>`).join('');$$('.nav-tab,.side-view').forEach(b=>b.onclick=()=>setView(b.dataset.view));const search=v=>{state.search=v;el.global.value=v;el.side.value=v;renderAll(false)};el.global.oninput=e=>search(e.target.value);el.side.oninput=e=>search(e.target.value);$('#clearFilters').onclick=()=>{state.search='';state.domains.clear();state.statuses.clear();state.priorities.clear();search('');renderAll()};$('#isoMode').onclick=()=>{atlas.setMode('iso');$('#isoMode').classList.add('active');$('#topMode').classList.remove('active')};$('#topMode').onclick=()=>{atlas.setMode('top');$('#topMode').classList.add('active');$('#isoMode').classList.remove('active')};$('#rotateLeft').onclick=()=>atlas.rotateBy(-Math.PI/8);$('#rotateRight').onclick=()=>atlas.rotateBy(Math.PI/8);$('#zoomOut').onclick=()=>atlas.zoomBy(-.12);$('#zoomIn').onclick=()=>atlas.zoomBy(.12);$('#resetView').onclick=()=>atlas.reset();$('#newProjectButton').onclick=()=>openDialog();$('#cancelDialog').onclick=()=>el.dialog.close();el.form.onsubmit=e=>{e.preventDefault();saveForm()};$('#deleteProject').onclick=()=>{const id=$('#formProjectId').value;if(id&&confirm('Excluir este projeto do manifesto local?')){repo.remove(id);state.selectedId=all()[0]?.id||null;el.dialog.close();renderAll();notify('Projeto excluído.')}};el.file.onchange=async()=>{const f=el.file.files?.[0];if(!f)return;try{await importManifest(f)}catch(e){alert(`Manifesto inválido:\n${e.message}`)}el.file.value=''};$('#syncButton').onclick=()=>{renderAll();notify('Snapshot local recalculado.')};$('#closeDetail').onclick=()=>el.drawer.classList.remove('open');addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();el.global.focus();el.global.select()}if(e.key==='Escape')el.drawer.classList.remove('open')});renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});document.documentElement.dataset.appReady='true'}
init();
